# generated by hwacha-cc from log_ndtr.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    vlw vv0, va0
    vfdiv.s vv1, vv0, vs63
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    vlw vv0, va0
    vcmpflt.s vp1, vv0, vs0
    @vp1 vfsgnjn.s vv1, vv0, vv0
    @!vp1 vaddw vv1, vv0, vs0
    vfmul.s vv0, vv1, vs63
    vfadd.s vv2, vv0, vs62
    vfdiv.s vv2, vs62, vv2
    vfmul.s vv0, vv2, vs61
    vfadd.s vv3, vv0, vs60
    vfmul.s vv3, vv3, vv2
    vfadd.s vv3, vv3, vs59
    vfmul.s vv3, vv3, vv2
    vfadd.s vv3, vv3, vs58
    vfmul.s vv3, vv3, vv2
    vfadd.s vv3, vv3, vs57
    vfmul.s vv3, vv3, vv2
    vfsgnjn.s vv0, vv1, vv1
    vfmul.s vv1, vv1, vv0
    vfmax.s vv1, vv1, vs56
    vfmin.s vv1, vv1, vs55
    vfmul.s vv0, vv1, vs54
    vfadd.s vv2, vv0, vs53
    vfadd.s vv0, vv2, vs52
    vfmul.s vv4, vv0, vs51
    vfsub.s vv1, vv1, vv4
    vfmul.s vv4, vv0, vs50
    vfsub.s vv1, vv1, vv4
    vfmul.s vv0, vv1, vs49
    vfadd.s vv4, vv0, vs48
    vfmul.s vv4, vv4, vv1
    vfadd.s vv4, vv4, vs47
    vfmul.s vv4, vv4, vv1
    vfadd.s vv4, vv4, vs46
    vfmul.s vv4, vv4, vv1
    vfadd.s vv4, vv4, vs45
    vfmul.s vv4, vv4, vv1
    vfadd.s vv4, vv4, vs44
    vfmul.s vv0, vv1, vv1
    vfmul.s vv4, vv4, vv0
    vfadd.s vv4, vv4, vv1
    vfadd.s vv4, vv4, vs62
    vsllw vv0, vv2, vs43
    vaddw vv1, vv0, vv4
    vfmul.s vv3, vv3, vv1
    vfsub.s vv3, vs62, vv3
    @vp1 vfsgnjn.s vv0, vv3, vv3
    @!vp1 vaddw vv0, vv3, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    vlw vv0, va0
    vfadd.s vv1, vv0, vs63
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    vlw vv0, va0
    vfmul.s vv1, vv0, vs63
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    vlw vv0, va0
    vsrlw vv1, vv0, vs63
    vand vv1, vv1, vs62
    vand vv2, vv0, vs61
    vor vv2, vv2, vs60
    vcmpflt.s vp1, vv2, vs59
    @vp1 vaddw vv0, vs58, vs0
    @!vp1 vaddw vv0, vs57, vs0
    vaddw vv1, vv1, vv0
    vfcvt.s.w vv1, vv1
    @vp1 vaddw vv0, vv2, vs0
    @!vp1 vaddw vv0, vs56, vs0
    vfadd.s vv3, vv0, vv2
    vfadd.s vv3, vv3, vs55
    vfmul.s vv0, vv3, vv3
    vfmul.s vv2, vv3, vs54
    vfadd.s vv2, vv2, vs53
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs52
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs51
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs50
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs49
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs48
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs47
    vfmul.s vv2, vv2, vv3
    vfadd.s vv2, vv2, vs46
    vfmul.s vv2, vv2, vv3
    vfmul.s vv2, vv2, vv0
    vfmul.s vv4, vv1, vs45
    vfadd.s vv2, vv2, vv4
    vfmul.s vv4, vv0, vs44
    vfsub.s vv2, vv2, vv4
    vfadd.s vv3, vv3, vv2
    vfmul.s vv1, vv1, vs43
    vfadd.s vv3, vv3, vv1
    vsw vv3, va0
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	lui	a4, 260944
	slli	a3, a3, 9
	addi	a4, a4, 1267
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a5, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi1)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi1)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi0)(a3)
	mv	a6, a0
	beqz	a7, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a7
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a6
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 81
	lui	a3, 256636
	slli	a2, a2, 10
	addi	a3, a3, -1531
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	lui	a2, 260096
	#APP
	vmcs vs62, a2
	#NO_APP
	lui	a2, 24541
	lui	a3, 260222
	slli	a2, a2, 5
	addi	a3, a3, -990
	addi	a2, a2, 227
	#APP
	vmcs vs61, a3
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	lui	a2, 260959
	lui	a3, 390285
	addi	a2, a2, 227
	addi	a3, a3, 1223
	#APP
	vmcs vs59, a2
	#NO_APP
	slli	a3, a3, 1
	#APP
	vmcs vs58, a3
	#NO_APP
	lui	a2, 256040
	addi	a2, a2, -1786
	lui	a3, 24919
	#APP
	vmcs vs57, a2
	#NO_APP
	slli	a3, a3, 5
	#APP
	vmcs vs56, a3
	#NO_APP
	lui	a2, 273152
	#APP
	vmcs vs55, a2
	#NO_APP
	lui	a2, 261003
	addi	a2, a2, -1477
	lui	a3, 308224
	#APP
	vmcs vs54, a2
	#NO_APP
	#APP
	vmcs vs53, a3
	#NO_APP
	li	a2, 813
	lui	a3, 258839
	slli	a2, a2, 22
	addi	a3, a3, 512
	#APP
	vmcs vs52, a2
	#NO_APP
	#APP
	vmcs vs51, a3
	#NO_APP
	lui	a2, 220156
	lui	a3, 234759
	addi	a2, a2, -370
	addi	a3, a3, -1689
	#APP
	vmcs vs50, a2
	#NO_APP
	#APP
	vmcs vs49, a3
	#NO_APP
	lui	a2, 240500
	lui	a3, 245897
	addi	a2, a2, 974
	addi	a3, a3, -1784
	#APP
	vmcs vs48, a2
	#NO_APP
	#APP
	vmcs vs47, a3
	#NO_APP
	lui	a2, 250539
	lui	a3, 254635
	addi	a2, a2, -1599
	addi	a3, a3, -1366
	#APP
	vmcs vs46, a2
	#NO_APP
	#APP
	vmcs vs45, a3
	#NO_APP
	lui	a2, 258048
	li	a3, 23
	#APP
	vmcs vs44, a2
	#NO_APP
	#APP
	vmcs vs43, a3
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi3:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a4, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi4:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi4)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi4)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi3)(a2)
	mv	a5, a0
	beqz	a6, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a5, a6
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a5
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	lui	a3, 260096
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi6:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi8:
	auipc	a4, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi7:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi8)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi7)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi7)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi6)(a2)
	mv	a5, a0
	beqz	a6, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a5, a6
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a5
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	lui	a3, 258048
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi9:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi11:
	auipc	a4, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi10:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi11)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi10)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi10)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi9)(a2)
	mv	a5, a0
	beqz	a6, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a5, a6
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a5
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 81
	li	a3, 23
	slli	a2, a2, 10
	li	a4, 255
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	lui	a2, 526336
	#APP
	vmcs vs62, a4
	#NO_APP
	addi	a2, a2, -1
	#APP
	vmcs vs61, a2
	#NO_APP
	lui	a3, 258896
	lui	a2, 258048
	addi	a3, a3, 1267
	#APP
	vmcs vs60, a2
	#NO_APP
	#APP
	vmcs vs59, a3
	#NO_APP
	li	a3, -127
	li	a4, -126
	#APP
	vmcs vs58, a3
	#NO_APP
	#APP
	vmcs vs57, a4
	#NO_APP
	li	a3, 1
	li	a4, 383
	slli	a3, a3, 31
	slli	a4, a4, 23
	#APP
	vmcs vs56, a3
	#NO_APP
	#APP
	vmcs vs55, a4
	#NO_APP
	lui	a3, 252162
	lui	a4, 97240
	addi	a3, a3, 443
	addi	a4, a4, -1481
	#APP
	vmcs vs54, a3
	#NO_APP
	slli	a4, a4, 3
	#APP
	vmcs vs53, a4
	#NO_APP
	lui	a3, 389107
	lui	a4, 253682
	slli	a3, a3, 1
	addi	a4, a4, 1306
	addi	a3, a3, -689
	#APP
	vmcs vs52, a4
	#NO_APP
	#APP
	vmcs vs51, a3
	#NO_APP
	lui	a3, 254239
	lui	a4, 48683
	addi	a3, a3, -1601
	addi	a4, a4, -1307
	#APP
	vmcs vs50, a3
	#NO_APP
	slli	a4, a4, 4
	#APP
	vmcs vs49, a4
	#NO_APP
	li	a3, 381
	lui	a4, 255181
	slli	a3, a3, 23
	addi	a4, a4, -340
	addi	a3, a3, -4
	#APP
	vmcs vs48, a4
	#NO_APP
	#APP
	vmcs vs47, a3
	#NO_APP
	lui	a3, 256683
	lui	a4, 94909
	addi	a3, a3, -1366
	slli	a4, a4, 3
	#APP
	vmcs vs46, a3
	#NO_APP
	addi	a3, a4, 131
	#APP
	vmcs vs45, a3
	#NO_APP
	lui	a3, 258840
	#APP
	vmcs vs44, a2
	#NO_APP
	#APP
	vmcs vs43, a3
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi12:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi14:
	auipc	a4, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi13:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi14)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi13)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi13)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi12)(a2)
	mv	a5, a0
	beqz	a6, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a5, a6
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a5
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -64
	.cfi_def_cfa_offset 64
	sd	ra, 56(sp)                      # 8-byte Folded Spill
	sd	s0, 48(sp)                      # 8-byte Folded Spill
	sd	s1, 40(sp)                      # 8-byte Folded Spill
	sd	s2, 32(sp)                      # 8-byte Folded Spill
	sd	s3, 24(sp)                      # 8-byte Folded Spill
	sd	s4, 16(sp)                      # 8-byte Folded Spill
	sd	s5, 8(sp)                       # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	mv	s0, a0
	li	a0, 320
	call	malloc
	mv	s1, a0
.Lpcrel_hi15:
	auipc	s3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi16:
	auipc	s4, %pcrel_hi(hwacha_grid_size)
	addi	a0, a0, 63
	li	s5, 64
	andi	s2, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s3)
	sd	s5, %pcrel_lo(.Lpcrel_hi16)(s4)
	li	a0, 64
	mv	a1, s0
	mv	a2, s2
	call	net_kernel_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s3)
	sd	s5, %pcrel_lo(.Lpcrel_hi16)(s4)
	li	a0, 64
	mv	a1, s2
	call	net_kernel_0_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s3)
	sd	s5, %pcrel_lo(.Lpcrel_hi16)(s4)
	li	a0, 64
	mv	a1, s2
	call	net_kernel_1_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s3)
	sd	s5, %pcrel_lo(.Lpcrel_hi16)(s4)
	li	a0, 64
	mv	a1, s2
	call	net_kernel_2_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s3)
	sd	s5, %pcrel_lo(.Lpcrel_hi16)(s4)
	li	a0, 64
	mv	a1, s2
	call	net_kernel_3_ct
	mv	a0, s1
	ld	ra, 56(sp)                      # 8-byte Folded Reload
	ld	s0, 48(sp)                      # 8-byte Folded Reload
	ld	s1, 40(sp)                      # 8-byte Folded Reload
	ld	s2, 32(sp)                      # 8-byte Folded Reload
	ld	s3, 24(sp)                      # 8-byte Folded Reload
	ld	s4, 16(sp)                      # 8-byte Folded Reload
	ld	s5, 8(sp)                       # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	addi	sp, sp, 64
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end5:
	.size	net, .Lfunc_end5-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.section	".note.GNU-stack","",@progbits
