# generated by hwacha-cc from ar_link_predictor.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsrl vv1, vv0, vs61
    vsll vv2, vv0, vs60
    vand vv2, vv2, vs59
    vsll vv1, vv1, vs58
    vadd vv2, vv2, vv1
    vlxw vv3, vs62, vv2
    vsw vv3, va0
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs60
    vsrl vv2, vv0, vs59
    vsrl vv3, vv0, vs58
    vsll vv3, vv3, vs57
    vlxw vv4, vs62, vv3
    vsll vv1, vv1, vs56
    vlxw vv5, vs61, vv1
    vlw vv6, va0
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs57
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs55
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs54
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs53
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vor vv2, vv2, vs58
    vsll vv2, vv2, vs56
    vlxw vv4, vs62, vv2
    vadd vs2, vs61, vs52
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vsw vv6, va0
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs61
    vlw vv2, va0
    vsll vv1, vv1, vs60
    vlxw vv3, vs62, vv1
    vfadd.s vv3, vv2, vv3
    vsw vv3, va0
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    vlw vv0, va0
    vcmpfle.s vp1, vv0, vs0
    @vp1 vaddw vv1, vs0, vs0
    @!vp1 vaddw vv1, vv0, vs0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_4_wt
net_kernel_4_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsrl vv1, vv0, vs61
    vsll vv2, vv0, vs60
    vand vv2, vv2, vs59
    vsll vv1, vv1, vs61
    vadd vv2, vv2, vv1
    vlxw vv3, vs62, vv2
    vsw vv3, va0
    vstop

    .text
    .align 3
    .globl net_kernel_5_wt
net_kernel_5_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_6_wt
net_kernel_6_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_7_wt
net_kernel_7_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs60
    vsll vv2, vv0, vs59
    vsrl vv3, vv0, vs58
    vsll vv3, vv3, vs57
    vlxw vv4, vs62, vv3
    vsll vv1, vv1, vs58
    vlxw vv5, vs61, vv1
    vlw vv6, va0
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs56
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs55
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs54
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs53
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs52
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs51
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs55
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs50
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs49
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs48
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vor vv3, vv2, vs47
    vsll vv3, vv3, vs58
    vlxw vv4, vs62, vv3
    vadd vs2, vs61, vs46
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vor vv2, vv2, vs45
    vsll vv2, vv2, vs58
    vlxw vv4, vs62, vv2
    vadd vs2, vs61, vs44
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vsw vv6, va0
    vstop

    .text
    .align 3
    .globl net_kernel_8_wt
net_kernel_8_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs61
    vlw vv2, va0
    vsll vv1, vv1, vs60
    vlxw vv3, vs62, vv1
    vfadd.s vv3, vv2, vv3
    vsw vv3, va1
    vstop

    .text
    .align 3
    .globl net_kernel_9_wt
net_kernel_9_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsrl vv1, vv0, vs61
    vsll vv2, vv0, vs60
    vand vv2, vv2, vs59
    vsll vv1, vv1, vs61
    vadd vv2, vv2, vv1
    vlxw vv3, vs62, vv2
    vsw vv3, va0
    vstop

    .text
    .align 3
    .globl net_kernel_10_wt
net_kernel_10_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs60
    vsll vv2, vv0, vs59
    vsrl vv3, vv0, vs58
    vsll vv3, vv3, vs57
    vlxw vv4, vs62, vv3
    vsll vv1, vv1, vs58
    vlxw vv5, vs61, vv1
    vlw vv6, va0
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs56
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs55
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs54
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs53
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs52
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs51
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs55
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs50
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vadd vs2, vs62, vs49
    vlxw vv4, vs2, vv3
    vadd vs2, vs61, vs48
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vor vv3, vv2, vs47
    vsll vv3, vv3, vs58
    vlxw vv4, vs62, vv3
    vadd vs2, vs61, vs46
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vor vv2, vv2, vs45
    vsll vv2, vv2, vs58
    vlxw vv4, vs62, vv2
    vadd vs2, vs61, vs44
    vlxw vv5, vs2, vv1
    vfmul.s vv5, vv4, vv5
    vfadd.s vv6, vv6, vv5
    vsw vv6, va0
    vstop

    .text
    .align 3
    .globl net_kernel_11_wt
net_kernel_11_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs61
    vlw vv2, va0
    vsll vv1, vv1, vs60
    vlxw vv3, vs62, vv1
    vfadd.s vv3, vv2, vv3
    vsw vv3, va1
    vstop

    .text
    .align 3
    .globl net_kernel_12_wt
net_kernel_12_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs60
    vsrl vv2, vv0, vs59
    vsll vv2, vv2, vs60
    vlxd vv3, vs62, vv2
    vsrl vv2, vv3, vs58
    vsll vv2, vv2, vs57
    vsll vv3, vv3, vs56
    vadd vv2, vv2, vv3
    vsll vv1, vv1, vs59
    vadd vv2, vv2, vv1
    vlxw vv4, vs61, vv2
    vsw vv4, va0
    vstop

    .text
    .align 3
    .globl net_kernel_13_wt
net_kernel_13_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs61
    vsrl vv2, vv0, vs60
    vadd vs2, vs59, vs58
    vsll vv2, vv2, vs61
    vlxd vv3, vs2, vv2
    vsrl vv2, vv3, vs57
    vsll vv2, vv2, vs56
    vsll vv3, vv3, vs55
    vadd vv2, vv2, vv3
    vsll vv1, vv1, vs60
    vadd vv2, vv2, vv1
    vlxw vv4, vs62, vv2
    vsw vv4, va0
    vstop

    .text
    .align 3
    .globl net_kernel_14_wt
net_kernel_14_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs60
    vsrl vv2, vv0, vs59
    vsll vv2, vv2, vs60
    vlxd vv3, vs61, vv2
    vsrl vv2, vv3, vs58
    vsll vv2, vv2, vs57
    vsll vv3, vv3, vs56
    vadd vv2, vv2, vv3
    vsll vv1, vv1, vs59
    vadd vv2, vv2, vv1
    vlxw vv4, vs62, vv2
    vsw vv4, va0
    vstop

    .text
    .align 3
    .globl net_kernel_15_wt
net_kernel_15_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs61
    vsrl vv2, vv0, vs60
    vadd vs2, vs59, vs58
    vsll vv2, vv2, vs61
    vlxd vv3, vs2, vv2
    vsrl vv2, vv3, vs57
    vsll vv2, vv2, vs56
    vsll vv3, vv3, vs55
    vadd vv2, vv2, vv3
    vsll vv1, vv1, vs60
    vadd vv2, vv2, vv1
    vlxw vv4, vs62, vv2
    vsw vv4, va0
    vstop

    .text
    .align 3
    .globl net_kernel_16_wt
net_kernel_16_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfmul.s vv1, vv0, vv1
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_17_wt
net_kernel_17_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_18_wt
net_kernel_18_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_19_wt
net_kernel_19_wt:
    vpset vp0
    vlstw vv0, va0, va5
    vlw vv1, va1
    vfadd.s vv1, vv0, vv1
    vlstw vv0, va2, va6
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va3, va7
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va4, va8
    vfadd.s vv1, vv1, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_20_wt
net_kernel_20_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfmul.s vv1, vv0, vv1
    vsw vv1, va2
    vstop

    .text
    .align 3
    .globl net_kernel_21_wt
net_kernel_21_wt:
    vpset vp0
    vlstw vv0, va0, va5
    vlw vv1, va1
    vfadd.s vv1, vv0, vv1
    vlstw vv0, va2, va6
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va3, va7
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va4, va8
    vfadd.s vv1, vv1, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_22_wt
net_kernel_22_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfsub.s vv1, vv0, vv1
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_23_wt
net_kernel_23_wt:
    vpset vp0
    vlw vv0, va0
    vfsgnjn.s vv1, vv0, vv0
    vfmax.s vv1, vv1, vs63
    vfmin.s vv1, vv1, vs62
    vfmul.s vv0, vv1, vs61
    vfadd.s vv2, vv0, vs60
    vfadd.s vv0, vv2, vs59
    vfmul.s vv3, vv0, vs58
    vfsub.s vv1, vv1, vv3
    vfmul.s vv3, vv0, vs57
    vfsub.s vv1, vv1, vv3
    vfmul.s vv0, vv1, vs56
    vfadd.s vv3, vv0, vs55
    vfmul.s vv3, vv3, vv1
    vfadd.s vv3, vv3, vs54
    vfmul.s vv3, vv3, vv1
    vfadd.s vv3, vv3, vs53
    vfmul.s vv3, vv3, vv1
    vfadd.s vv3, vv3, vs52
    vfmul.s vv3, vv3, vv1
    vfadd.s vv3, vv3, vs51
    vfmul.s vv0, vv1, vv1
    vfmul.s vv3, vv3, vv0
    vfadd.s vv3, vv3, vv1
    vfadd.s vv3, vv3, vs50
    vsllw vv0, vv2, vs49
    vaddw vv1, vv0, vv3
    vfadd.s vv0, vv1, vs50
    vfdiv.s vv1, vs50, vv0
    vsw vv1, va0
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a2, 1048568
	addi	a2, a2, -1031
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(__constant_8x4xf32)
	srli	a2, a2, 1
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi0)
	not	a2, a2
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs62, a3
	#NO_APP
	li	a2, 3
	li	a3, 4
	#APP
	vmcs vs61, a2
	#NO_APP
	#APP
	vmcs vs60, a3
	#NO_APP
	li	a2, 112
	li	a3, 2
	#APP
	vmcs vs59, a2
	#NO_APP
	#APP
	vmcs vs58, a3
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi1:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi3:
	auipc	a5, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi2:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi3)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi2)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi2)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi1)(a3)
	mv	a6, a0
	beqz	a7, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a7
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a6
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi4:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi6:
	auipc	a4, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi5:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi6)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi5)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi5)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi4)(a2)
	mv	a5, a0
	beqz	a6, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a5, a6
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a5
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048552
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	li	a1, 7
	#APP
	vmcs vs61, a2
	#NO_APP
	#APP
	vmcs vs60, a1
	#NO_APP
	li	a1, 1
	li	a2, 3
	#APP
	vmcs vs59, a1
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a1, 4
	li	a2, 2
	#APP
	vmcs vs57, a1
	#NO_APP
	#APP
	vmcs vs56, a2
	#NO_APP
	li	a1, 32
	li	a2, 8
	#APP
	vmcs vs55, a1
	#NO_APP
	#APP
	vmcs vs54, a2
	#NO_APP
	li	a1, 64
	li	a2, 96
	#APP
	vmcs vs53, a1
	#NO_APP
	#APP
	vmcs vs52, a2
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi7:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi9:
	auipc	a5, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi8:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi9)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi8)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi8)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi7)(a2)
	mv	a6, a0
	beqz	a7, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a7
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a6
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a2, 1048560
	addi	a2, a2, -1029
.Lpcrel_hi10:
	auipc	a3, %pcrel_hi(__constant_8xf32)
	srli	a2, a2, 1
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi10)
	not	a2, a2
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs62, a3
	#NO_APP
	li	a2, 7
	li	a3, 2
	#APP
	vmcs vs61, a2
	#NO_APP
	#APP
	vmcs vs60, a3
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi11:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi13:
	auipc	a5, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi12:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi13)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi12)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi12)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi11)(a3)
	mv	a6, a0
	beqz	a7, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a7
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a6
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 33
	slli	a2, a2, 10
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi14:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi16:
	auipc	a4, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi15:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi16)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi15)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi15)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi14)(a2)
	mv	a5, a0
	beqz	a6, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a5, a6
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a5
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_4_ct                 # -- Begin function net_kernel_4_ct
	.p2align	2
	.type	net_kernel_4_ct,@function
net_kernel_4_ct:                        # @net_kernel_4_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a2, 1048568
	addi	a2, a2, -1031
	srli	a2, a2, 1
	not	a2, a2
.Lpcrel_hi17:
	auipc	a3, %pcrel_hi(__constant_4x8xf32_1)
	#APP
	vsetcfg a2
	#NO_APP
	li	a2, 2
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi17)
	#APP
	vmcs vs62, a3
	#NO_APP
	#APP
	vmcs vs61, a2
	#NO_APP
	li	a2, 5
	li	a3, 96
	#APP
	vmcs vs60, a2
	#NO_APP
	#APP
	vmcs vs59, a3
	#NO_APP
	beqz	a0, .LBB5_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi18:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi20:
	auipc	a5, %pcrel_hi(net_kernel_4_wt)
.Lpcrel_hi19:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi20)
	j	.LBB5_3
.LBB5_2:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi19)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi19)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB5_7
.LBB5_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi18)(a3)
	mv	a6, a0
	beqz	a7, .LBB5_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a6, a7
.LBB5_5:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB5_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a6
	j	.LBB5_2
.LBB5_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end5:
	.size	net_kernel_4_ct, .Lfunc_end5-net_kernel_4_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_5_ct                 # -- Begin function net_kernel_5_ct
	.p2align	2
	.type	net_kernel_5_ct,@function
net_kernel_5_ct:                        # @net_kernel_5_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB6_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi21:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi23:
	auipc	a4, %pcrel_hi(net_kernel_5_wt)
.Lpcrel_hi22:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi23)
	j	.LBB6_3
.LBB6_2:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi22)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi22)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB6_7
.LBB6_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi21)(a2)
	mv	a5, a0
	beqz	a6, .LBB6_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a5, a6
.LBB6_5:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB6_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a5
	j	.LBB6_2
.LBB6_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end6:
	.size	net_kernel_5_ct, .Lfunc_end6-net_kernel_5_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_6_ct                 # -- Begin function net_kernel_6_ct
	.p2align	2
	.type	net_kernel_6_ct,@function
net_kernel_6_ct:                        # @net_kernel_6_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB7_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi24:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi26:
	auipc	a5, %pcrel_hi(net_kernel_6_wt)
.Lpcrel_hi25:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi26)
	j	.LBB7_3
.LBB7_2:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi25)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi25)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB7_7
.LBB7_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi24)(a3)
	mv	a6, a0
	beqz	a7, .LBB7_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a7
.LBB7_5:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB7_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a7, a6
	j	.LBB7_2
.LBB7_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end7:
	.size	net_kernel_6_ct, .Lfunc_end7-net_kernel_6_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_7_ct                 # -- Begin function net_kernel_7_ct
	.p2align	2
	.type	net_kernel_7_ct,@function
net_kernel_7_ct:                        # @net_kernel_7_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048552
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	li	a1, 3
	#APP
	vmcs vs61, a2
	#NO_APP
	#APP
	vmcs vs60, a1
	#NO_APP
	li	a1, 1
	li	a2, 2
	#APP
	vmcs vs59, a1
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a1, 5
	li	a2, 4
	#APP
	vmcs vs57, a1
	#NO_APP
	#APP
	vmcs vs56, a2
	#NO_APP
	li	a1, 16
	li	a2, 8
	#APP
	vmcs vs55, a1
	#NO_APP
	#APP
	vmcs vs54, a2
	#NO_APP
	li	a1, 32
	li	a2, 12
	#APP
	vmcs vs53, a1
	#NO_APP
	#APP
	vmcs vs52, a2
	#NO_APP
	li	a1, 48
	li	a2, 64
	#APP
	vmcs vs51, a1
	#NO_APP
	#APP
	vmcs vs50, a2
	#NO_APP
	li	a1, 20
	li	a2, 80
	#APP
	vmcs vs49, a1
	#NO_APP
	#APP
	vmcs vs48, a2
	#NO_APP
	li	a1, 6
	li	a2, 96
	#APP
	vmcs vs47, a1
	#NO_APP
	#APP
	vmcs vs46, a2
	#NO_APP
	li	a1, 7
	li	a2, 112
	#APP
	vmcs vs45, a1
	#NO_APP
	#APP
	vmcs vs44, a2
	#NO_APP
	beqz	a0, .LBB8_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi27:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi29:
	auipc	a5, %pcrel_hi(net_kernel_7_wt)
.Lpcrel_hi28:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi29)
	j	.LBB8_3
.LBB8_2:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi28)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi28)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB8_7
.LBB8_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi27)(a2)
	mv	a6, a0
	beqz	a7, .LBB8_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a6, a7
.LBB8_5:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB8_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a7, a6
	j	.LBB8_2
.LBB8_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end8:
	.size	net_kernel_7_ct, .Lfunc_end8-net_kernel_7_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_8_ct                 # -- Begin function net_kernel_8_ct
	.p2align	2
	.type	net_kernel_8_ct,@function
net_kernel_8_ct:                        # @net_kernel_8_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048560
	addi	a3, a3, -1029
	srli	a3, a3, 1
.Lpcrel_hi30:
	auipc	a4, %pcrel_hi(__constant_4xf32_0)
	not	a3, a3
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi30)
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a4
	#NO_APP
	li	a3, 3
	li	a4, 2
	#APP
	vmcs vs61, a3
	#NO_APP
	#APP
	vmcs vs60, a4
	#NO_APP
	beqz	a0, .LBB9_7
# %bb.1:                                # %stripmine.preheader
	li	a3, 0
.Lpcrel_hi31:
	auipc	a4, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi33:
	auipc	a6, %pcrel_hi(net_kernel_8_wt)
.Lpcrel_hi32:
	auipc	a5, %pcrel_hi(hwacha_vl_short)
	addi	a6, a6, %pcrel_lo(.Lpcrel_hi33)
	j	.LBB9_3
.LBB9_2:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	#APP
	vsetvl a7, t0
	#NO_APP
	ld	t1, %pcrel_lo(.Lpcrel_hi32)(a5)
	sltu	t0, a7, t0
	sub	a0, a0, a7
	or	t0, t1, t0
	slli	t1, a7, 2
	sd	t0, %pcrel_lo(.Lpcrel_hi32)(a5)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	#APP
	vf 0(a6)
	#NO_APP
	add	a3, a3, a7
	add	a1, a1, t1
	add	a2, a2, t1
	beqz	a0, .LBB9_7
.LBB9_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t0, %pcrel_lo(.Lpcrel_hi31)(a4)
	mv	a7, a0
	beqz	t0, .LBB9_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a7, t0
.LBB9_5:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	t0, a0
	bltu	a0, a7, .LBB9_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	t0, a7
	j	.LBB9_2
.LBB9_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end9:
	.size	net_kernel_8_ct, .Lfunc_end9-net_kernel_8_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_9_ct                 # -- Begin function net_kernel_9_ct
	.p2align	2
	.type	net_kernel_9_ct,@function
net_kernel_9_ct:                        # @net_kernel_9_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a2, 1048568
	addi	a2, a2, -1031
	srli	a2, a2, 1
	not	a2, a2
.Lpcrel_hi34:
	auipc	a3, %pcrel_hi(__constant_4x8xf32)
	#APP
	vsetcfg a2
	#NO_APP
	li	a2, 2
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi34)
	#APP
	vmcs vs62, a3
	#NO_APP
	#APP
	vmcs vs61, a2
	#NO_APP
	li	a2, 5
	li	a3, 96
	#APP
	vmcs vs60, a2
	#NO_APP
	#APP
	vmcs vs59, a3
	#NO_APP
	beqz	a0, .LBB10_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi35:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi37:
	auipc	a5, %pcrel_hi(net_kernel_9_wt)
.Lpcrel_hi36:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi37)
	j	.LBB10_3
.LBB10_2:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi36)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi36)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB10_7
.LBB10_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi35)(a3)
	mv	a6, a0
	beqz	a7, .LBB10_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a6, a7
.LBB10_5:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB10_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a7, a6
	j	.LBB10_2
.LBB10_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end10:
	.size	net_kernel_9_ct, .Lfunc_end10-net_kernel_9_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_10_ct                # -- Begin function net_kernel_10_ct
	.p2align	2
	.type	net_kernel_10_ct,@function
net_kernel_10_ct:                       # @net_kernel_10_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048552
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	li	a1, 3
	#APP
	vmcs vs61, a2
	#NO_APP
	#APP
	vmcs vs60, a1
	#NO_APP
	li	a1, 1
	li	a2, 2
	#APP
	vmcs vs59, a1
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a1, 5
	li	a2, 4
	#APP
	vmcs vs57, a1
	#NO_APP
	#APP
	vmcs vs56, a2
	#NO_APP
	li	a1, 16
	li	a2, 8
	#APP
	vmcs vs55, a1
	#NO_APP
	#APP
	vmcs vs54, a2
	#NO_APP
	li	a1, 32
	li	a2, 12
	#APP
	vmcs vs53, a1
	#NO_APP
	#APP
	vmcs vs52, a2
	#NO_APP
	li	a1, 48
	li	a2, 64
	#APP
	vmcs vs51, a1
	#NO_APP
	#APP
	vmcs vs50, a2
	#NO_APP
	li	a1, 20
	li	a2, 80
	#APP
	vmcs vs49, a1
	#NO_APP
	#APP
	vmcs vs48, a2
	#NO_APP
	li	a1, 6
	li	a2, 96
	#APP
	vmcs vs47, a1
	#NO_APP
	#APP
	vmcs vs46, a2
	#NO_APP
	li	a1, 7
	li	a2, 112
	#APP
	vmcs vs45, a1
	#NO_APP
	#APP
	vmcs vs44, a2
	#NO_APP
	beqz	a0, .LBB11_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi38:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi40:
	auipc	a5, %pcrel_hi(net_kernel_10_wt)
.Lpcrel_hi39:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi40)
	j	.LBB11_3
.LBB11_2:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi39)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi39)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB11_7
.LBB11_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi38)(a2)
	mv	a6, a0
	beqz	a7, .LBB11_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a6, a7
.LBB11_5:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB11_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a7, a6
	j	.LBB11_2
.LBB11_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end11:
	.size	net_kernel_10_ct, .Lfunc_end11-net_kernel_10_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_11_ct                # -- Begin function net_kernel_11_ct
	.p2align	2
	.type	net_kernel_11_ct,@function
net_kernel_11_ct:                       # @net_kernel_11_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048560
	addi	a3, a3, -1029
	srli	a3, a3, 1
.Lpcrel_hi41:
	auipc	a4, %pcrel_hi(__constant_4xf32)
	not	a3, a3
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi41)
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a4
	#NO_APP
	li	a3, 3
	li	a4, 2
	#APP
	vmcs vs61, a3
	#NO_APP
	#APP
	vmcs vs60, a4
	#NO_APP
	beqz	a0, .LBB12_7
# %bb.1:                                # %stripmine.preheader
	li	a3, 0
.Lpcrel_hi42:
	auipc	a4, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi44:
	auipc	a6, %pcrel_hi(net_kernel_11_wt)
.Lpcrel_hi43:
	auipc	a5, %pcrel_hi(hwacha_vl_short)
	addi	a6, a6, %pcrel_lo(.Lpcrel_hi44)
	j	.LBB12_3
.LBB12_2:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	#APP
	vsetvl a7, t0
	#NO_APP
	ld	t1, %pcrel_lo(.Lpcrel_hi43)(a5)
	sltu	t0, a7, t0
	sub	a0, a0, a7
	or	t0, t1, t0
	slli	t1, a7, 2
	sd	t0, %pcrel_lo(.Lpcrel_hi43)(a5)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	#APP
	vf 0(a6)
	#NO_APP
	add	a3, a3, a7
	add	a1, a1, t1
	add	a2, a2, t1
	beqz	a0, .LBB12_7
.LBB12_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t0, %pcrel_lo(.Lpcrel_hi42)(a4)
	mv	a7, a0
	beqz	t0, .LBB12_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a7, t0
.LBB12_5:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	t0, a0
	bltu	a0, a7, .LBB12_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	t0, a7
	j	.LBB12_2
.LBB12_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end12:
	.size	net_kernel_11_ct, .Lfunc_end12-net_kernel_11_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_12_ct                # -- Begin function net_kernel_12_ct
	.p2align	2
	.type	net_kernel_12_ct,@function
net_kernel_12_ct:                       # @net_kernel_12_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048568
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	li	a1, 3
	#APP
	vmcs vs61, a2
	#NO_APP
	#APP
	vmcs vs60, a1
	#NO_APP
	li	a1, 2
	li	a2, 63
	#APP
	vmcs vs59, a1
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a1, 7
	li	a2, 4
	#APP
	vmcs vs57, a1
	#NO_APP
	#APP
	vmcs vs56, a2
	#NO_APP
	beqz	a0, .LBB13_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi45:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi47:
	auipc	a5, %pcrel_hi(net_kernel_12_wt)
.Lpcrel_hi46:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi47)
	j	.LBB13_3
.LBB13_2:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi46)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi46)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB13_7
.LBB13_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi45)(a2)
	mv	a6, a0
	beqz	a7, .LBB13_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a6, a7
.LBB13_5:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB13_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a7, a6
	j	.LBB13_2
.LBB13_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end13:
	.size	net_kernel_12_ct, .Lfunc_end13-net_kernel_12_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_13_ct                # -- Begin function net_kernel_13_ct
	.p2align	2
	.type	net_kernel_13_ct,@function
net_kernel_13_ct:                       # @net_kernel_13_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048568
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	li	a2, 3
	#APP
	vmcs vs61, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs60, a2
	#NO_APP
	#APP
	vmcs vs59, a1
	#NO_APP
	li	a1, 128
	li	a2, 63
	#APP
	vmcs vs58, a1
	#NO_APP
	#APP
	vmcs vs57, a2
	#NO_APP
	li	a1, 7
	li	a2, 4
	#APP
	vmcs vs56, a1
	#NO_APP
	#APP
	vmcs vs55, a2
	#NO_APP
	beqz	a0, .LBB14_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi48:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi50:
	auipc	a5, %pcrel_hi(net_kernel_13_wt)
.Lpcrel_hi49:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi50)
	j	.LBB14_3
.LBB14_2:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi49)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi49)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB14_7
.LBB14_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi48)(a2)
	mv	a6, a0
	beqz	a7, .LBB14_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a6, a7
.LBB14_5:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB14_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a7, a6
	j	.LBB14_2
.LBB14_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end14:
	.size	net_kernel_13_ct, .Lfunc_end14-net_kernel_13_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_14_ct                # -- Begin function net_kernel_14_ct
	.p2align	2
	.type	net_kernel_14_ct,@function
net_kernel_14_ct:                       # @net_kernel_14_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048568
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	li	a2, 3
	#APP
	vmcs vs61, a1
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	li	a1, 2
	li	a2, 63
	#APP
	vmcs vs59, a1
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a1, 7
	li	a2, 4
	#APP
	vmcs vs57, a1
	#NO_APP
	#APP
	vmcs vs56, a2
	#NO_APP
	beqz	a0, .LBB15_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi51:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi53:
	auipc	a5, %pcrel_hi(net_kernel_14_wt)
.Lpcrel_hi52:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi53)
	j	.LBB15_3
.LBB15_2:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi52)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi52)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB15_7
.LBB15_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi51)(a2)
	mv	a6, a0
	beqz	a7, .LBB15_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a6, a7
.LBB15_5:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB15_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a7, a6
	j	.LBB15_2
.LBB15_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end15:
	.size	net_kernel_14_ct, .Lfunc_end15-net_kernel_14_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_15_ct                # -- Begin function net_kernel_15_ct
	.p2align	2
	.type	net_kernel_15_ct,@function
net_kernel_15_ct:                       # @net_kernel_15_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048568
	addi	a4, a4, -1033
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	li	a2, 3
	#APP
	vmcs vs61, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs60, a2
	#NO_APP
	#APP
	vmcs vs59, a1
	#NO_APP
	li	a1, 128
	li	a2, 63
	#APP
	vmcs vs58, a1
	#NO_APP
	#APP
	vmcs vs57, a2
	#NO_APP
	li	a1, 7
	li	a2, 4
	#APP
	vmcs vs56, a1
	#NO_APP
	#APP
	vmcs vs55, a2
	#NO_APP
	beqz	a0, .LBB16_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi54:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi56:
	auipc	a5, %pcrel_hi(net_kernel_15_wt)
.Lpcrel_hi55:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi56)
	j	.LBB16_3
.LBB16_2:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi55)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi55)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, t0
	beqz	a0, .LBB16_7
.LBB16_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi54)(a2)
	mv	a6, a0
	beqz	a7, .LBB16_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a6, a7
.LBB16_5:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB16_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a7, a6
	j	.LBB16_2
.LBB16_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end16:
	.size	net_kernel_15_ct, .Lfunc_end16-net_kernel_15_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_16_ct                # -- Begin function net_kernel_16_ct
	.p2align	2
	.type	net_kernel_16_ct,@function
net_kernel_16_ct:                       # @net_kernel_16_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB17_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi57:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi59:
	auipc	a5, %pcrel_hi(net_kernel_16_wt)
.Lpcrel_hi58:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi59)
	j	.LBB17_3
.LBB17_2:                               # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi58)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi58)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB17_7
.LBB17_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi57)(a3)
	mv	a6, a0
	beqz	a7, .LBB17_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a6, a7
.LBB17_5:                               # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB17_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a7, a6
	j	.LBB17_2
.LBB17_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end17:
	.size	net_kernel_16_ct, .Lfunc_end17-net_kernel_16_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_17_ct                # -- Begin function net_kernel_17_ct
	.p2align	2
	.type	net_kernel_17_ct,@function
net_kernel_17_ct:                       # @net_kernel_17_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB18_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi60:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi62:
	auipc	a4, %pcrel_hi(net_kernel_17_wt)
.Lpcrel_hi61:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi62)
	j	.LBB18_3
.LBB18_2:                               # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi61)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi61)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB18_7
.LBB18_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi60)(a2)
	mv	a5, a0
	beqz	a6, .LBB18_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	a5, a6
.LBB18_5:                               # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB18_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	a6, a5
	j	.LBB18_2
.LBB18_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end18:
	.size	net_kernel_17_ct, .Lfunc_end18-net_kernel_17_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_18_ct                # -- Begin function net_kernel_18_ct
	.p2align	2
	.type	net_kernel_18_ct,@function
net_kernel_18_ct:                       # @net_kernel_18_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB19_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi63:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi65:
	auipc	a5, %pcrel_hi(net_kernel_18_wt)
.Lpcrel_hi64:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi65)
	j	.LBB19_3
.LBB19_2:                               # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi64)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi64)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB19_7
.LBB19_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi63)(a3)
	mv	a6, a0
	beqz	a7, .LBB19_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a6, a7
.LBB19_5:                               # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB19_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a7, a6
	j	.LBB19_2
.LBB19_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end19:
	.size	net_kernel_18_ct, .Lfunc_end19-net_kernel_18_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_19_ct                # -- Begin function net_kernel_19_ct
	.p2align	2
	.type	net_kernel_19_ct,@function
net_kernel_19_ct:                       # @net_kernel_19_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 16
	#APP
	vmca va5, a3
	#NO_APP
	#APP
	vmca va6, a3
	#NO_APP
	#APP
	vmca va7, a3
	#NO_APP
	#APP
	vmca va8, a3
	#NO_APP
	beqz	a0, .LBB20_7
# %bb.1:                                # %stripmine.preheader
	addi	a3, a1, 4
	addi	a4, a1, 8
	addi	a5, a1, 12
.Lpcrel_hi66:
	auipc	a6, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi68:
	auipc	t0, %pcrel_hi(net_kernel_19_wt)
.Lpcrel_hi67:
	auipc	a7, %pcrel_hi(hwacha_vl_short)
	addi	t0, t0, %pcrel_lo(.Lpcrel_hi68)
	j	.LBB20_3
.LBB20_2:                               # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	#APP
	vsetvl t1, t2
	#NO_APP
	ld	t3, %pcrel_lo(.Lpcrel_hi67)(a7)
	sltu	t2, t1, t2
	sub	a0, a0, t1
	or	t2, t3, t2
	sd	t2, %pcrel_lo(.Lpcrel_hi67)(a7)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vmca va4, a5
	#NO_APP
	#APP
	vf 0(t0)
	#NO_APP
	slli	t2, t1, 4
	add	a1, a1, t2
	slli	t1, t1, 2
	add	a2, a2, t1
	add	a3, a3, t2
	add	a4, a4, t2
	add	a5, a5, t2
	beqz	a0, .LBB20_7
.LBB20_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t2, %pcrel_lo(.Lpcrel_hi66)(a6)
	mv	t1, a0
	beqz	t2, .LBB20_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	t1, t2
.LBB20_5:                               # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	t2, a0
	bltu	a0, t1, .LBB20_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	t2, t1
	j	.LBB20_2
.LBB20_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end20:
	.size	net_kernel_19_ct, .Lfunc_end20-net_kernel_19_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_20_ct                # -- Begin function net_kernel_20_ct
	.p2align	2
	.type	net_kernel_20_ct,@function
net_kernel_20_ct:                       # @net_kernel_20_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a4, -1
	slli	a4, a4, 54
	addi	a4, a4, 65
	slli	a4, a4, 9
	#APP
	vsetcfg a4
	#NO_APP
	beqz	a0, .LBB21_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi69:
	auipc	a4, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi71:
	auipc	a6, %pcrel_hi(net_kernel_20_wt)
.Lpcrel_hi70:
	auipc	a5, %pcrel_hi(hwacha_vl_short)
	addi	a6, a6, %pcrel_lo(.Lpcrel_hi71)
	j	.LBB21_3
.LBB21_2:                               # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	#APP
	vsetvl a7, t0
	#NO_APP
	ld	t1, %pcrel_lo(.Lpcrel_hi70)(a5)
	sltu	t0, a7, t0
	sub	a0, a0, a7
	slli	a7, a7, 2
	or	t0, t1, t0
	sd	t0, %pcrel_lo(.Lpcrel_hi70)(a5)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vf 0(a6)
	#NO_APP
	add	a1, a1, a7
	add	a2, a2, a7
	add	a3, a3, a7
	beqz	a0, .LBB21_7
.LBB21_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t0, %pcrel_lo(.Lpcrel_hi69)(a4)
	mv	a7, a0
	beqz	t0, .LBB21_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a7, t0
.LBB21_5:                               # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	t0, a0
	bltu	a0, a7, .LBB21_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	t0, a7
	j	.LBB21_2
.LBB21_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end21:
	.size	net_kernel_20_ct, .Lfunc_end21-net_kernel_20_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_21_ct                # -- Begin function net_kernel_21_ct
	.p2align	2
	.type	net_kernel_21_ct,@function
net_kernel_21_ct:                       # @net_kernel_21_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 16
	#APP
	vmca va5, a3
	#NO_APP
	#APP
	vmca va6, a3
	#NO_APP
	#APP
	vmca va7, a3
	#NO_APP
	#APP
	vmca va8, a3
	#NO_APP
	beqz	a0, .LBB22_7
# %bb.1:                                # %stripmine.preheader
	addi	a3, a1, 4
	addi	a4, a1, 8
	addi	a5, a1, 12
.Lpcrel_hi72:
	auipc	a6, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi74:
	auipc	t0, %pcrel_hi(net_kernel_21_wt)
.Lpcrel_hi73:
	auipc	a7, %pcrel_hi(hwacha_vl_short)
	addi	t0, t0, %pcrel_lo(.Lpcrel_hi74)
	j	.LBB22_3
.LBB22_2:                               # %stripmine
                                        #   in Loop: Header=BB22_3 Depth=1
	#APP
	vsetvl t1, t2
	#NO_APP
	ld	t3, %pcrel_lo(.Lpcrel_hi73)(a7)
	sltu	t2, t1, t2
	sub	a0, a0, t1
	or	t2, t3, t2
	sd	t2, %pcrel_lo(.Lpcrel_hi73)(a7)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vmca va4, a5
	#NO_APP
	#APP
	vf 0(t0)
	#NO_APP
	slli	t2, t1, 4
	add	a1, a1, t2
	slli	t1, t1, 2
	add	a2, a2, t1
	add	a3, a3, t2
	add	a4, a4, t2
	add	a5, a5, t2
	beqz	a0, .LBB22_7
.LBB22_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t2, %pcrel_lo(.Lpcrel_hi72)(a6)
	mv	t1, a0
	beqz	t2, .LBB22_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB22_3 Depth=1
	mv	t1, t2
.LBB22_5:                               # %stripmine
                                        #   in Loop: Header=BB22_3 Depth=1
	mv	t2, a0
	bltu	a0, t1, .LBB22_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB22_3 Depth=1
	mv	t2, t1
	j	.LBB22_2
.LBB22_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end22:
	.size	net_kernel_21_ct, .Lfunc_end22-net_kernel_21_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_22_ct                # -- Begin function net_kernel_22_ct
	.p2align	2
	.type	net_kernel_22_ct,@function
net_kernel_22_ct:                       # @net_kernel_22_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB23_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi75:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi77:
	auipc	a5, %pcrel_hi(net_kernel_22_wt)
.Lpcrel_hi76:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi77)
	j	.LBB23_3
.LBB23_2:                               # %stripmine
                                        #   in Loop: Header=BB23_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi76)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi76)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB23_7
.LBB23_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi75)(a3)
	mv	a6, a0
	beqz	a7, .LBB23_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB23_3 Depth=1
	mv	a6, a7
.LBB23_5:                               # %stripmine
                                        #   in Loop: Header=BB23_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB23_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB23_3 Depth=1
	mv	a7, a6
	j	.LBB23_2
.LBB23_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end23:
	.size	net_kernel_22_ct, .Lfunc_end23-net_kernel_22_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_23_ct                # -- Begin function net_kernel_23_ct
	.p2align	2
	.type	net_kernel_23_ct,@function
net_kernel_23_ct:                       # @net_kernel_23_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 129
	lui	a3, 24919
	slli	a2, a2, 9
	slli	a3, a3, 5
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	lui	a2, 261003
	lui	a3, 273152
	addi	a2, a2, -1477
	#APP
	vmcs vs62, a3
	#NO_APP
	#APP
	vmcs vs61, a2
	#NO_APP
	lui	a2, 308224
	li	a3, 813
	#APP
	vmcs vs60, a2
	#NO_APP
	slli	a3, a3, 22
	#APP
	vmcs vs59, a3
	#NO_APP
	lui	a2, 258839
	addi	a2, a2, 512
	lui	a3, 220156
	#APP
	vmcs vs58, a2
	#NO_APP
	addi	a2, a3, -370
	#APP
	vmcs vs57, a2
	#NO_APP
	lui	a2, 234759
	addi	a2, a2, -1689
	lui	a3, 240500
	#APP
	vmcs vs56, a2
	#NO_APP
	addi	a2, a3, 974
	#APP
	vmcs vs55, a2
	#NO_APP
	lui	a2, 245897
	addi	a2, a2, -1784
	lui	a3, 250539
	#APP
	vmcs vs54, a2
	#NO_APP
	addi	a2, a3, -1599
	#APP
	vmcs vs53, a2
	#NO_APP
	lui	a2, 254635
	addi	a2, a2, -1366
	lui	a3, 258048
	#APP
	vmcs vs52, a2
	#NO_APP
	#APP
	vmcs vs51, a3
	#NO_APP
	lui	a2, 260096
	li	a3, 23
	#APP
	vmcs vs50, a2
	#NO_APP
	#APP
	vmcs vs49, a3
	#NO_APP
	beqz	a0, .LBB24_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi78:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi80:
	auipc	a4, %pcrel_hi(net_kernel_23_wt)
.Lpcrel_hi79:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi80)
	j	.LBB24_3
.LBB24_2:                               # %stripmine
                                        #   in Loop: Header=BB24_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi79)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi79)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB24_7
.LBB24_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi78)(a2)
	mv	a5, a0
	beqz	a6, .LBB24_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB24_3 Depth=1
	mv	a5, a6
.LBB24_5:                               # %stripmine
                                        #   in Loop: Header=BB24_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB24_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB24_3 Depth=1
	mv	a6, a5
	j	.LBB24_2
.LBB24_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end24:
	.size	net_kernel_23_ct, .Lfunc_end24-net_kernel_23_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -176
	.cfi_def_cfa_offset 176
	sd	ra, 168(sp)                     # 8-byte Folded Spill
	sd	s0, 160(sp)                     # 8-byte Folded Spill
	sd	s1, 152(sp)                     # 8-byte Folded Spill
	sd	s2, 144(sp)                     # 8-byte Folded Spill
	sd	s3, 136(sp)                     # 8-byte Folded Spill
	sd	s4, 128(sp)                     # 8-byte Folded Spill
	sd	s5, 120(sp)                     # 8-byte Folded Spill
	sd	s6, 112(sp)                     # 8-byte Folded Spill
	sd	s7, 104(sp)                     # 8-byte Folded Spill
	sd	s8, 96(sp)                      # 8-byte Folded Spill
	sd	s9, 88(sp)                      # 8-byte Folded Spill
	sd	s10, 80(sp)                     # 8-byte Folded Spill
	sd	s11, 72(sp)                     # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	.cfi_offset s8, -80
	.cfi_offset s9, -88
	.cfi_offset s10, -96
	.cfi_offset s11, -104
	mv	s0, a0
	li	a0, 192
	call	malloc
	sd	a0, 64(sp)                      # 8-byte Folded Spill
.Lpcrel_hi81:
	auipc	s5, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi82:
	auipc	s7, %pcrel_hi(hwacha_grid_size)
	addi	a1, a0, 63
	li	s3, 32
	andi	s1, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s1
	call	net_kernel_ct
	li	a0, 320
	call	malloc
	sd	a0, 56(sp)                      # 8-byte Folded Spill
	li	s2, 64
	addi	a1, a0, 63
	andi	s6, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s2, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 64
	mv	a1, s6
	call	net_kernel_0_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s2, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 64
	mv	a1, s0
	mv	a2, s1
	mv	a3, s6
	call	net_kernel_1_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s2, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 64
	mv	a1, s6
	call	net_kernel_2_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s2, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 64
	mv	a1, s6
	call	net_kernel_3_ct
	li	a0, 192
	call	malloc
	sd	a0, 48(sp)                      # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a1, a0, 63
	andi	s8, a1, -64
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s8
	call	net_kernel_4_ct
	li	a0, 192
	call	malloc
	sd	a0, 40(sp)                      # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a1, a0, 63
	andi	s0, a1, -64
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s0
	call	net_kernel_5_ct
	li	a0, 192
	call	malloc
	sd	a0, 32(sp)                      # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a1, a0, 63
	andi	s2, a1, -64
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s0
	mv	a2, s2
	call	net_kernel_6_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s6
	mv	a2, s8
	mv	a3, s2
	call	net_kernel_7_ct
	li	a0, 192
	call	malloc
	sd	a0, 24(sp)                      # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a1, a0, 63
	andi	s1, a1, -64
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s2
	mv	a2, s1
	call	net_kernel_8_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s8
	call	net_kernel_9_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s6
	mv	a2, s8
	mv	a3, s0
	call	net_kernel_10_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s3, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 32
	mv	a1, s0
	mv	a2, s8
	call	net_kernel_11_ct
	li	a0, 128
	call	malloc
	sd	a0, 16(sp)                      # 8-byte Folded Spill
	addi	a1, a0, 63
	andi	s11, a1, -64
	li	a0, 128
	call	malloc
	sd	a0, 8(sp)                       # 8-byte Folded Spill
	li	s6, 16
	addi	a1, a0, 63
	andi	s0, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s6, %pcrel_lo(.Lpcrel_hi82)(s7)
.Lpcrel_hi83:
	auipc	s3, %pcrel_hi(.L__constant_2x16xi64)
	addi	s3, s3, %pcrel_lo(.Lpcrel_hi83)
	li	a0, 16
	mv	a1, s3
	mv	a2, s1
	mv	a3, s0
	call	net_kernel_12_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s6, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 16
	mv	a1, s3
	mv	a2, s1
	mv	a3, s11
	call	net_kernel_13_ct
	li	a0, 128
	call	malloc
	sd	a0, 0(sp)                       # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a1, a0, 63
	andi	s1, a1, -64
	sd	s6, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 16
	mv	a1, s3
	mv	a2, s8
	mv	a3, s1
	call	net_kernel_14_ct
	li	a0, 128
	call	malloc
	mv	s10, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a0, a0, 63
	andi	s2, a0, -64
	sd	s6, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 16
	mv	a1, s3
	mv	a2, s8
	mv	a3, s2
	call	net_kernel_15_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s6, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 16
	mv	a1, s0
	mv	a2, s11
	call	net_kernel_16_ct
	li	a0, 80
	call	malloc
	mv	s8, a0
	li	s9, 4
	addi	a0, a0, 63
	andi	s3, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s9, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 4
	mv	a1, s3
	call	net_kernel_17_ct
	li	a0, 80
	call	malloc
	mv	s0, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	addi	a0, a0, 63
	andi	s4, a0, -64
	sd	s9, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 4
	mv	a1, s3
	mv	a2, s4
	call	net_kernel_18_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s9, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 4
	mv	a1, s11
	mv	a2, s4
	call	net_kernel_19_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s6, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 16
	mv	a1, s1
	mv	a2, s2
	mv	a3, s11
	call	net_kernel_20_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s9, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 4
	mv	a1, s11
	mv	a2, s3
	call	net_kernel_21_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s9, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 4
	mv	a1, s4
	mv	a2, s3
	call	net_kernel_22_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi81)(s5)
	sd	s9, %pcrel_lo(.Lpcrel_hi82)(s7)
	li	a0, 4
	mv	a1, s3
	call	net_kernel_23_ct
	ld	a0, 64(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 56(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 48(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 40(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 32(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 24(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 16(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 8(sp)                       # 8-byte Folded Reload
	call	free
	ld	a0, 0(sp)                       # 8-byte Folded Reload
	call	free
	mv	a0, s10
	call	free
	mv	a0, s0
	call	free
	mv	a0, s8
	ld	ra, 168(sp)                     # 8-byte Folded Reload
	ld	s0, 160(sp)                     # 8-byte Folded Reload
	ld	s1, 152(sp)                     # 8-byte Folded Reload
	ld	s2, 144(sp)                     # 8-byte Folded Reload
	ld	s3, 136(sp)                     # 8-byte Folded Reload
	ld	s4, 128(sp)                     # 8-byte Folded Reload
	ld	s5, 120(sp)                     # 8-byte Folded Reload
	ld	s6, 112(sp)                     # 8-byte Folded Reload
	ld	s7, 104(sp)                     # 8-byte Folded Reload
	ld	s8, 96(sp)                      # 8-byte Folded Reload
	ld	s9, 88(sp)                      # 8-byte Folded Reload
	ld	s10, 80(sp)                     # 8-byte Folded Reload
	ld	s11, 72(sp)                     # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	.cfi_restore s8
	.cfi_restore s9
	.cfi_restore s10
	.cfi_restore s11
	addi	sp, sp, 176
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end25:
	.size	net, .Lfunc_end25-net
	.cfi_endproc
                                        # -- End function
	.type	__constant_8x4xf32,@object      # @__constant_8x4xf32
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
__constant_8x4xf32:
	.word	0xbdd54c58                      # float -0.10414952
	.word	0x3d0c4b50                      # float 0.0342515111
	.word	0xbe855be8                      # float -0.260466814
	.word	0xbed8d4a6                      # float -0.423497379
	.word	0xbeaa03f2                      # float -0.33206135
	.word	0xbd60e060                      # float -0.0549014807
	.word	0xbeb954a2                      # float -0.361973822
	.word	0x3efc50dc                      # float 0.492804408
	.word	0x3bb15380                      # float 0.0054115653
	.word	0xbe440288                      # float -0.191415906
	.word	0x3e4a5a4c                      # float 0.19761008
	.word	0xbee2f62c                      # float -0.443284392
	.word	0xbe82f126                      # float -0.255746067
	.word	0x3e404ec8                      # float 0.187800527
	.word	0xbed9837e                      # float -0.424831331
	.word	0x3e7f2eac                      # float 0.249201477
	.word	0x3d2c2520                      # float 0.0420275927
	.word	0xbed57464                      # float -0.416903615
	.word	0xbefe100a                      # float -0.496216118
	.word	0x3e21d164                      # float 0.158025324
	.word	0x3e720194                      # float 0.236334145
	.word	0xbdccb440                      # float -0.0999531745
	.word	0xbee25e90                      # float -0.442127705
	.word	0xbe938b70                      # float -0.288173199
	.word	0x3d59ab20                      # float 0.0531417131
	.word	0x3c950440                      # float 0.0181905031
	.word	0x3e030f68                      # float 0.127988458
	.word	0x3db51058                      # float 0.0884100794
	.word	0xbcd6b280                      # float -0.0262081623
	.word	0x3e871916                      # float 0.263863266
	.word	0x3ef852d0                      # float 0.485006809
	.word	0x3ed53348                      # float 0.41640687
	.size	__constant_8x4xf32, 128

	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	__constant_8xf32,@object        # @__constant_8xf32
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
__constant_8xf32:
	.word	0x3ee89efc                      # float 0.454337955
	.word	0xbe2ccd3c                      # float -0.168751657
	.word	0xbe2ec0d0                      # float -0.170657396
	.word	0xbd6282f0                      # float -0.055300653
	.word	0x3e17537c                      # float 0.147779405
	.word	0x3e4f3f28                      # float 0.202389359
	.word	0xbd368d00                      # float -0.0445680618
	.word	0xbea55b6c                      # float -0.322963119
	.size	__constant_8xf32, 32

	.type	__constant_4x8xf32_1,@object    # @__constant_4x8xf32_1
	.p2align	6, 0x0
__constant_4x8xf32_1:
	.word	0xbe88943f                      # float -0.266756028
	.word	0x3eae454b                      # float 0.340372413
	.word	0xbdc2ac22                      # float -0.0950548798
	.word	0xbd43becd                      # float -0.0477893837
	.word	0xbe5de10c                      # float -0.216678798
	.word	0xbe337bf7                      # float -0.175277576
	.word	0x3d9f093e                      # float 0.0776543468
	.word	0x3e187c5c                      # float 0.148911893
	.word	0xbe0f1f55                      # float -0.13976796
	.word	0xbe0541a3                      # float -0.130133197
	.word	0x3e8f6569                      # float 0.280070573
	.word	0xbe3a74b9                      # float -0.182085887
	.word	0xbe870e47                      # float -0.263780802
	.word	0xbd61ef4d                      # float -0.0551598556
	.word	0x3eac3f76                      # float 0.336421669
	.word	0x3d9d8d1b                      # float 0.0769292936
	.word	0x3d4818a0                      # float 0.0488516092
	.word	0xbd345032                      # float -0.0440217927
	.word	0x3e623be1                      # float 0.220931545
	.word	0xbe3371dd                      # float -0.175239041
	.word	0x3e757757                      # float 0.239713058
	.word	0x3dab0f1a                      # float 0.0835248977
	.word	0x3d2102ab                      # float 0.039309185
	.word	0x3d475cb6                      # float 0.0486724004
	.word	0xbe5f4743                      # float -0.218045279
	.word	0x3e8671bd                      # float 0.262586504
	.word	0x3e3e2543                      # float 0.185689017
	.word	0xbe8d9411                      # float -0.276520282
	.word	0xbea88b35                      # float -0.329187065
	.word	0xbdba660a                      # float -0.0910149366
	.word	0x3e70856c                      # float 0.234883964
	.word	0xbe323e3b                      # float -0.174065515
	.size	__constant_4x8xf32_1, 128

	.type	__constant_4xf32_0,@object      # @__constant_4xf32_0
	.p2align	6, 0x0
__constant_4xf32_0:
	.word	0x3ea7c681                      # float 0.32768634
	.word	0xbe360637                      # float -0.177758083
	.word	0xbea383e4                      # float -0.319365621
	.word	0x3e1f419c                      # float 0.155523717
	.size	__constant_4xf32_0, 16

	.type	__constant_4x8xf32,@object      # @__constant_4x8xf32
	.p2align	6, 0x0
__constant_4x8xf32:
	.word	0xbe5acbc0                      # float -0.21366787
	.word	0xbd6448df                      # float -0.0557335578
	.word	0xbde1d7b3                      # float -0.110274695
	.word	0xbce6236e                      # float -0.0280930661
	.word	0xbe9dbc41                      # float -0.308076888
	.word	0xbea607fa                      # float -0.324279606
	.word	0x3e1ba1cc                      # float 0.151984394
	.word	0xbd24192b                      # float -0.0400630645
	.word	0xbe5a648c                      # float -0.213274181
	.word	0xbc1390a6                      # float -0.00900665484
	.word	0xbea538e4                      # float -0.322699666
	.word	0x3dc03368                      # float 0.0938480496
	.word	0x3e2beee9                      # float 0.167903557
	.word	0x3eaf8e38                      # float 0.342881918
	.word	0xbe9378b9                      # float -0.288030416
	.word	0xbd2f9963                      # float -0.0428708903
	.word	0x3e4479ff                      # float 0.191871628
	.word	0x3ea5e5a9                      # float 0.324017793
	.word	0xbe80ca4a                      # float -0.251543343
	.word	0x3e19da50                      # float 0.150246859
	.word	0x3e157907                      # float 0.145969495
	.word	0x3e5a4336                      # float 0.213147014
	.word	0xbe799866                      # float -0.243745416
	.word	0x3e812daa                      # float 0.252301514
	.word	0xbe1db0de                      # float -0.153995007
	.word	0xbe5eda3a                      # float -0.217629343
	.word	0x3d8fc54e                      # float 0.0702005476
	.word	0x3e995948                      # float 0.299509287
	.word	0xbe6fbff3                      # float -0.234130666
	.word	0x3e414b9c                      # float 0.188764989
	.word	0xbd25d9d4                      # float -0.0404909402
	.word	0x3de7270c                      # float 0.112867445
	.size	__constant_4x8xf32, 128

	.type	__constant_4xf32,@object        # @__constant_4xf32
	.p2align	6, 0x0
__constant_4xf32:
	.word	0x3e8d3534                      # float 0.275796533
	.word	0x3dc49a07                      # float 0.0959969088
	.word	0xbe96463d                      # float -0.293504626
	.word	0xbdda0094                      # float -0.106446415
	.size	__constant_4xf32, 16

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.bss
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.type	.L__constant_2x16xi64,@object   # @__constant_2x16xi64
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
.L__constant_2x16xi64:
	.quad	0                               # 0x0
	.quad	0                               # 0x0
	.quad	1                               # 0x1
	.quad	1                               # 0x1
	.quad	2                               # 0x2
	.quad	3                               # 0x3
	.quad	4                               # 0x4
	.quad	4                               # 0x4
	.quad	1                               # 0x1
	.quad	2                               # 0x2
	.quad	2                               # 0x2
	.quad	3                               # 0x3
	.quad	3                               # 0x3
	.quad	4                               # 0x4
	.quad	5                               # 0x5
	.quad	6                               # 0x6
	.quad	1                               # 0x1
	.quad	2                               # 0x2
	.quad	2                               # 0x2
	.quad	3                               # 0x3
	.quad	3                               # 0x3
	.quad	4                               # 0x4
	.quad	5                               # 0x5
	.quad	6                               # 0x6
	.quad	0                               # 0x0
	.quad	0                               # 0x0
	.quad	1                               # 0x1
	.quad	1                               # 0x1
	.quad	2                               # 0x2
	.quad	3                               # 0x3
	.quad	4                               # 0x4
	.quad	4                               # 0x4
	.size	.L__constant_2x16xi64, 256

	.section	".note.GNU-stack","",@progbits
