# generated by hwacha-cc from voxel_grid.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    vadd vv0, vs0, vs0
    vsd vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    vaddw vv0, vs63, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    vld vv0, va0
    vsd vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    vlw vv2, va0
    vlw vv3, va1
    vld vv0, va2
    vfmin.s vv4, vv2, vv3
    vcmpflt.s vp1, vv2, vv3
    @vp1 vadd vv1, vs63, vs0
    @!vp1 vadd vv1, vv0, vs0
    vsw vv4, va1
    vsd vv1, va2
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    vaddw vv0, vs63, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_4_wt
net_kernel_4_wt:
    vpset vp0
    vlw vv2, va0
    vlw vv3, va1
    vld vv0, va2
    vfmax.s vv4, vv2, vv3
    vcmpflt.s vp1, vv3, vv2
    @vp1 vadd vv1, vs63, vs0
    @!vp1 vadd vv1, vv0, vs0
    vsw vv4, va1
    vsd vv1, va2
    vstop

    .text
    .align 3
    .globl net_kernel_5_wt
net_kernel_5_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfsub.s vv1, vv0, vv1
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_6_wt
net_kernel_6_wt:
    vpset vp0
    vlw vv0, va0
    vfcvt.w.s vv1, vv0, rtz
    vfcvt.s.w vv1, vv1
    vfadd.s vv2, vv1, vs63
    vcmpflt.s vp1, vv0, vv1
    @!vp1 vaddw vv2, vv1, vs0
    vsw vv2, va0
    vstop

    .text
    .align 3
    .globl net_kernel_7_wt
net_kernel_7_wt:
    vpset vp0
    vlw vv1, va0
    vfcvt.l.s vv0, vv1, rtz
    vsd vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_8_wt
net_kernel_8_wt:
    vpset vp0
    vld vv0, va0
    vadd vv1, vv0, vs63
    vsd vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_9_wt
net_kernel_9_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsll vv1, vv0, vs59
    vlxw vv3, vs60, vv1
    vdivu vv2, vv0, vs58
    vmul vv2, vv2, vs57
    vsub vv2, vv1, vv2
    vlxw vv4, vs62, vv2
    vfsub.s vv4, vv3, vv4
    vsxw vv4, vs61, vv1
    vstop

    .text
    .align 3
    .globl net_kernel_10_wt
net_kernel_10_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsll vv1, vv0, vs61
    vlxw vv2, vs62, vv1
    vfcvt.w.s vv3, vv2, rtz
    vfcvt.s.w vv3, vv3
    vfadd.s vv4, vv3, vs60
    vcmpflt.s vp1, vv2, vv3
    @!vp1 vaddw vv4, vv3, vs0
    vsxw vv4, vs62, vv1
    vstop

    .text
    .align 3
    .globl net_kernel_11_wt
net_kernel_11_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsll vv1, vv0, vs60
    vlxw vv3, vs61, vv1
    vfcvt.l.s vv1, vv3, rtz
    vsll vv2, vv0, vs59
    vsxd vv1, vs62, vv2
    vstop

    .text
    .align 3
    .globl net_kernel_12_wt
net_kernel_12_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsll vv1, vv0, vs60
    vlxd vv2, vs61, vv1
    vdivu vv3, vv0, vs60
    vmul vv3, vv3, vs59
    vsub vv3, vv1, vv3
    vlxd vv4, vs62, vv3
    vmul vv4, vv4, vv2
    vsxd vv4, vs61, vv1
    vstop

    .text
    .align 3
    .globl net_kernel_13_wt
net_kernel_13_wt:
    vpset vp0
    vadd vv0, vs0, vs0
    vsd vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_14_wt
net_kernel_14_wt:
    vpset vp0
    vlstd vv0, va0, va4
    vld vv1, va1
    vadd vv1, vv1, vv0
    vlstd vv0, va2, va5
    vadd vv1, vv0, vv1
    vlstd vv0, va3, va6
    vadd vv1, vv0, vv1
    vsd vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_15_wt
net_kernel_15_wt:
    vpset vp0
    vld vv0, va0
    vfcvt.s.l vv1, vv0
    vsw vv1, va1
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 513
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a4, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi1)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 3
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi1)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi0)(a2)
	mv	a5, a0
	beqz	a6, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a5, a6
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a5
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	lui	a3, 522240
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi3:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a4, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi4:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi4)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi4)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi3)(a2)
	mv	a5, a0
	beqz	a6, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a5, a6
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a5
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 63
	addi	a3, a3, 513
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi6:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi8:
	auipc	a5, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi7:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi8)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi7)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 3
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi7)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi6)(a3)
	mv	a6, a0
	beqz	a7, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a7
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a6
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a5, 1048551
	addi	a5, a5, 2043
	srli	a5, a5, 1
	not	a5, a5
	#APP
	vsetcfg a5
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
	slli	a5, a2, 2
	slli	a6, a2, 3
.Lpcrel_hi9:
	auipc	a2, %pcrel_hi(hwacha_group_size)
	add	a5, a6, a5
.Lpcrel_hi11:
	auipc	a6, %pcrel_hi(net_kernel_2_wt)
	add	a1, a1, a5
.Lpcrel_hi10:
	auipc	a5, %pcrel_hi(hwacha_vl_short)
	addi	a6, a6, %pcrel_lo(.Lpcrel_hi11)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a7, t0
	#NO_APP
	ld	t1, %pcrel_lo(.Lpcrel_hi10)(a5)
	sltu	t0, a7, t0
	sub	a0, a0, a7
	or	t0, t1, t0
	slli	t1, a7, 2
	sd	t0, %pcrel_lo(.Lpcrel_hi10)(a5)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a3
	#NO_APP
	#APP
	vmca va2, a4
	#NO_APP
	#APP
	vf 0(a6)
	#NO_APP
	add	a1, a1, t1
	slli	a7, a7, 3
	add	a3, a3, t1
	add	a4, a4, a7
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t0, %pcrel_lo(.Lpcrel_hi9)(a2)
	mv	a7, a0
	beqz	t0, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, t0
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	t0, a0
	bltu	a0, a7, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	t0, a7
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	li	a3, 511
	slli	a2, a2, 9
	slli	a3, a3, 23
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi12:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi14:
	auipc	a4, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi13:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi14)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi13)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi13)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi12)(a2)
	mv	a5, a0
	beqz	a6, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a5, a6
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a5
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_4_ct                 # -- Begin function net_kernel_4_ct
	.p2align	2
	.type	net_kernel_4_ct,@function
net_kernel_4_ct:                        # @net_kernel_4_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a5, 1048551
	addi	a5, a5, 2043
	srli	a5, a5, 1
	not	a5, a5
	#APP
	vsetcfg a5
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	beqz	a0, .LBB5_7
# %bb.1:                                # %stripmine.preheader
	slli	a5, a2, 2
	slli	a6, a2, 3
.Lpcrel_hi15:
	auipc	a2, %pcrel_hi(hwacha_group_size)
	add	a5, a6, a5
.Lpcrel_hi17:
	auipc	a6, %pcrel_hi(net_kernel_4_wt)
	add	a1, a1, a5
.Lpcrel_hi16:
	auipc	a5, %pcrel_hi(hwacha_vl_short)
	addi	a6, a6, %pcrel_lo(.Lpcrel_hi17)
	j	.LBB5_3
.LBB5_2:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	#APP
	vsetvl a7, t0
	#NO_APP
	ld	t1, %pcrel_lo(.Lpcrel_hi16)(a5)
	sltu	t0, a7, t0
	sub	a0, a0, a7
	or	t0, t1, t0
	slli	t1, a7, 2
	sd	t0, %pcrel_lo(.Lpcrel_hi16)(a5)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a3
	#NO_APP
	#APP
	vmca va2, a4
	#NO_APP
	#APP
	vf 0(a6)
	#NO_APP
	add	a1, a1, t1
	slli	a7, a7, 3
	add	a3, a3, t1
	add	a4, a4, a7
	beqz	a0, .LBB5_7
.LBB5_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t0, %pcrel_lo(.Lpcrel_hi15)(a2)
	mv	a7, a0
	beqz	t0, .LBB5_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, t0
.LBB5_5:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	t0, a0
	bltu	a0, a7, .LBB5_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	t0, a7
	j	.LBB5_2
.LBB5_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end5:
	.size	net_kernel_4_ct, .Lfunc_end5-net_kernel_4_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_5_ct                 # -- Begin function net_kernel_5_ct
	.p2align	2
	.type	net_kernel_5_ct,@function
net_kernel_5_ct:                        # @net_kernel_5_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB6_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi18:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi20:
	auipc	a5, %pcrel_hi(net_kernel_5_wt)
.Lpcrel_hi19:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi20)
	j	.LBB6_3
.LBB6_2:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi19)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi19)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB6_7
.LBB6_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi18)(a3)
	mv	a6, a0
	beqz	a7, .LBB6_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a7
.LBB6_5:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB6_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a7, a6
	j	.LBB6_2
.LBB6_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end6:
	.size	net_kernel_5_ct, .Lfunc_end6-net_kernel_5_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_6_ct                 # -- Begin function net_kernel_6_ct
	.p2align	2
	.type	net_kernel_6_ct,@function
net_kernel_6_ct:                        # @net_kernel_6_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 49
	li	a3, 383
	slli	a2, a2, 10
	slli	a3, a3, 23
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB7_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi21:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi23:
	auipc	a4, %pcrel_hi(net_kernel_6_wt)
.Lpcrel_hi22:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi23)
	j	.LBB7_3
.LBB7_2:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi22)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi22)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB7_7
.LBB7_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi21)(a2)
	mv	a5, a0
	beqz	a6, .LBB7_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a5, a6
.LBB7_5:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB7_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a5
	j	.LBB7_2
.LBB7_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end7:
	.size	net_kernel_6_ct, .Lfunc_end7-net_kernel_6_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_7_ct                 # -- Begin function net_kernel_7_ct
	.p2align	2
	.type	net_kernel_7_ct,@function
net_kernel_7_ct:                        # @net_kernel_7_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048568
	addi	a3, a3, -1027
	srli	a3, a3, 1
	not	a3, a3
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB8_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi24:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi26:
	auipc	a5, %pcrel_hi(net_kernel_7_wt)
.Lpcrel_hi25:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi26)
	j	.LBB8_3
.LBB8_2:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi25)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	slli	a6, a6, 3
	sd	a7, %pcrel_lo(.Lpcrel_hi25)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, t0
	add	a2, a2, a6
	beqz	a0, .LBB8_7
.LBB8_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi24)(a3)
	mv	a6, a0
	beqz	a7, .LBB8_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a6, a7
.LBB8_5:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB8_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a7, a6
	j	.LBB8_2
.LBB8_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end8:
	.size	net_kernel_7_ct, .Lfunc_end8-net_kernel_7_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_8_ct                 # -- Begin function net_kernel_8_ct
	.p2align	2
	.type	net_kernel_8_ct,@function
net_kernel_8_ct:                        # @net_kernel_8_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 514
	li	a3, 1
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB9_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi27:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi29:
	auipc	a4, %pcrel_hi(net_kernel_8_wt)
.Lpcrel_hi28:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi29)
	j	.LBB9_3
.LBB9_2:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi28)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 3
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi28)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB9_7
.LBB9_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi27)(a2)
	mv	a5, a0
	beqz	a6, .LBB9_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a5, a6
.LBB9_5:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB9_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a6, a5
	j	.LBB9_2
.LBB9_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end9:
	.size	net_kernel_8_ct, .Lfunc_end9-net_kernel_8_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_9_ct                 # -- Begin function net_kernel_9_ct
	.p2align	2
	.type	net_kernel_9_ct,@function
net_kernel_9_ct:                        # @net_kernel_9_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048560
	addi	a4, a4, -1031
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	#APP
	vmcs vs61, a3
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs60, a1
	#NO_APP
	#APP
	vmcs vs59, a2
	#NO_APP
	li	a1, 3
	li	a2, 12
	#APP
	vmcs vs58, a1
	#NO_APP
	#APP
	vmcs vs57, a2
	#NO_APP
	beqz	a0, .LBB10_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi30:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi32:
	auipc	a4, %pcrel_hi(net_kernel_9_wt)
.Lpcrel_hi31:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi32)
	j	.LBB10_3
.LBB10_2:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi31)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi31)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB10_7
.LBB10_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi30)(a2)
	mv	a5, a0
	beqz	a6, .LBB10_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a5, a6
.LBB10_5:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB10_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a6, a5
	j	.LBB10_2
.LBB10_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end10:
	.size	net_kernel_9_ct, .Lfunc_end10-net_kernel_9_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_10_ct                # -- Begin function net_kernel_10_ct
	.p2align	2
	.type	net_kernel_10_ct,@function
net_kernel_10_ct:                       # @net_kernel_10_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a2, 1048551
	addi	a2, a2, 2043
	srli	a2, a2, 1
	not	a2, a2
	#APP
	vsetcfg a2
	#NO_APP
	li	a2, 383
	#APP
	vmcs vs62, a1
	#NO_APP
	li	a1, 2
	slli	a2, a2, 23
	#APP
	vmcs vs61, a1
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	beqz	a0, .LBB11_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi33:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi35:
	auipc	a4, %pcrel_hi(net_kernel_10_wt)
.Lpcrel_hi34:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi35)
	j	.LBB11_3
.LBB11_2:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi34)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi34)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB11_7
.LBB11_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi33)(a2)
	mv	a5, a0
	beqz	a6, .LBB11_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a5, a6
.LBB11_5:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB11_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a6, a5
	j	.LBB11_2
.LBB11_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end11:
	.size	net_kernel_10_ct, .Lfunc_end11-net_kernel_10_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_11_ct                # -- Begin function net_kernel_11_ct
	.p2align	2
	.type	net_kernel_11_ct,@function
net_kernel_11_ct:                       # @net_kernel_11_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048568
	addi	a3, a3, -1031
	srli	a3, a3, 1
	not	a3, a3
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	#APP
	vmcs vs61, a1
	#NO_APP
	li	a1, 2
	li	a2, 3
	#APP
	vmcs vs60, a1
	#NO_APP
	#APP
	vmcs vs59, a2
	#NO_APP
	beqz	a0, .LBB12_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi36:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi38:
	auipc	a4, %pcrel_hi(net_kernel_11_wt)
.Lpcrel_hi37:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi38)
	j	.LBB12_3
.LBB12_2:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi37)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi37)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB12_7
.LBB12_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi36)(a2)
	mv	a5, a0
	beqz	a6, .LBB12_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a5, a6
.LBB12_5:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB12_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a6, a5
	j	.LBB12_2
.LBB12_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end12:
	.size	net_kernel_11_ct, .Lfunc_end12-net_kernel_11_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_12_ct                # -- Begin function net_kernel_12_ct
	.p2align	2
	.type	net_kernel_12_ct,@function
net_kernel_12_ct:                       # @net_kernel_12_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 63
	addi	a3, a3, 517
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	#APP
	vmcs vs61, a1
	#NO_APP
	li	a1, 3
	li	a2, 24
	#APP
	vmcs vs60, a1
	#NO_APP
	#APP
	vmcs vs59, a2
	#NO_APP
	beqz	a0, .LBB13_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi39:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi41:
	auipc	a4, %pcrel_hi(net_kernel_12_wt)
.Lpcrel_hi40:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi41)
	j	.LBB13_3
.LBB13_2:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi40)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi40)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB13_7
.LBB13_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi39)(a2)
	mv	a5, a0
	beqz	a6, .LBB13_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a5, a6
.LBB13_5:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB13_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a6, a5
	j	.LBB13_2
.LBB13_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end13:
	.size	net_kernel_12_ct, .Lfunc_end13-net_kernel_12_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_13_ct                # -- Begin function net_kernel_13_ct
	.p2align	2
	.type	net_kernel_13_ct,@function
net_kernel_13_ct:                       # @net_kernel_13_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 513
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB14_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi42:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi44:
	auipc	a4, %pcrel_hi(net_kernel_13_wt)
.Lpcrel_hi43:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi44)
	j	.LBB14_3
.LBB14_2:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi43)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 3
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi43)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB14_7
.LBB14_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi42)(a2)
	mv	a5, a0
	beqz	a6, .LBB14_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a5, a6
.LBB14_5:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB14_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a6, a5
	j	.LBB14_2
.LBB14_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end14:
	.size	net_kernel_13_ct, .Lfunc_end14-net_kernel_13_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_14_ct                # -- Begin function net_kernel_14_ct
	.p2align	2
	.type	net_kernel_14_ct,@function
net_kernel_14_ct:                       # @net_kernel_14_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 63
	addi	a3, a3, 514
	li	a4, 24
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmca va4, a4
	#NO_APP
	#APP
	vmca va5, a4
	#NO_APP
	#APP
	vmca va6, a4
	#NO_APP
	beqz	a0, .LBB15_7
# %bb.1:                                # %stripmine.preheader
	addi	a3, a1, 8
	addi	a4, a1, 16
.Lpcrel_hi45:
	auipc	a5, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi47:
	auipc	a7, %pcrel_hi(net_kernel_14_wt)
.Lpcrel_hi46:
	auipc	a6, %pcrel_hi(hwacha_vl_short)
	addi	a7, a7, %pcrel_lo(.Lpcrel_hi47)
	j	.LBB15_3
.LBB15_2:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	#APP
	vsetvl t0, t1
	#NO_APP
	ld	t2, %pcrel_lo(.Lpcrel_hi46)(a6)
	sltu	t1, t0, t1
	or	t1, t2, t1
	slli	t2, t0, 4
	sd	t1, %pcrel_lo(.Lpcrel_hi46)(a6)
	slli	t1, t0, 3
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vf 0(a7)
	#NO_APP
	sub	a0, a0, t0
	add	t2, t2, t1
	add	a1, a1, t2
	add	a2, a2, t1
	add	a3, a3, t2
	add	a4, a4, t2
	beqz	a0, .LBB15_7
.LBB15_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t1, %pcrel_lo(.Lpcrel_hi45)(a5)
	mv	t0, a0
	beqz	t1, .LBB15_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	t0, t1
.LBB15_5:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	t1, a0
	bltu	a0, t0, .LBB15_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	t1, t0
	j	.LBB15_2
.LBB15_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end15:
	.size	net_kernel_14_ct, .Lfunc_end15-net_kernel_14_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_15_ct                # -- Begin function net_kernel_15_ct
	.p2align	2
	.type	net_kernel_15_ct,@function
net_kernel_15_ct:                       # @net_kernel_15_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048568
	addi	a3, a3, -1027
	srli	a3, a3, 1
	not	a3, a3
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB16_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi48:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi50:
	auipc	a5, %pcrel_hi(net_kernel_15_wt)
.Lpcrel_hi49:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi50)
	j	.LBB16_3
.LBB16_2:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi49)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 3
	slli	a6, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi49)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, t0
	add	a2, a2, a6
	beqz	a0, .LBB16_7
.LBB16_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi48)(a3)
	mv	a6, a0
	beqz	a7, .LBB16_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a6, a7
.LBB16_5:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB16_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a7, a6
	j	.LBB16_2
.LBB16_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end16:
	.size	net_kernel_15_ct, .Lfunc_end16-net_kernel_15_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -128
	.cfi_def_cfa_offset 128
	sd	ra, 120(sp)                     # 8-byte Folded Spill
	sd	s0, 112(sp)                     # 8-byte Folded Spill
	sd	s1, 104(sp)                     # 8-byte Folded Spill
	sd	s2, 96(sp)                      # 8-byte Folded Spill
	sd	s3, 88(sp)                      # 8-byte Folded Spill
	sd	s4, 80(sp)                      # 8-byte Folded Spill
	sd	s5, 72(sp)                      # 8-byte Folded Spill
	sd	s6, 64(sp)                      # 8-byte Folded Spill
	sd	s7, 56(sp)                      # 8-byte Folded Spill
	sd	s8, 48(sp)                      # 8-byte Folded Spill
	sd	s9, 40(sp)                      # 8-byte Folded Spill
	sd	s10, 32(sp)                     # 8-byte Folded Spill
	sd	s11, 24(sp)                     # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	.cfi_offset s8, -80
	.cfi_offset s9, -88
	.cfi_offset s10, -96
	.cfi_offset s11, -104
	mv	s5, a0
	li	a0, 88
	call	malloc
.Lpcrel_hi51:
	auipc	s0, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi52:
	auipc	s11, %pcrel_hi(hwacha_grid_size)
	sd	a0, 16(sp)                      # 8-byte Folded Spill
	addi	a0, a0, 63
	li	s9, 3
	andi	s4, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s9, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s4
	call	net_kernel_ct
	li	a0, 76
	call	malloc
	mv	s1, a0
	li	a0, 76
	call	malloc
	mv	s2, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	addi	a0, a0, 63
	andi	s7, a0, -64
	sd	s9, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s7
	call	net_kernel_0_ct
	li	a0, 88
	call	malloc
	mv	s3, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	addi	a0, a0, 63
	andi	s6, a0, -64
	sd	s9, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s4
	mv	a2, s6
	call	net_kernel_1_ct
	li	s8, 0
	li	s10, 8
.LBB17_1:                               # =>This Inner Loop Header: Depth=1
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s9, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s5
	mv	a2, s8
	mv	a3, s7
	mv	a4, s6
	call	net_kernel_2_ct
	addi	s8, s8, 1
	bne	s8, s10, .LBB17_1
# %bb.2:
	sd	s1, 8(sp)                       # 8-byte Folded Spill
	addi	a0, s1, 63
	li	s9, 3
	andi	s6, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s9, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s6
	call	net_kernel_3_ct
	li	s8, 0
	li	s10, 8
.LBB17_3:                               # =>This Inner Loop Header: Depth=1
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s9, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s5
	mv	a2, s8
	mv	a3, s6
	mv	a4, s4
	call	net_kernel_4_ct
	addi	s8, s8, 1
	bne	s8, s10, .LBB17_3
# %bb.4:
	li	s8, 3
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s8, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s6
	mv	a2, s7
	call	net_kernel_5_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s8, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s6
	call	net_kernel_6_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s8, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s6
	mv	a2, s4
	call	net_kernel_7_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s8, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 3
	mv	a1, s4
	call	net_kernel_8_ct
	li	a0, 160
	call	malloc
	mv	s6, a0
	li	s10, 24
	addi	a0, a0, 63
	andi	s8, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s10, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 24
	mv	a1, s5
	mv	a2, s7
	mv	a3, s8
	call	net_kernel_9_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s10, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 24
	mv	a1, s8
	call	net_kernel_10_ct
	li	a0, 256
	call	malloc
	mv	s5, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	addi	a0, a0, 63
	andi	s9, a0, -64
	sd	s10, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 24
	mv	a1, s8
	mv	a2, s9
	call	net_kernel_11_ct
	li	a0, 72
	call	malloc
	ld	a1, 0(s4)
	ld	a2, 8(s4)
	mul	a1, a2, a1
	mv	s7, a0
	addi	a0, a0, 63
	andi	s1, a0, -64
	sd	a1, 0(s1)
	li	a0, 88
	call	malloc
	mv	s8, a0
	li	a0, 1
	addi	a1, s8, 63
	andi	a2, a1, -64
	sd	a0, 0(a2)
	ld	a0, 0(s4)
	sd	a0, 8(a2)
	ld	a0, 0(s1)
	sd	a0, 16(a2)
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s10, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 24
	mv	a1, s9
	call	net_kernel_12_ct
	li	a0, 128
	call	malloc
	mv	s4, a0
	li	s1, 8
	addi	a0, a0, 63
	andi	s10, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s1, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 8
	mv	a1, s10
	call	net_kernel_13_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	sd	s1, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 8
	mv	a1, s9
	mv	a2, s10
	call	net_kernel_14_ct
	li	a0, 96
	call	malloc
	mv	s9, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi51)(s0)
	addi	a0, a0, 63
	andi	a2, a0, -64
	sd	s1, %pcrel_lo(.Lpcrel_hi52)(s11)
	li	a0, 8
	mv	a1, s10
	call	net_kernel_15_ct
	ld	a0, 16(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 8(sp)                       # 8-byte Folded Reload
	call	free
	mv	a0, s2
	call	free
	mv	a0, s3
	call	free
	mv	a0, s6
	call	free
	mv	a0, s5
	call	free
	mv	a0, s7
	call	free
	mv	a0, s8
	call	free
	mv	a0, s4
	call	free
	mv	a0, s9
	ld	ra, 120(sp)                     # 8-byte Folded Reload
	ld	s0, 112(sp)                     # 8-byte Folded Reload
	ld	s1, 104(sp)                     # 8-byte Folded Reload
	ld	s2, 96(sp)                      # 8-byte Folded Reload
	ld	s3, 88(sp)                      # 8-byte Folded Reload
	ld	s4, 80(sp)                      # 8-byte Folded Reload
	ld	s5, 72(sp)                      # 8-byte Folded Reload
	ld	s6, 64(sp)                      # 8-byte Folded Reload
	ld	s7, 56(sp)                      # 8-byte Folded Reload
	ld	s8, 48(sp)                      # 8-byte Folded Reload
	ld	s9, 40(sp)                      # 8-byte Folded Reload
	ld	s10, 32(sp)                     # 8-byte Folded Reload
	ld	s11, 24(sp)                     # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	.cfi_restore s8
	.cfi_restore s9
	.cfi_restore s10
	.cfi_restore s11
	addi	sp, sp, 128
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end17:
	.size	net, .Lfunc_end17-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.section	".note.GNU-stack","",@progbits
