# generated by hwacha-cc from replicationpad3d.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vadd vv1, vv0, vs62
    vsd vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    vld vv0, va0
    vcmplt vp1, vv0, vs0
    @vp1 vadd vv1, vs0, vs0
    @!vp1 vadd vv1, vv0, vs0
    vcmpltu vp1, vv1, vs63
    @vp1 vadd vv1, vv1, vs0
    @!vp1 vadd vv1, vs63, vs0
    vsd vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsd vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsd vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs57
    vsrl vv2, vv0, vs56
    vand vv2, vv2, vs57
    vsrl vv3, vv0, vs55
    vremuw vv10, vv3, vs54
    vsll vv3, vv10, vs45
    vsrl vv3, vv3, vs45
    vdivuw vv10, vv0, vs53
    vsll vv4, vv10, vs45
    vsrl vv4, vv4, vs45
    vlsd vs2, vs52
    vsll vv5, vv4, vs57
    vlxd vv6, vs60, vv5
    vsll vv5, vv3, vs57
    vlxd vv7, vs58, vv5
    vsll vv5, vv2, vs57
    vlxd vv8, vs61, vv5
    vsll vv5, vv1, vs57
    vlxd vv9, vs59, vv5
    vsrl vs3, vs2, vs51
    vadd vs3, vs3, vs2
    vsll vs3, vs3, vs50
    vadd vs3, vs49, vs3
    vsrl vv5, vv6, vs51
    vsll vv5, vv5, vs50
    vsll vv6, vv6, vs48
    vadd vv5, vv5, vv6
    vsrl vv6, vv7, vs51
    vsll vv6, vv6, vs48
    vadd vv5, vv5, vv6
    vsll vv7, vv7, vs47
    vadd vv5, vv5, vv7
    vsrl vv6, vv8, vs51
    vsll vv6, vv6, vs47
    vadd vv5, vv5, vv6
    vsll vv8, vv8, vs55
    vadd vv5, vv5, vv8
    vsrl vv6, vv9, vs51
    vsll vv6, vv6, vs55
    vadd vv5, vv5, vv6
    vsll vv9, vv9, vs56
    vadd vv5, vv5, vv9
    vlxw vv10, vs3, vv5
    vmul vv4, vv4, vs46
    vsll vv3, vv3, vs47
    vsll vv2, vv2, vs55
    vadd vv4, vv4, vv3
    vadd vv4, vv4, vv2
    vsll vv1, vv1, vs56
    vadd vv4, vv4, vv1
    vsxw vv10, vs62, vv4
    vstop

    .text
    .align 3
    .globl net_kernel_4_wt
net_kernel_4_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsd vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_5_wt
net_kernel_5_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs57
    vsrl vv2, vv0, vs56
    vremuw vv9, vv2, vs55
    vsll vv2, vv9, vs43
    vsrl vv2, vv2, vs43
    vdivuw vv9, vv0, vs54
    vsll vv3, vv9, vs43
    vsrl vv3, vv3, vs43
    vlsd vs2, vs53
    vsll vv4, vv3, vs57
    vlxd vv5, vs58, vv4
    vdivu vv4, vv0, vs52
    vsll vv4, vv4, vs57
    vmul vv6, vv3, vs51
    vsub vv4, vv4, vv6
    vlxd vv6, vs62, vv4
    vsll vv4, vv2, vs57
    vlxd vv7, vs60, vv4
    vsll vv4, vv1, vs57
    vlxd vv8, vs59, vv4
    vsrl vs3, vs2, vs50
    vadd vs3, vs3, vs2
    vcmplt vp1, vv6, vs0
    vsll vv6, vv6, vs49
    @vp1 vadd vv4, vv6, vs48
    @!vp1 vadd vv4, vv6, vs0
    vmul vs3, vs3, vs47
    vadd vs3, vs46, vs3
    vsrl vv6, vv5, vs50
    vmul vv6, vv6, vs47
    vmul vv5, vv5, vs45
    vadd vv6, vv6, vv5
    vsrl vv5, vv7, vs50
    vsll vv5, vv5, vs44
    vadd vv6, vv6, vv5
    vsll vv7, vv7, vs49
    vadd vv6, vv6, vv7
    vsrl vv5, vv8, vs50
    vsll vv5, vv5, vs49
    vadd vv6, vv6, vv5
    vsll vv4, vv4, vs56
    vadd vv6, vv6, vv4
    vsll vv8, vv8, vs56
    vadd vv6, vv6, vv8
    vlxw vv9, vs3, vv6
    vsll vv2, vv2, vs49
    vdivu vv3, vv0, vs52
    vmul vv3, vv3, vs48
    vadd vv3, vv3, vv2
    vsll vv1, vv1, vs56
    vadd vv3, vv3, vv1
    vsxw vv9, vs61, vv3
    vstop

    .text
    .align 3
    .globl net_kernel_6_wt
net_kernel_6_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vdivuw vv8, vv0, vs57
    vmulw vv9, vv8, vs56
    vaddw vv9, vv9, vv0
    vsll vv1, vv9, vs41
    vsrl vv1, vv1, vs41
    vdivuw vv8, vv0, vs55
    vsll vv2, vv8, vs41
    vsrl vv2, vv2, vs41
    vlsd vs2, vs54
    vsll vv3, vv2, vs53
    vlxd vv4, vs58, vv3
    vsll vv3, vv0, vs41
    vsrl vv3, vv3, vs41
    vdivu vv3, vv3, vs52
    vsll vv3, vv3, vs53
    vmul vv5, vv2, vs51
    vsub vv3, vv3, vv5
    vlxd vv5, vs60, vv3
    vsll vv3, vv0, vs41
    vsrl vv3, vv3, vs41
    vdivu vv6, vv3, vs50
    vsll vv6, vv6, vs53
    vdivu vv3, vv3, vs52
    vmul vv3, vv3, vs51
    vsub vv6, vv6, vv3
    vlxd vv3, vs59, vv6
    vsll vv6, vv1, vs53
    vlxd vv7, vs61, vv6
    vsrl vs3, vs2, vs49
    vadd vs3, vs3, vs2
    vcmplt vp1, vv5, vs0
    @vp1 vadd vv6, vv5, vs50
    @!vp1 vadd vv6, vv5, vs0
    vcmplt vp1, vv3, vs0
    vsll vv3, vv3, vs48
    @vp1 vadd vv5, vv3, vs47
    @!vp1 vadd vv5, vv3, vs0
    vmul vs3, vs3, vs46
    vadd vs3, vs45, vs3
    vmul vv6, vv6, vs44
    vsrl vv3, vv4, vs49
    vmul vv3, vv3, vs46
    vmul vv4, vv4, vs43
    vadd vv3, vv3, vv4
    vadd vv3, vv3, vv6
    vsrl vv4, vv7, vs49
    vsll vv4, vv4, vs42
    vadd vv3, vv3, vv4
    vsll vv5, vv5, vs48
    vadd vv3, vv3, vv5
    vsll vv7, vv7, vs48
    vadd vv3, vv3, vv7
    vlxw vv8, vs3, vv3
    vsll vv2, vv0, vs41
    vsrl vv2, vv2, vs41
    vdivu vv2, vv2, vs50
    vmul vv2, vv2, vs47
    vsll vv1, vv1, vs48
    vadd vv2, vv2, vv1
    vsxw vv8, vs62, vv2
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a3, a2, 63
	addi	a3, a3, 514
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a5, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi1)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 3
	sd	a7, %pcrel_lo(.Lpcrel_hi1)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi0)(a3)
	mv	a6, a0
	beqz	a7, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a7
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a6
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 63
	addi	a3, a3, 1026
	li	a4, 3
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi3:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a5, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi4:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi4)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 3
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi4)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi3)(a3)
	mv	a6, a0
	beqz	a7, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a7
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a7, a6
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 513
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi6:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi8:
	auipc	a5, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi7:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi8)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi7)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 3
	sd	a7, %pcrel_lo(.Lpcrel_hi7)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi6)(a3)
	mv	a6, a0
	beqz	a7, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a7
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a6
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 513
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi9:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi11:
	auipc	a5, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi10:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi11)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi10)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 3
	sd	a7, %pcrel_lo(.Lpcrel_hi10)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi9)(a3)
	mv	a6, a0
	beqz	a7, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a7
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a6
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	t0, 1048568
	addi	t0, t0, -1045
	srli	t0, t0, 1
	not	t0, t0
	#APP
	vsetcfg t0
	#NO_APP
	#APP
	vmcs vs62, a7
	#NO_APP
	#APP
	vmcs vs61, a4
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	#APP
	vmcs vs59, a5
	#NO_APP
	#APP
	vmcs vs58, a3
	#NO_APP
	li	a2, 3
	#APP
	vmcs vs57, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs56, a2
	#NO_APP
	li	a2, 4
	#APP
	vmcs vs55, a2
	#NO_APP
	li	a2, 6
	#APP
	vmcs vs54, a2
	#NO_APP
	li	a3, 96
	#APP
	vmcs vs53, a3
	#NO_APP
	#APP
	vmcs vs52, a1
	#NO_APP
	li	a1, 63
	li	a3, 9
	#APP
	vmcs vs51, a1
	#NO_APP
	#APP
	vmcs vs50, a3
	#NO_APP
	#APP
	vmcs vs49, a6
	#NO_APP
	li	a1, 8
	#APP
	vmcs vs48, a1
	#NO_APP
	#APP
	vmcs vs47, a2
	#NO_APP
	li	a1, 384
	li	a2, 32
	#APP
	vmcs vs46, a1
	#NO_APP
	#APP
	vmcs vs45, a2
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi12:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi14:
	auipc	a4, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi13:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi14)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi13)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi13)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi12)(a2)
	mv	a5, a0
	beqz	a6, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a5, a6
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a5
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_4_ct                 # -- Begin function net_kernel_4_ct
	.p2align	2
	.type	net_kernel_4_ct,@function
net_kernel_4_ct:                        # @net_kernel_4_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 513
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB5_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi15:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi17:
	auipc	a5, %pcrel_hi(net_kernel_4_wt)
.Lpcrel_hi16:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi17)
	j	.LBB5_3
.LBB5_2:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi16)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 3
	sd	a7, %pcrel_lo(.Lpcrel_hi16)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB5_7
.LBB5_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi15)(a3)
	mv	a6, a0
	beqz	a7, .LBB5_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a6, a7
.LBB5_5:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB5_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a6
	j	.LBB5_2
.LBB5_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end5:
	.size	net_kernel_4_ct, .Lfunc_end5-net_kernel_4_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_5_ct                 # -- Begin function net_kernel_5_ct
	.p2align	2
	.type	net_kernel_5_ct,@function
net_kernel_5_ct:                        # @net_kernel_5_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	t0, 1048567
	addi	t0, t0, 2029
	srli	t0, t0, 1
	not	t0, t0
	#APP
	vsetcfg t0
	#NO_APP
	#APP
	vmcs vs62, a3
	#NO_APP
	#APP
	vmcs vs61, a7
	#NO_APP
	#APP
	vmcs vs60, a4
	#NO_APP
	#APP
	vmcs vs59, a5
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a2, 3
	#APP
	vmcs vs57, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs56, a2
	#NO_APP
	li	a2, 6
	#APP
	vmcs vs55, a2
	#NO_APP
	li	a3, 144
	#APP
	vmcs vs54, a3
	#NO_APP
	#APP
	vmcs vs53, a1
	#NO_APP
	li	a1, 24
	li	a3, 48
	#APP
	vmcs vs52, a1
	#NO_APP
	#APP
	vmcs vs51, a3
	#NO_APP
	li	a1, 63
	li	a3, 4
	#APP
	vmcs vs50, a1
	#NO_APP
	#APP
	vmcs vs49, a3
	#NO_APP
	li	a1, 96
	li	a3, 768
	#APP
	vmcs vs48, a1
	#NO_APP
	#APP
	vmcs vs47, a3
	#NO_APP
	#APP
	vmcs vs46, a6
	#NO_APP
	li	a1, 384
	#APP
	vmcs vs45, a1
	#NO_APP
	li	a1, 32
	#APP
	vmcs vs44, a2
	#NO_APP
	#APP
	vmcs vs43, a1
	#NO_APP
	beqz	a0, .LBB6_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi18:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi20:
	auipc	a4, %pcrel_hi(net_kernel_5_wt)
.Lpcrel_hi19:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi20)
	j	.LBB6_3
.LBB6_2:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi19)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi19)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB6_7
.LBB6_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi18)(a2)
	mv	a5, a0
	beqz	a6, .LBB6_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a5, a6
.LBB6_5:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB6_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a5
	j	.LBB6_2
.LBB6_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end6:
	.size	net_kernel_5_ct, .Lfunc_end6-net_kernel_5_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_6_ct                 # -- Begin function net_kernel_6_ct
	.p2align	2
	.type	net_kernel_6_ct,@function
net_kernel_6_ct:                        # @net_kernel_6_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	t0, 1048559
	addi	t0, t0, 2031
	srli	t0, t0, 1
	not	t0, t0
	#APP
	vsetcfg t0
	#NO_APP
	#APP
	vmcs vs62, a7
	#NO_APP
	#APP
	vmcs vs61, a5
	#NO_APP
	#APP
	vmcs vs60, a3
	#NO_APP
	#APP
	vmcs vs59, a4
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a2, 6
	#APP
	vmcs vs57, a2
	#NO_APP
	li	a3, -6
	#APP
	vmcs vs56, a3
	#NO_APP
	li	a3, 216
	#APP
	vmcs vs55, a3
	#NO_APP
	li	a3, 3
	#APP
	vmcs vs54, a1
	#NO_APP
	#APP
	vmcs vs53, a3
	#NO_APP
	li	a1, 36
	li	a3, 48
	#APP
	vmcs vs52, a1
	#NO_APP
	#APP
	vmcs vs51, a3
	#NO_APP
	#APP
	vmcs vs50, a2
	#NO_APP
	li	a1, 63
	#APP
	vmcs vs49, a1
	#NO_APP
	li	a1, 2
	#APP
	vmcs vs48, a1
	#NO_APP
	li	a1, 24
	#APP
	vmcs vs47, a1
	#NO_APP
	li	a1, 1152
	#APP
	vmcs vs46, a1
	#NO_APP
	#APP
	vmcs vs45, a6
	#NO_APP
	li	a1, 96
	li	a2, 576
	#APP
	vmcs vs44, a1
	#NO_APP
	#APP
	vmcs vs43, a2
	#NO_APP
	li	a1, 4
	li	a2, 32
	#APP
	vmcs vs42, a1
	#NO_APP
	#APP
	vmcs vs41, a2
	#NO_APP
	beqz	a0, .LBB7_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi21:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi23:
	auipc	a4, %pcrel_hi(net_kernel_6_wt)
.Lpcrel_hi22:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi23)
	j	.LBB7_3
.LBB7_2:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi22)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi22)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB7_7
.LBB7_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi21)(a2)
	mv	a5, a0
	beqz	a6, .LBB7_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a5, a6
.LBB7_5:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB7_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a5
	j	.LBB7_2
.LBB7_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end7:
	.size	net_kernel_6_ct, .Lfunc_end7-net_kernel_6_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -144
	.cfi_def_cfa_offset 144
	sd	ra, 136(sp)                     # 8-byte Folded Spill
	sd	s0, 128(sp)                     # 8-byte Folded Spill
	sd	s1, 120(sp)                     # 8-byte Folded Spill
	sd	s2, 112(sp)                     # 8-byte Folded Spill
	sd	s3, 104(sp)                     # 8-byte Folded Spill
	sd	s4, 96(sp)                      # 8-byte Folded Spill
	sd	s5, 88(sp)                      # 8-byte Folded Spill
	sd	s6, 80(sp)                      # 8-byte Folded Spill
	sd	s7, 72(sp)                      # 8-byte Folded Spill
	sd	s8, 64(sp)                      # 8-byte Folded Spill
	sd	s9, 56(sp)                      # 8-byte Folded Spill
	sd	s10, 48(sp)                     # 8-byte Folded Spill
	sd	s11, 40(sp)                     # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	.cfi_offset s8, -80
	.cfi_offset s9, -88
	.cfi_offset s10, -96
	.cfi_offset s11, -104
	mv	s6, a0
	li	a0, 112
	call	malloc
	sd	a0, 32(sp)                      # 8-byte Folded Spill
.Lpcrel_hi24:
	auipc	s5, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi25:
	auipc	s3, %pcrel_hi(hwacha_grid_size)
	addi	a1, a0, 63
	li	s2, 6
	andi	s1, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	sd	s2, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 6
	mv	a1, s1
	call	net_kernel_ct
	li	a0, 112
	call	malloc
	sd	a0, 24(sp)                      # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	addi	a1, a0, 63
	andi	s4, a1, -64
	sd	s2, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 6
	mv	a1, s1
	mv	a2, s4
	call	net_kernel_0_ct
	li	a0, 96
	call	malloc
	sd	a0, 16(sp)                      # 8-byte Folded Spill
	li	a2, 4
	addi	a1, a0, 63
	andi	s10, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	sd	a2, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 4
	mv	a1, s10
	call	net_kernel_1_ct
	li	a0, 80
	call	malloc
	sd	a0, 8(sp)                       # 8-byte Folded Spill
	li	a2, 2
	addi	a1, a0, 63
	andi	s9, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	sd	a2, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 2
	mv	a1, s9
	call	net_kernel_2_ct
	li	a0, 72
	call	malloc
	mv	s7, a0
	addi	a0, a0, 63
	andi	s11, a0, -64
	sd	zero, 0(s11)
	li	a0, 832
	call	malloc
	mv	s8, a0
	li	a0, 192
	addi	a1, s8, 63
	andi	s0, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	sd	a0, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 192
	mv	a1, s11
	mv	a2, s9
	mv	a3, s4
	mv	a4, s10
	mv	a5, s10
	mv	a6, s6
	mv	a7, s0
	call	net_kernel_3_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	sd	s2, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 6
	mv	a1, s1
	call	net_kernel_4_ct
	li	a0, 1216
	call	malloc
	mv	s6, a0
	li	a0, 288
	addi	a1, s6, 63
	andi	s2, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	sd	a0, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 288
	mv	a1, s11
	mv	a2, s9
	mv	a3, s1
	mv	a4, s4
	mv	a5, s10
	mv	a6, s0
	mv	a7, s2
	call	net_kernel_5_ct
	li	a0, 1792
	call	malloc
	mv	s0, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi24)(s5)
	addi	a0, a0, 63
	li	a1, 432
	andi	a7, a0, -64
	sd	a1, %pcrel_lo(.Lpcrel_hi25)(s3)
	li	a0, 432
	mv	a1, s11
	mv	a2, s9
	mv	a3, s1
	mv	a4, s1
	mv	a5, s4
	mv	a6, s2
	call	net_kernel_6_ct
	ld	a0, 32(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 24(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 16(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 8(sp)                       # 8-byte Folded Reload
	call	free
	mv	a0, s7
	call	free
	mv	a0, s8
	call	free
	mv	a0, s6
	call	free
	mv	a0, s0
	ld	ra, 136(sp)                     # 8-byte Folded Reload
	ld	s0, 128(sp)                     # 8-byte Folded Reload
	ld	s1, 120(sp)                     # 8-byte Folded Reload
	ld	s2, 112(sp)                     # 8-byte Folded Reload
	ld	s3, 104(sp)                     # 8-byte Folded Reload
	ld	s4, 96(sp)                      # 8-byte Folded Reload
	ld	s5, 88(sp)                      # 8-byte Folded Reload
	ld	s6, 80(sp)                      # 8-byte Folded Reload
	ld	s7, 72(sp)                      # 8-byte Folded Reload
	ld	s8, 64(sp)                      # 8-byte Folded Reload
	ld	s9, 56(sp)                      # 8-byte Folded Reload
	ld	s10, 48(sp)                     # 8-byte Folded Reload
	ld	s11, 40(sp)                     # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	.cfi_restore s8
	.cfi_restore s9
	.cfi_restore s10
	.cfi_restore s11
	addi	sp, sp, 144
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end8:
	.size	net, .Lfunc_end8-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.section	".note.GNU-stack","",@progbits
