# generated by hwacha-cc from myocyte/myocyte.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl kernel_gpu_opencl_wt
kernel_gpu_opencl_wt:
    vpset vp0
    veidx vv0
    vpclear vp1
    vaddw vv1, vs63, vs0
    vcmpeq vp2, vv1, vs0
    vpop vp3, vp0, vp2, vp2, 0x80
    vpop vp4, vp0, vp2, vp2, 0x02
    vcmpeq vp2, vv0, vs0
    vpop vp5, vp3, vp2, vp2, 0x80
    vpop vp6, vp3, vp2, vp2, 0x02
    @!vp4 vcjal 0, vs1, .Lkernel_gpu_opencl_skip0
    vaddw vv1, vs63, vs0
    vcmpeq vp2, vv1, vs62
    vcmpeq vp3, vv0, vs0
    vpop vp3, vp2, vp3, vp1, 0xD8
.Lkernel_gpu_opencl_skip0:
    vpop vp2, vp4, vp3, vp3, 0x80
    vpop vp7, vp4, vp3, vp3, 0x02
    vpop vp3, vp2, vp2, vp2, 0xAA
    vpop vp3, vp3, vp7, vp7, 0xEE
    vpop vp3, vp3, vp5, vp5, 0xEE
    vpop vp3, vp3, vp6, vp6, 0xEE
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	kernel_gpu_opencl_ct            # -- Begin function kernel_gpu_opencl_ct
	.p2align	2
	.type	kernel_gpu_opencl_ct,@function
kernel_gpu_opencl_ct:                   # @kernel_gpu_opencl_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a1, 1048566
	addi	a1, a1, -3
	srli	a1, a1, 1
	not	a1, a1
	li	a2, 1
	#APP
	vsetcfg a1
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a4, %pcrel_hi(kernel_gpu_opencl_wt)
.Lpcrel_hi1:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi1)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a5, a7, a6
	sd	a5, %pcrel_lo(.Lpcrel_hi1)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	addi	a1, a1, 1
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi0)(a2)
	mv	a5, a0
	beqz	a6, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a5, a6
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a5
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	kernel_gpu_opencl_ct, .Lfunc_end0-kernel_gpu_opencl_ct
	.cfi_endproc
                                        # -- End function
	.type	hwacha_group_size,@object       # @hwacha_group_size
	.bss
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.section	".note.GNU-stack","",@progbits
