#!/usr/bin/env python3
"""Export one torch.* operator (docs.pytorch.org/docs/2.14/torch.html) through torch-mlir to
linalg-on-tensors, plus a PyTorch reference for one call. Every case is a single-input module
net(x) -> one float tensor: second operands, indices, masks and weights are constant buffers, integer
and boolean results are cast to float, several results are flattened and concatenated, the in-place
variants (op_) run on a copy of the input and return it, and the random-sampling functions run under
torch.manual_seed(0) with the reference drawn under the same seed (one draw pinned).
usage: export_op.py <name> <mlir_out> <check_out>   |   --list"""
import sys, os, math, struct, numpy as np, torch, torch.nn.functional as NF
from torch_mlir import fx
import inspect, textwrap, torch_mlir.extras.fx_importer as _fxi
# torch.export folds a constant tensor argument of a list-taking op (cat / stack / index_* with a buffer
# operand) into a literal torch.Tensor inside the list, which torch-mlir's importer rejects
# ("Heterogeneous lists are not supported"); import it as a vtensor literal (as ../torchgeometric does).
_src = textwrap.dedent(inspect.getsource(_fxi.GraphNodeImporter._import_list_argument))
_old = """        else:
            assert (is_optional_type and operand_type is NoneType) or ("""
assert _old in _src
_new = """        elif isinstance(operand, torch.Tensor):
            with loc:
                val = self._import_literal(operand)
        else:
            assert (is_optional_type and operand_type is NoneType) or ("""
_ns = dict(vars(_fxi)); exec("from typing import *\n" + _src.replace(_old, _new), _ns)
_fxi.GraphNodeImporter._import_list_argument = _ns['_import_list_argument']
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import op_lib as LB

class Case(torch.nn.Module):
    def __init__(s, body, **bufs):
        super().__init__(); s.body = body
        for k, v in bufs.items(): s.register_buffer(k, v)
    def forward(s, x): return s.body(s, x)
class Ref(Case):
    """exported body differs from the reference (the genuine torch call, what check.bin holds)"""
    def __init__(s, body, ref, _atol=1e-4, **bufs): super().__init__(body, **bufs); s.ref = ref; s.atol = _atol
    def reference(s, x): return s.ref(s, x)
def export_linalg(m, x):
    from torch_mlir.extras.fx_decomp_util import get_decomposition_table
    table = {k: v for k, v in get_decomposition_table().items() if not any(str(k).startswith('aten.' + n) for n in ('zeros', 'ones', 'full', 'new_zeros', 'new_ones', 'new_full', 'empty_like', 'zeros_like', 'ones_like', 'full_like'))}
    return fx.export_and_import(torch.export.export(m, (x,)), x, output_type='linalg-on-tensors', func_name='net', decomposition_table=table)
def R(*shape): return torch.randn(*shape)
def U(*shape): return torch.rand(*shape)
def f(t): return t.float()
def flat(*ts): return torch.cat([t.reshape(-1).float() for t in ts])
def seeded(fn):
    def g(s, x): torch.manual_seed(0); return fn(s, x)
    return g

def build(name):
    torch.manual_seed(0)
    C = {}
    def case(n_, body, x, **b): C[n_] = lambda: (Case(body, **b), x)
    def rcase(n_, body, ref, x, **b): C[n_] = lambda: (Ref(body, ref, **b), x)
    X = R(4, 8); XP = U(4, 8) + 0.5; X2 = R(4, 8); Y = R(4, 8); XI = torch.randint(-5, 6, (4, 8)); XU = torch.randint(0, 8, (4, 8))
    def unary(n, fn, x=None, ref=None):
        if ref is None: case(n, lambda s, x: fn(x), X if x is None else x)
        else: rcase(n, lambda s, x: fn(x), lambda s, x: ref(x), X if x is None else x)
    def inplace(n, meth, x=None):   # torch.op_(t): the in-place variant on a copy of the input
        case(n, lambda s, x: (lambda t: (meth(t), t)[1])(x.clone()), X if x is None else x)
    def binary(n, fn, x=None, y=None): case(n, lambda s, x: fn(x, s.y), X if x is None else x, y=Y if y is None else y)
    # ================= Tensors =================
    case('is_tensor', lambda s, x: x * float(torch.is_tensor(x)), X)
    case('is_complex', lambda s, x: x * (1.0 if torch.is_complex(x) else 0.5), X)
    case('is_conj', lambda s, x: x * (1.0 if torch.is_conj(x) else 0.5), X)
    case('is_floating_point', lambda s, x: x * float(torch.is_floating_point(x)), X)
    case('is_nonzero', lambda s, x: x * float(torch.is_nonzero(torch.tensor([2.0]))), X)
    case('is_same_size', lambda s, x: x * float(torch.is_same_size(x, s.y)), X, y=Y)
    case('is_signed', lambda s, x: x * float(torch.is_signed(x)), X)
    case('numel', lambda s, x: x / torch.numel(x), X)
    # ---- creation ops (the created tensor combined with the input so the graph has an input and a constant)
    rcase('rand', lambda s, x: x + s.r, seeded(lambda s, x: x + torch.rand(4, 8)), X, r=(lambda: (torch.manual_seed(0), torch.rand(4, 8))[1])())
    rcase('rand_like', lambda s, x: x + s.r, seeded(lambda s, x: x + torch.rand_like(x)), X, r=(lambda: (torch.manual_seed(0), torch.rand_like(X))[1])())
    rcase('randn', lambda s, x: x + s.r, seeded(lambda s, x: x + torch.randn(4, 8)), X, r=(lambda: (torch.manual_seed(0), torch.randn(4, 8))[1])())
    rcase('randn_like', lambda s, x: x + s.r, seeded(lambda s, x: x + torch.randn_like(x)), X, r=(lambda: (torch.manual_seed(0), torch.randn_like(X))[1])())
    rcase('randint', lambda s, x: x + s.r, seeded(lambda s, x: x + torch.randint(0, 10, (4, 8)).float()), X, r=(lambda: (torch.manual_seed(0), torch.randint(0, 10, (4, 8)).float())[1])())
    rcase('randint_like', lambda s, x: x + s.r, seeded(lambda s, x: x + torch.randint_like(x, 0, 10)), X, r=(lambda: (torch.manual_seed(0), torch.randint_like(X, 0, 10))[1])())
    rcase('randperm', lambda s, x: x[s.p], seeded(lambda s, x: x[torch.randperm(4)]), X, p=(lambda: (torch.manual_seed(0), torch.randperm(4))[1])())
    case('empty', lambda s, x: x + torch.empty(4, 8).zero_(), X)
    case('tensor', lambda s, x: x + torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]), X)
    case('asarray', lambda s, x: x + torch.asarray([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]), X)
    case('as_tensor', lambda s, x: x + torch.as_tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]), X)
    case('as_strided', lambda s, x: torch.as_strided(x, (4, 4), (8, 2)), X)
    case('zeros', lambda s, x: x + torch.zeros(4, 8), X); case('zeros_like', lambda s, x: x + torch.zeros_like(x), X)
    case('ones', lambda s, x: x + torch.ones(4, 8), X); case('ones_like', lambda s, x: x + torch.ones_like(x), X)
    case('arange', lambda s, x: x + torch.arange(8).float(), X); rcase('range', lambda s, x: x + torch.arange(8).float(), lambda s, x: x + torch.range(0, 7).float(), X)
    case('linspace', lambda s, x: x + torch.linspace(0, 1, 8), X); rcase('logspace', lambda s, x: x + LB.powf(torch.full((8,), 10.0), torch.linspace(0, 1, 8)), lambda s, x: x + torch.logspace(0, 1, 8), X)
    case('eye', lambda s, x: x[:, :4] + torch.eye(4), X)
    case('empty_like', lambda s, x: x + torch.empty_like(x).zero_(), X)
    case('empty_strided', lambda s, x: x + torch.empty_strided((4, 8), (8, 1)).zero_(), X)
    case('full', lambda s, x: x + torch.full((4, 8), 2.5), X); case('full_like', lambda s, x: x + torch.full_like(x, 2.5), X)
    # complex: [re | im] along the last dim (torch-mlir has no complex tensors)
    rcase('complex', lambda s, x: torch.cat([x, s.y], -1), lambda s, x: torch.view_as_real(torch.complex(x, s.y)).permute(0, 2, 1).reshape(4, 16), X, y=Y)
    rcase('real', lambda s, x: x[:, :8], lambda s, x: torch.real(torch.complex(x[:, :8], x[:, 8:])), torch.cat([X, Y], -1))
    rcase('imag', lambda s, x: x[:, 8:], lambda s, x: torch.imag(torch.complex(x[:, :8], x[:, 8:])), torch.cat([X, Y], -1))
    rcase('polar', lambda s, x: torch.cat([x * torch.cos(s.a), x * torch.sin(s.a)], -1), lambda s, x: torch.view_as_real(torch.polar(x, s.a)).permute(0, 2, 1).reshape(4, 16), XP, a=Y)
    unary('abs', torch.abs); inplace('abs_', lambda t: t.abs_()); unary('absolute', torch.absolute)
    rcase('angle', lambda s, x: LB.atan2(x[:, 8:], x[:, :8]), lambda s, x: torch.angle(torch.complex(x[:, :8], x[:, 8:])), torch.cat([X, Y], -1))
    case('scalar_tensor', lambda s, x: x + torch.scalar_tensor(1.5), X)
    binary('heaviside', torch.heaviside, y=torch.tensor(0.5).expand(4, 8).clone())
    # ---- indexing, slicing, joining, mutating
    unary('adjoint', lambda x: torch.adjoint(x)); rcase('alias_copy', lambda s, x: x, lambda s, x: torch.alias_copy(x), X)
    rcase('argwhere', lambda s, x: (x > 0).float(), lambda s, x: LB.pair_mask(torch.argwhere(x > 0).t(), 4, 8), X)   # the (4, 8) 0/1 mask of the returned positions
    rcase('as_strided_copy', lambda s, x: torch.as_strided(x, (4, 4), (8, 2)), lambda s, x: torch.as_strided_copy(x, (4, 4), (8, 2)), X)
    src_ = R(4, 4); rcase('as_strided_scatter', lambda s, x: x * (1 - s.M) + s.E, lambda s, x: torch.as_strided_scatter(x, s.src, (4, 4), (8, 2)), X, src=src_, M=torch.as_strided_scatter(torch.zeros(4, 8), torch.ones(4, 4), (4, 4), (8, 2)), E=torch.as_strided_scatter(torch.zeros(4, 8), src_, (4, 4), (8, 2)))
    case('cat', lambda s, x: torch.cat([x, s.y], 0), X, y=Y); case('concat', lambda s, x: torch.concat([x, s.y], 1), X, y=Y); case('concatenate', lambda s, x: torch.concatenate([x, s.y]), X, y=Y)
    unary('conj', lambda x: torch.conj(x)); case('chunk', lambda s, x: flat(*torch.chunk(x, 4, 1)), X)
    unary('detach', torch.detach); rcase('detach_copy', lambda s, x: x, lambda s, x: torch.detach_copy(x), X)
    rcase('diagonal_copy', lambda s, x: torch.diagonal(x, 1), lambda s, x: torch.diagonal_copy(x, 1), X); unary('diagonal', lambda x: torch.diagonal(x, -1))
    case('dsplit', lambda s, x: flat(*torch.dsplit(x, 2)), R(2, 4, 4)); case('column_stack', lambda s, x: torch.column_stack([x, s.y]), X, y=Y); case('dstack', lambda s, x: torch.dstack([x, s.y]), X, y=Y)
    rcase('expand_copy', lambda s, x: x[:, :1].expand(4, 8), lambda s, x: torch.expand_copy(x[:, :1], (4, 8)), X); unary('Tensor.expand', lambda x: x[:1].expand(4, 8))
    case('fill', lambda s, x: torch.fill(x, 0.5) + x, X)
    case('gather', lambda s, x: torch.gather(x, 1, s.i), X, i=XU)
    case('hsplit', lambda s, x: flat(*torch.hsplit(x, 2)), X); case('hstack', lambda s, x: torch.hstack([x, s.y]), X, y=Y)
    rcase('index_add', lambda s, x: LB.index_add_rows(x, s.i, s.src, 2.0), lambda s, x: torch.index_add(x, 0, s.i, s.src, alpha=2.0), X, i=torch.tensor([0, 2, 3]), src=R(3, 8))
    rcase('Tensor.index_add_', lambda s, x: LB.index_add_rows(x, s.i, s.src), lambda s, x: x.clone().index_add_(0, s.i, s.src), X, i=torch.tensor([0, 2, 3]), src=R(3, 8))
    rcase('index_copy', lambda s, x: LB.index_copy_rows(x, s.i, s.src), lambda s, x: torch.index_copy(x, 0, s.i, s.src), X, i=torch.tensor([3, 1, 0]), src=R(3, 8))
    rcase('Tensor.index_copy_', lambda s, x: LB.index_copy_rows(x, s.i, s.src), lambda s, x: x.clone().index_copy_(0, s.i, s.src), X, i=torch.tensor([3, 1, 0]), src=R(3, 8))
    rcase('index_put_', lambda s, x: LB.index_put_acc(x, s.i, s.j, s.v), lambda s, x: x.clone().index_put_((s.i, s.j), s.v, accumulate=True), X, i=torch.tensor([0, 1, 1]), j=torch.tensor([2, 2, 5]), v=R(3))
    rcase('index_reduce', lambda s, x: x * torch.exp(LB.onehot(s.i, 4).t() @ torch.log(s.src.abs())) * torch.cos(math.pi * (LB.onehot(s.i, 4).t() @ (s.src < 0).float())), lambda s, x: torch.index_reduce(x, 0, s.i, s.src, 'prod'), X, i=torch.tensor([0, 2, 0]), src=R(3, 8))
    rcase('Tensor.index_reduce_', lambda s, x: torch.maximum(x, torch.where(LB.onehot(s.i, 4).t()[:, :, None] > 0, s.src[None], torch.full_like(s.src[None].expand(4, -1, -1), -1e30)).amax(1)), lambda s, x: x.clone().index_reduce_(0, s.i, s.src, 'amax'), X, i=torch.tensor([0, 2, 0]), src=R(3, 8))
    case('index_select', lambda s, x: torch.index_select(x, 1, s.i), X, i=torch.tensor([7, 0, 3]))
    case('masked_fill', lambda s, x: torch.masked_fill(x, s.m, 9.0), X, m=U(4, 8) > 0.5)
    # masked_select: a data-dependent length; the mask is a constant, so the selection is a constant gather
    m_ = U(4, 8) > 0.5; rcase('masked_select', lambda s, x: x.reshape(-1)[s.idx], lambda s, x: torch.masked_select(x, s.m), X, m=m_, idx=m_.reshape(-1).nonzero().view(-1))
    unary('movedim', lambda x: torch.movedim(x, 0, 1)); unary('moveaxis', lambda x: torch.moveaxis(x, 1, 0))
    unary('narrow', lambda x: torch.narrow(x, 1, 2, 4)); rcase('narrow_copy', lambda s, x: torch.narrow(x, 0, 1, 2), lambda s, x: torch.narrow_copy(x, 0, 1, 2), X); unary('Tensor.narrow', lambda x: x.narrow(1, 1, 3))
    rcase('nonzero', lambda s, x: (x > 0).float(), lambda s, x: LB.pair_mask(torch.nonzero(x > 0).t(), 4, 8), X)
    rcase('nonzero_static', lambda s, x: (x > 0).float(), lambda s, x: LB.pair_mask((lambda z: z[z[:, 0] >= 0])(torch.nonzero_static(x > 0, size=32, fill_value=-1)).t(), 4, 8), X)
    unary('permute', lambda x: torch.permute(x, (1, 0))); rcase('permute_copy', lambda s, x: torch.permute(x, (1, 0)), lambda s, x: torch.permute_copy(x, (1, 0)), X)
    rcase('put', lambda s, x: (x.reshape(-1) + LB.onehot(s.i, 32).t() @ s.v).reshape(4, 8), lambda s, x: torch.put(x, s.i, s.v, accumulate=True), X, i=torch.tensor([0, 5, 31, 5]), v=R(4))
    unary('reshape', lambda x: torch.reshape(x, (8, 4)))
    case('row_stack', lambda s, x: torch.row_stack([x, s.y]), X, y=Y); case('vstack', lambda s, x: torch.vstack([x, s.y]), X, y=Y)
    unary('select', lambda x: torch.select(x, 1, 3)); rcase('select_copy', lambda s, x: torch.select(x, 0, 2), lambda s, x: torch.select_copy(x, 0, 2), X)
    iu_ = torch.stack([torch.randperm(8) for _ in range(4)]); rcase('scatter', lambda s, x: LB.scatter_rows(x, s.i, s.src), lambda s, x: torch.scatter(x, 1, s.i, s.src), X, i=iu_, src=R(4, 8))
    rcase('Tensor.scatter_', lambda s, x: LB.scatter_rows(x, s.i, s.src), lambda s, x: x.clone().scatter_(1, s.i, s.src), X, i=iu_, src=R(4, 8))
    d_ = R(4); rcase('diagonal_scatter', lambda s, x: x * (1 - s.M) + s.E, lambda s, x: torch.diagonal_scatter(x, s.d, 1), X, d=d_, M=torch.diagonal_scatter(torch.zeros(4, 8), torch.ones(4), 1), E=torch.diagonal_scatter(torch.zeros(4, 8), d_, 1))
    case('select_scatter', lambda s, x: torch.select_scatter(x, s.src, 0, 2), X, src=R(8))
    rcase('slice_copy', lambda s, x: x[:, 1:7:2], lambda s, x: torch.slice_copy(x, 1, 1, 7, 2), X)
    case('slice_scatter', lambda s, x: torch.slice_scatter(x, s.src, 1, 0, 8, 2), X, src=R(4, 4))
    rcase('scatter_add', lambda s, x: LB.scatter_rows(x, s.i, s.src, 'add'), lambda s, x: torch.scatter_add(x, 1, s.i, s.src), X, i=XU, src=R(4, 8))
    rcase('Tensor.scatter_add_', lambda s, x: LB.scatter_cols(x, s.i, s.src), lambda s, x: x.clone().scatter_add_(0, s.i, s.src), X, i=torch.randint(0, 4, (4, 8)), src=R(4, 8))
    rcase('scatter_reduce', lambda s, x: LB.scatter_amax_rows(x, s.i, s.src), lambda s, x: torch.scatter_reduce(x, 1, s.i, s.src, 'amax'), X, i=XU, src=R(4, 8))
    rcase('Tensor.scatter_reduce_', lambda s, x: LB.scatter_mean_rows_noself(x, s.i, s.src), lambda s, x: x.clone().scatter_reduce_(1, s.i, s.src, 'mean', include_self=False), X, i=XU, src=R(4, 8))
    case('split', lambda s, x: flat(*torch.split(x, [3, 5], 1)), X); case('squeeze', lambda s, x: torch.squeeze(x), R(1, 4, 1, 8))
    case('stack', lambda s, x: torch.stack([x, s.y], 1), X, y=Y); unary('swapaxes', lambda x: torch.swapaxes(x, 0, 1)); unary('swapdims', lambda x: torch.swapdims(x, 0, 1))
    unary('t', torch.t); unary('t_copy', torch.t_copy); case('take', lambda s, x: torch.take(x, s.i), X, i=torch.tensor([[0, 31], [7, 12]]))
    case('take_along_dim', lambda s, x: torch.take_along_dim(x, s.i, 1), X, i=XU[:, :3])
    case('tensor_split', lambda s, x: flat(*torch.tensor_split(x, [2, 5], 1)), X); case('tile', lambda s, x: torch.tile(x, (2, 1)), X)
    unary('transpose', lambda x: torch.transpose(x, 0, 1)); unary('transpose_copy', lambda x: torch.transpose_copy(x, 0, 1))
    case('unbind', lambda s, x: flat(*torch.unbind(x, 1)), X); rcase('unbind_copy', lambda s, x: flat(*torch.unbind(x, 0)), lambda s, x: flat(*torch.unbind_copy(x, 0)), X)
    rcase('unravel_index', lambda s, x: flat(torch.floor(s.fi / 8), s.fi - 8 * torch.floor(s.fi / 8)) + x[0, 0] * 0, lambda s, x: flat(*torch.unravel_index(s.i, (4, 8))) + x[0, 0] * 0, X, i=torch.tensor([5, 13, 31]), fi=torch.tensor([5., 13., 31.]))
    unary('unsqueeze', lambda x: torch.unsqueeze(x, 1)); unary('unsqueeze_copy', lambda x: torch.unsqueeze_copy(x, 0))
    case('vsplit', lambda s, x: flat(*torch.vsplit(x, 2)), X); rcase('view_copy', lambda s, x: x.reshape(2, 16), lambda s, x: torch.view_copy(x, (2, 16)), X)
    case('where', lambda s, x: torch.where(s.m, x, s.y), X, m=U(4, 8) > 0.5, y=Y)
    # ================= random sampling (one draw pinned under seed 0; the reference under the same seed) =================
    p_b = U(4, 8); rcase('bernoulli', lambda s, x: s.draw + x, seeded(lambda s, x: torch.bernoulli(s.p) + x), X, p=p_b, draw=(lambda: (torch.manual_seed(0), torch.bernoulli(p_b))[1])())
    p_m = U(4, 8); rcase('multinomial', lambda s, x: s.draw + x[:, :3] * 0, seeded(lambda s, x: torch.multinomial(s.p, 3, replacement=True).float() + x[:, :3] * 0), X, p=p_m, draw=(lambda: (torch.manual_seed(0), torch.multinomial(p_m, 3, replacement=True).float())[1])())
    rcase('normal', lambda s, x: x + 0.5 * s.z, seeded(lambda s, x: torch.normal(x, 0.5)), X, z=(lambda: (torch.manual_seed(0), torch.normal(torch.zeros(4, 8), 1.0))[1])())
    r_ = U(4, 8) * 3; rcase('poisson', lambda s, x: s.draw + x, seeded(lambda s, x: torch.poisson(s.r) + x), X, r=r_, draw=(lambda: (torch.manual_seed(0), torch.poisson(r_))[1])())
    def pinned(fn_):   # the genuine in-place draw under seed 0, as a constant of the case
        torch.manual_seed(0); t = X.clone(); fn_(t); return t
    for n_, fn_ in [('bernoulli_', lambda t: t.bernoulli_(0.5)), ('normal_', lambda t: t.normal_()), ('uniform_', lambda t: t.uniform_()), ('cauchy_', lambda t: t.cauchy_()), ('exponential_', lambda t: t.exponential_()), ('geometric_', lambda t: t.geometric_(0.5)), ('log_normal_', lambda t: t.log_normal_()), ('random_', lambda t: t.random_(0, 10))]:
        rcase('Tensor.' + n_, lambda s, x: s.draw + x * 0, seeded((lambda fn_: lambda s, x: (lambda t: (fn_(t), t)[1])(x.clone()))(fn_)), X, draw=pinned(fn_))
    # ================= pointwise ops =================
    rcase('acos', lambda s, x: LB.acos(x), lambda s, x: torch.acos(x), U(4, 8) * 2 - 1); rcase('acos_', lambda s, x: LB.acos(x), lambda s, x: x.clone().acos_(), U(4, 8) * 2 - 1); rcase('arccos', lambda s, x: LB.acos(x), lambda s, x: torch.arccos(x), U(4, 8) * 2 - 1); rcase('arccos_', lambda s, x: LB.acos(x), lambda s, x: x.clone().arccos_(), U(4, 8) * 2 - 1)
    rcase('acosh', lambda s, x: LB.acosh(x), lambda s, x: torch.acosh(x), XP + 1); rcase('acosh_', lambda s, x: LB.acosh(x), lambda s, x: x.clone().acosh_(), XP + 1); rcase('arccosh', lambda s, x: LB.acosh(x), lambda s, x: torch.arccosh(x), XP + 1); rcase('arccosh_', lambda s, x: LB.acosh(x), lambda s, x: x.clone().arccosh_(), XP + 1)
    binary('add', lambda x, y: torch.add(x, y, alpha=2.0))
    case('addcdiv', lambda s, x: torch.addcdiv(x, s.a, s.b, value=0.5), X, a=Y, b=XP); case('addcmul', lambda s, x: torch.addcmul(x, s.a, s.b, value=0.5), X, a=Y, b=X2)
    rcase('asin', lambda s, x: LB.asin(x), lambda s, x: torch.asin(x), U(4, 8) * 2 - 1); rcase('asin_', lambda s, x: LB.asin(x), lambda s, x: x.clone().asin_(), U(4, 8) * 2 - 1); rcase('arcsin', lambda s, x: LB.asin(x), lambda s, x: torch.arcsin(x), U(4, 8) * 2 - 1); rcase('arcsin_', lambda s, x: LB.asin(x), lambda s, x: x.clone().arcsin_(), U(4, 8) * 2 - 1)
    rcase('asinh', lambda s, x: LB.asinh(x), lambda s, x: torch.asinh(x), X); rcase('asinh_', lambda s, x: LB.asinh(x), lambda s, x: x.clone().asinh_(), X); rcase('arcsinh', lambda s, x: LB.asinh(x), lambda s, x: torch.arcsinh(x), X); rcase('arcsinh_', lambda s, x: LB.asinh(x), lambda s, x: x.clone().arcsinh_(), X)
    unary('atan', torch.atan); inplace('atan_', lambda t: t.atan_()); unary('arctan', torch.arctan); inplace('arctan_', lambda t: t.arctan_())
    rcase('atanh', lambda s, x: LB.atanh(x), lambda s, x: torch.atanh(x), U(4, 8) * 1.8 - 0.9); rcase('atanh_', lambda s, x: LB.atanh(x), lambda s, x: x.clone().atanh_(), U(4, 8) * 1.8 - 0.9); rcase('arctanh', lambda s, x: LB.atanh(x), lambda s, x: torch.arctanh(x), U(4, 8) * 1.8 - 0.9); rcase('arctanh_', lambda s, x: LB.atanh(x), lambda s, x: x.clone().arctanh_(), U(4, 8) * 1.8 - 0.9)
    rcase('atan2', lambda s, x: LB.atan2(x, s.y), lambda s, x: torch.atan2(x, s.y), X, y=Y); rcase('arctan2', lambda s, x: LB.atan2(x, s.y), lambda s, x: torch.arctan2(x, s.y), X, y=Y)
    case('bitwise_not', lambda s, x: f(torch.bitwise_not(s.a)) + x * 0, X, a=XI); case('bitwise_and', lambda s, x: f(torch.bitwise_and(s.a, s.b)) + x * 0, X, a=XI, b=XU)
    case('bitwise_or', lambda s, x: f(torch.bitwise_or(s.a, s.b)) + x * 0, X, a=XI, b=XU); case('bitwise_xor', lambda s, x: f(torch.bitwise_xor(s.a, s.b)) + x * 0, X, a=XI, b=XU)
    case('bitwise_left_shift', lambda s, x: f(torch.bitwise_left_shift(s.a, s.b)) + x * 0, X, a=XU, b=XU % 4); case('bitwise_right_shift', lambda s, x: f(torch.bitwise_right_shift(s.a, s.b)) + x * 0, X, a=XU * 8, b=XU % 4)
    rcase('ceil', lambda s, x: LB.ceil(x), lambda s, x: torch.ceil(x), X * 3); rcase('ceil_', lambda s, x: LB.ceil(x), lambda s, x: x.clone().ceil_(), X * 3)
    unary('clamp', lambda x: torch.clamp(x, -0.5, 0.5)); case('min', lambda s, x: torch.min(x, s.y), X, y=Y); case('max', lambda s, x: torch.max(x, s.y), X, y=Y)
    inplace('clamp_', lambda t: t.clamp_(-0.5, 0.5)); inplace('clamp_max_', lambda t: t.clamp_max_(0.5)); inplace('clamp_min_', lambda t: t.clamp_min_(-0.5))
    unary('clip', lambda x: torch.clip(x, -0.5, 0.5)); inplace('clip_', lambda t: t.clip_(-0.5, 0.5))
    unary('conj_physical', torch.conj_physical); inplace('conj_physical_', lambda t: t.conj_physical_())
    rcase('copysign', lambda s, x: x.abs() * torch.where(s.y < 0, -torch.ones_like(x), torch.ones_like(x)), lambda s, x: torch.copysign(x, s.y), X, y=Y); unary('cos', torch.cos); inplace('cos_', lambda t: t.cos_()); rcase('cosh', lambda s, x: LB.cosh(x), lambda s, x: torch.cosh(x), X); rcase('cosh_', lambda s, x: LB.cosh(x), lambda s, x: x.clone().cosh_(), X)
    unary('deg2rad', torch.deg2rad, X * 90); inplace('deg2rad_', lambda t: t.deg2rad_(), X * 90)
    binary('div', torch.div, y=XP); binary('divide', lambda x, y: torch.divide(x, y, rounding_mode='floor'), y=XP)
    rcase('digamma', lambda s, x: LB.digamma(x), lambda s, x: torch.digamma(x), XP); unary('erf', torch.erf); inplace('erf_', lambda t: t.erf_()); rcase('erfc', lambda s, x: 1 - torch.erf(x), lambda s, x: torch.erfc(x), X); rcase('erfc_', lambda s, x: 1 - torch.erf(x), lambda s, x: x.clone().erfc_(), X)
    rcase('erfinv', lambda s, x: LB.erfinv(x), lambda s, x: torch.erfinv(x), U(4, 8) * 1.8 - 0.9)
    unary('exp', torch.exp); inplace('exp_', lambda t: t.exp_()); rcase('exp2', lambda s, x: LB.exp2(x), lambda s, x: torch.exp2(x), X); rcase('exp2_', lambda s, x: LB.exp2(x), lambda s, x: x.clone().exp2_(), X); unary('expm1', torch.expm1); inplace('expm1_', lambda t: t.expm1_())
    rcase('fake_quantize_per_channel_affine', lambda s, x: (torch.clamp(torch.round(x / s.sc) + s.zpf, 0, 255) - s.zpf) * s.sc, lambda s, x: torch.fake_quantize_per_channel_affine(x, s.sc, s.zp, 1, 0, 255), X, sc=torch.full((8,), 0.01), zp=torch.zeros(8, dtype=torch.int32), zpf=torch.zeros(8))
    unary('fake_quantize_per_tensor_affine', lambda x: torch.fake_quantize_per_tensor_affine(x, 0.01, 0, 0, 255))
    inplace('fill_', lambda t: t.fill_(0.5)); unary('fix', torch.fix, X * 3); unary('trunc', torch.trunc, X * 3); inplace('fix_', lambda t: t.fix_(), X * 3); inplace('trunc_', lambda t: t.trunc_(), X * 3)
    rcase('float_power', lambda s, x: LB.powf(x, s.y), lambda s, x: torch.float_power(x, s.y).float(), XP, y=XU.float())
    unary('floor', torch.floor, X * 3); inplace('floor_', lambda t: t.floor_(), X * 3); binary('floor_divide', torch.floor_divide, X * 3, y=XP); binary('fmod', torch.fmod, X * 3, y=XP)
    unary('frac', torch.frac, X * 3); inplace('frac_', lambda t: t.frac_(), X * 3)
    rcase('frexp', lambda s, x: flat(*LB.frexp_f(x)), lambda s, x: flat(*[t.float() for t in torch.frexp(x)]), X)
    case('gradient', lambda s, x: flat(*torch.gradient(x, spacing=0.5)), X)
    rcase('ldexp', lambda s, x: x * LB.exp2(s.ef), lambda s, x: torch.ldexp(x, s.e), X, e=XU, ef=XU.float()); rcase('ldexp_', lambda s, x: x * LB.exp2(s.ef), lambda s, x: x.clone().ldexp_(s.e), X, e=XU, ef=XU.float())
    case('lerp', lambda s, x: torch.lerp(x, s.y, 0.3), X, y=Y); rcase('lgamma', lambda s, x: LB.lgamma(x), lambda s, x: torch.lgamma(x), XP)
    unary('log', torch.log, XP); inplace('log_', lambda t: t.log_(), XP); unary('log10', torch.log10, XP); inplace('log10_', lambda t: t.log10_(), XP)
    unary('log1p', torch.log1p, XP); inplace('log1p_', lambda t: t.log1p_(), XP); rcase('log2', lambda s, x: LB.log2(x), lambda s, x: torch.log2(x), XP); rcase('log2_', lambda s, x: LB.log2(x), lambda s, x: x.clone().log2_(), XP)
    binary('logaddexp', torch.logaddexp); rcase('logaddexp2', lambda s, x: LB.log2(LB.exp2(x) + LB.exp2(s.y)), lambda s, x: torch.logaddexp2(x, s.y), X, y=Y)
    case('logical_and', lambda s, x: f(torch.logical_and(x > 0, s.y > 0)), X, y=Y); case('logical_not', lambda s, x: f(torch.logical_not(x > 0)), X)
    case('logical_or', lambda s, x: f(torch.logical_or(x > 0, s.y > 0)), X, y=Y); case('logical_xor', lambda s, x: f(torch.logical_xor(x > 0, s.y > 0)), X, y=Y)
    unary('logit', lambda x: torch.logit(x, eps=1e-6), U(4, 8)); inplace('logit_', lambda t: t.logit_(1e-6), U(4, 8))
    rcase('hypot', lambda s, x: LB.hypot(x, s.y), lambda s, x: torch.hypot(x, s.y), X, y=Y); rcase('i0', lambda s, x: LB.i0(x), lambda s, x: torch.i0(x), X); rcase('i0_', lambda s, x: LB.i0(x), lambda s, x: x.clone().i0_(), X)
    rcase('igamma', lambda s, x: LB.gammainc(x, s.y), lambda s, x: torch.igamma(x, s.y), XP, y=XP * 2); rcase('igammac', lambda s, x: 1 - LB.gammainc(x, s.y), lambda s, x: torch.igammac(x, s.y), XP, y=XP * 2)
    binary('mul', torch.mul); binary('multiply', torch.multiply); rcase('mvlgamma', lambda s, x: 0.5 * math.log(math.pi) + LB.lgamma(x) + LB.lgamma(x - 0.5), lambda s, x: torch.mvlgamma(x, 2), XP + 1)
    unary('nan_to_num', lambda x: torch.nan_to_num(x / (x.abs() > 0.3).float(), nan=0.0, posinf=1e3, neginf=-1e3)); inplace('nan_to_num_', lambda t: t.nan_to_num_(nan=0.0, posinf=9.0, neginf=-9.0))
    unary('neg', torch.neg); inplace('neg_', lambda t: t.neg_()); unary('negative', torch.negative); inplace('negative_', lambda t: t.negative_())
    rcase('nextafter', lambda s, x: LB.nextafter(x, s.y), lambda s, x: torch.nextafter(x, s.y), X, y=Y); rcase('polygamma', lambda s, x: LB.trigamma(x), lambda s, x: torch.polygamma(1, x), XP); unary('positive', torch.positive)
    binary('pow', torch.pow, XP, XU.float() / 2); unary('rad2deg', torch.rad2deg); inplace('rad2deg_', lambda t: t.rad2deg_())
    unary('reciprocal', torch.reciprocal, XP); inplace('reciprocal_', lambda t: t.reciprocal_(), XP); binary('remainder', torch.remainder, X * 3, y=XP)
    unary('round', torch.round, X * 3); inplace('round_', lambda t: t.round_(), X * 3); unary('round_decimals', lambda x: torch.round(x, decimals=1))
    unary('rsqrt', torch.rsqrt, XP); inplace('rsqrt_', lambda t: t.rsqrt_(), XP); unary('sigmoid', torch.sigmoid); inplace('sigmoid_', lambda t: t.sigmoid_())
    unary('sign', torch.sign); unary('sgn', torch.sgn); rcase('signbit', lambda s, x: f(x < 0), lambda s, x: f(torch.signbit(x)), X)
    unary('sin', torch.sin); inplace('sin_', lambda t: t.sin_()); unary('sinc', torch.sinc); inplace('sinc_', lambda t: t.sinc_()); rcase('sinh', lambda s, x: LB.sinh(x), lambda s, x: torch.sinh(x), X); rcase('sinh_', lambda s, x: LB.sinh(x), lambda s, x: x.clone().sinh_(), X)
    unary('softmax', lambda x: torch.softmax(x, 1)); unary('nn.functional.softmax', lambda x: NF.softmax(x, 0))
    unary('sqrt', torch.sqrt, XP); inplace('sqrt_', lambda t: t.sqrt_(), XP); unary('square', torch.square); inplace('square_', lambda t: t.square_())
    binary('sub', lambda x, y: torch.sub(x, y, alpha=0.5)); binary('subtract', torch.subtract)
    rcase('tan', lambda s, x: LB.tan(x), lambda s, x: torch.tan(x), X); rcase('tan_', lambda s, x: LB.tan(x), lambda s, x: x.clone().tan_(), X); unary('tanh', torch.tanh); inplace('tanh_', lambda t: t.tanh_())
    binary('true_divide', torch.true_divide, y=XP); binary('xlogy', torch.xlogy, y=XP); case('xlogy_', lambda s, x: x.clone().xlogy_(s.y), X, y=XP); inplace('zero_', lambda t: t.zero_())
    # ================= reduction ops =================
    unary('argmax', lambda x: f(torch.argmax(x, 1))); unary('argmin', lambda x: f(torch.argmin(x, 0)))
    unary('amax', lambda x: torch.amax(x, 1)); unary('amin', lambda x: torch.amin(x, 0)); unary('aminmax', lambda x: flat(*torch.aminmax(x, dim=1)))
    unary('all', lambda x: f(torch.all(x > -2, 1))); unary('any', lambda x: f(torch.any(x > 1, 1)))
    rcase('dist', lambda s, x: ((x - s.y).abs() ** 3).sum().pow(1 / 3).reshape(1), lambda s, x: torch.dist(x, s.y, 3).reshape(1), X, y=Y); unary('logsumexp', lambda x: torch.logsumexp(x, 1))
    unary('mean', lambda x: torch.mean(x, 1)); unary('nanmean', lambda x: torch.nanmean(torch.where(x.abs() < 0.2, torch.full_like(x, float('nan')), x), 1))
    rcase('median', lambda s, x: LB.quantile_rank(x, 0.5, 'lower'), lambda s, x: torch.median(x, 1).values, X)
    rcase('nanmedian', lambda s, x: LB.quantile_rank(x, 0.5, 'lower'), lambda s, x: torch.nanmedian(x, 1).values, X)
    rcase('mode', lambda s, x: LB.mode_rows(x), lambda s, x: torch.mode(x, 1).values.float(), XU.float())
    unary('norm', lambda x: torch.norm(x, dim=1)); unary('norm_except_dim', lambda x: torch.norm_except_dim(x, 2, 0).reshape(-1))
    rcase('nuclear_norm', lambda s, x: LB.nuclear_norm_4x4(x), lambda s, x: torch.nuclear_norm(x).reshape(1), R(4, 4))
    unary('nansum', lambda x: torch.nansum(torch.where(x.abs() < 0.2, torch.full_like(x, float('nan')), x), 1)); unary('prod', lambda x: torch.prod(x, 1))
    rcase('quantile', lambda s, x: LB.quantile_rank(x, 0.3, 'linear'), lambda s, x: torch.quantile(x, 0.3, dim=1), X)
    rcase('nanquantile', lambda s, x: LB.quantile_rank(x, 0.3, 'linear'), lambda s, x: torch.nanquantile(x, 0.3, dim=1), X)
    unary('std', lambda x: torch.std(x, 1)); unary('std_mean', lambda x: flat(*torch.std_mean(x, 1))); unary('sum', lambda x: torch.sum(x, 0))
    rcase('unique', lambda s, x: LB.sort_rows(x[s.first][None])[0], lambda s, x: torch.unique(x), torch.tensor([3., 1., 2., 3., 0., 1., 5., 2.]), first=torch.tensor([0, 1, 2, 4, 6]))
    rcase('unique_consecutive', lambda s, x: LB.unique_consecutive_static(x, s.keep), lambda s, x: torch.unique_consecutive(x), torch.tensor([1., 1., 2., 2., 3., 1., 1., 2.]), keep=torch.tensor([0, 2, 4, 5, 7]))
    unary('var', lambda x: torch.var(x, 1)); unary('var_mean', lambda x: flat(*torch.var_mean(x, 0))); unary('count_nonzero', lambda x: f(torch.count_nonzero(x > 0, 1)))
    # ================= comparison ops =================
    rcase('allclose', lambda s, x: x * ((x - s.y).abs() <= 10.0 + 1e-5 * s.y.abs()).all().float(), lambda s, x: x * float(torch.allclose(x, s.y, atol=10.0)), X, y=Y)
    rcase('argsort', lambda s, x: LB.rank_rows(x), lambda s, x: LB.inv_perm(torch.argsort(x, 1)).float(), X)   # rank of every element = the inverse of argsort
    binary('eq', lambda x, y: f(torch.eq(x, y)), y=X.clone().masked_fill(U(4, 8) > 0.5, 0.0)); rcase('equal', lambda s, x: x * (x == s.y).all().float(), lambda s, x: x * float(torch.equal(x, s.y)), X, y=X.clone())
    binary('ge', lambda x, y: f(torch.ge(x, y))); binary('greater_equal', lambda x, y: f(torch.greater_equal(x, y))); binary('gt', lambda x, y: f(torch.gt(x, y))); binary('greater', lambda x, y: f(torch.greater(x, y)))
    binary('isclose', lambda x, y: f(torch.isclose(x, y, atol=0.5)))
    rcase('isfinite', lambda s, x: f((x / (x.abs() > 0.3).float()).abs() < float('inf')), lambda s, x: f(torch.isfinite(x / (x.abs() > 0.3).float())), X)
    case('isin', lambda s, x: f(torch.isin(s.a, s.b)) + x * 0, X, a=XU, b=torch.tensor([1, 3, 5]))
    unary('isinf', lambda x: f(torch.isinf(x / (x.abs() > 0.3).float()))); unary('isposinf', lambda x: f(torch.isposinf(x / (x.abs() > 0.3).float()))); unary('isneginf', lambda x: f(torch.isneginf(x / (x.abs() > 0.3).float())))
    unary('isnan', lambda x: f(torch.isnan(torch.where(x.abs() < 0.2, torch.full_like(x, float('nan')), x)))); unary('isreal', lambda x: f(torch.isreal(x)))
    rcase('kthvalue', lambda s, x: LB.quantile_rank(x, 2 / 7, 'lower'), lambda s, x: torch.kthvalue(x, 3, 1).values, X)   # k = 3 of 8: rank 2
    binary('le', lambda x, y: f(torch.le(x, y))); binary('less_equal', lambda x, y: f(torch.less_equal(x, y))); binary('lt', lambda x, y: f(torch.lt(x, y))); binary('less', lambda x, y: f(torch.less(x, y)))
    binary('maximum', torch.maximum); binary('minimum', torch.minimum); binary('fmax', torch.fmax); binary('fmin', torch.fmin)
    binary('ne', lambda x, y: f(torch.ne(x, y))); binary('not_equal', lambda x, y: f(torch.not_equal(x, y)))
    rcase('sort', lambda s, x: LB.sort_rows(x), lambda s, x: torch.sort(x, 1).values, X)
    rcase('topk', lambda s, x: LB.sort_rows(x, descending=True)[:, :3], lambda s, x: torch.topk(x, 3, 1).values, X)
    rcase('msort', lambda s, x: LB.sort_rows(x.t()).t(), lambda s, x: torch.msort(x), X)
    # ================= spectral ops =================
    rcase('stft', lambda s, x: LB.stft_mat(x, s.win, s.dft, 16, 4), lambda s, x: torch.view_as_real(torch.stft(x, 16, 4, window=s.win, return_complex=True)).permute(0, 3, 1, 2).reshape(2, -1), R(2, 64), win=torch.hann_window(16), dft=LB.dft_matrix(16))
    rcase('istft', lambda s, x: LB.istft_mat(x, s.win, s.idft, 16, 4, 64), lambda s, x: torch.istft(torch.complex(x[:, :9 * 17].reshape(2, 9, 17), x[:, 9 * 17:].reshape(2, 9, 17)), 16, 4, window=s.win, length=64), torch.cat([LB.stft_re_im(R(2, 64), 16, 4)], 1), win=torch.hann_window(16), idft=LB.idft_matrix(16), _atol=1e-3)
    rcase('bartlett_window', lambda s, x: x * LB.bartlett_window(8), lambda s, x: x * torch.bartlett_window(8), X)
    rcase('blackman_window', lambda s, x: x * LB.cosine_window(8, [0.42, 0.5, 0.08]), lambda s, x: x * torch.blackman_window(8), X)
    rcase('hamming_window', lambda s, x: x * LB.cosine_window(8, [0.54, 0.46]), lambda s, x: x * torch.hamming_window(8), X)
    rcase('hann_window', lambda s, x: x * LB.cosine_window(8, [0.5, 0.5]), lambda s, x: x * torch.hann_window(8), X)
    rcase('kaiser_window', lambda s, x: x * LB.kaiser_window(8, 8.0), lambda s, x: x * torch.kaiser_window(8, True, 8.0), X)
    # ================= other operations =================
    rcase('adaptive_avg_pool1d', lambda s, x: x.reshape(4, 4, 2).mean(-1), lambda s, x: torch.adaptive_avg_pool1d(x, 4), X); rcase('adaptive_max_pool1d', lambda s, x: x.reshape(4, 4, 2).amax(-1), lambda s, x: torch.adaptive_max_pool1d(x, 4)[0], X)
    case('affine_grid_generator', lambda s, x: torch.affine_grid_generator(s.th, [1, 1, 4, 4], False).reshape(-1) + x.reshape(-1)[:32] * 0, X, th=torch.tensor([[[1.0, 0.2, 0.1], [-0.1, 0.9, 0.0]]]))
    rcase('alpha_dropout', lambda s, x: s.a * x + s.b, seeded(lambda s, x: torch.alpha_dropout(x, 0.5, True)), X, **LB.alpha_dropout_affine(X, 0.5)); rcase('alpha_dropout_', lambda s, x: s.a * x + s.b, seeded(lambda s, x: torch.alpha_dropout_(x.clone(), 0.5, True)), X, **LB.alpha_dropout_affine(X, 0.5))
    case('atleast_1d', lambda s, x: torch.atleast_1d(x) * s.two, torch.tensor(1.5), two=torch.tensor([2.0, 2.0])); case('atleast_2d', lambda s, x: torch.atleast_2d(x), R(8)); case('atleast_3d', lambda s, x: torch.atleast_3d(x), X)
    rcase('avg_pool1d', lambda s, x: x.reshape(4, 4, 2).mean(-1), lambda s, x: torch.avg_pool1d(x, 2), X)
    case('bilinear', lambda s, x: torch.bilinear(x, s.y, s.w, s.b), X, y=Y, w=R(3, 8, 8) * 0.1, b=R(3))
    rcase('bincount', lambda s, x: LB.onehot(s.i, 8).sum(0) + x[0, 0] * 0, lambda s, x: torch.bincount(s.i, minlength=8).float() + x[0, 0] * 0, X, i=XU.reshape(-1))
    p_ = U(4, 8); rcase('binomial', lambda s, x: s.draw + x, seeded(lambda s, x: torch.binomial(s.cnt, s.p) + x), X, cnt=torch.full((4, 8), 10.0), p=p_, draw=(lambda: (torch.manual_seed(0), torch.binomial(torch.full((4, 8), 10.0), p_))[1])())
    case('block_diag', lambda s, x: torch.block_diag(x[:2, :2], s.b), X, b=R(3, 3)); case('broadcast_tensors', lambda s, x: flat(*torch.broadcast_tensors(x[:1], s.c)), X, c=R(4, 1))
    unary('broadcast_to', lambda x: torch.broadcast_to(x[:1], (4, 8))); case('broadcast_shapes', lambda s, x: x.reshape(torch.broadcast_shapes((4, 1), (1, 8))), X)
    case('bucketize', lambda s, x: f(torch.bucketize(x, s.b)), X, b=torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0]))
    case('cartesian_prod', lambda s, x: torch.cartesian_prod(x[0, :3], s.b), X, b=R(2))
    rcase('cdist', lambda s, x: LB.cdist(x, s.y), lambda s, x: torch.cdist(x, s.y), X, y=R(5, 8))
    inplace('celu_', lambda t: torch.celu_(t)); unary('channel_shuffle', lambda x: torch.channel_shuffle(x, 2), R(1, 4, 3, 3))
    unary('clone', torch.clone); rcase('combinations', lambda s, x: LB.combinations_f(x[0, :5]), lambda s, x: torch.combinations(x[0, :5], 2), X)
    case('conv1d', lambda s, x: torch.conv1d(x.unsqueeze(0), s.w, s.b, padding=1).squeeze(0), X, w=R(3, 4, 3), b=R(3))
    case('conv3d', lambda s, x: torch.conv3d(x, s.w, padding=1), R(1, 2, 4, 4, 4), w=R(3, 2, 3, 3, 3))
    rcase('conv_tbc', lambda s, x: torch.conv1d(x.permute(1, 2, 0), s.w.permute(2, 1, 0), s.b, padding=1).permute(2, 0, 1), lambda s, x: torch.conv_tbc(x, s.w, s.b, 1), R(8, 1, 4), w=R(3, 4, 3), b=R(3))
    case('conv_transpose1d', lambda s, x: torch.conv_transpose1d(x.unsqueeze(0), s.w, stride=2).squeeze(0), X, w=R(4, 3, 3))
    case('conv_transpose2d', lambda s, x: torch.conv_transpose2d(x, s.w, stride=2), R(1, 2, 4, 4), w=R(2, 3, 3, 3))
    case('conv_transpose3d', lambda s, x: torch.conv_transpose3d(x, s.w), R(1, 2, 3, 3, 3), w=R(2, 2, 2, 2, 2))
    case('convolution', lambda s, x: torch.convolution(x, s.w, s.b, [1, 1], [1, 1], [1, 1], False, [0, 0], 1), R(1, 2, 4, 4), w=R(3, 2, 3, 3), b=R(3))
    rcase('corrcoef', lambda s, x: LB.corrcoef_f(x), lambda s, x: torch.corrcoef(x), X); case('cosine_embedding_loss', lambda s, x: torch.cosine_embedding_loss(x, s.y, s.t, 0.0, 1).reshape(1), X, y=Y, t=torch.tensor([1., -1., 1., -1.]))
    binary('cosine_similarity', lambda x, y: torch.cosine_similarity(x, y, 1)); rcase('cov', lambda s, x: LB.cov_f(x), lambda s, x: torch.cov(x), X)
    case('cross', lambda s, x: torch.cross(x, s.y, dim=1), R(4, 3), y=R(4, 3))
    rcase('ctc_loss', lambda s, x: LB.ctc_loss(x.log_softmax(1), [1, 2]), lambda s, x: torch.ctc_loss(x.log_softmax(1).unsqueeze(1), s.tg, s.il, s.tl, 0, 2).reshape(1), R(6, 4), tg=torch.tensor([[1, 2]]), il=torch.tensor([6]), tl=torch.tensor([2]))
    rcase('cummax', lambda s, x: LB.cummax_rows(x), lambda s, x: torch.cummax(x, 1).values, X); rcase('cummin', lambda s, x: -LB.cummax_rows(-x), lambda s, x: torch.cummin(x, 1).values, X)
    rcase('cumprod', lambda s, x: LB.cumprod_rows(x), lambda s, x: torch.cumprod(x, 1), XP); rcase('cumsum', lambda s, x: x @ s.T, lambda s, x: torch.cumsum(x, 1), X, T=torch.triu(torch.ones(8, 8)))
    inplace('detach_', lambda t: t.detach_()); unary('diag', lambda x: torch.diag(x[0])); unary('diag_embed', lambda x: torch.diag_embed(x[:, :4])); unary('diagflat', lambda x: torch.diagflat(x[0, :4]))
    unary('diff', lambda x: torch.diff(x, dim=1)); rcase('dropout_', lambda s, x: x * s.mask, seeded(lambda s, x: torch.dropout_(x.clone(), 0.5, True)), X, mask=(lambda: (torch.manual_seed(0), torch.dropout_(torch.ones(4, 8), 0.5, True))[1])())
    case('einsum', lambda s, x: torch.einsum('ij,jk->ik', x, s.y), X, y=R(8, 3))
    case('embedding', lambda s, x: torch.embedding(x, s.i), X, i=torch.tensor([[3, 1], [0, 2]]))
    rcase('embedding_renorm_', lambda s, x: LB.embedding_renorm(x, s.i, 1.0, 2.0), lambda s, x: torch.embedding_renorm_(x.clone(), s.i, 1.0, 2.0), X, i=torch.tensor([0, 2]))
    case('feature_alpha_dropout', seeded(lambda s, x: torch.feature_alpha_dropout(x, 0.5, True)), R(2, 4, 8)); case('feature_alpha_dropout_', seeded(lambda s, x: torch.feature_alpha_dropout_(x.clone(), 0.5, True)), R(2, 4, 8))
    case('feature_dropout', seeded(lambda s, x: torch.feature_dropout(x, 0.5, True)), R(2, 4, 8)); case('feature_dropout_', seeded(lambda s, x: torch.feature_dropout_(x.clone(), 0.5, True)), R(2, 4, 8))
    unary('flatten', torch.flatten); unary('flip', lambda x: torch.flip(x, [0, 1])); unary('fliplr', torch.fliplr); unary('flipud', torch.flipud)
    rcase('gcd', lambda s, x: LB.gcd_f(s.af, s.bf) + x * 0, lambda s, x: f(torch.gcd(s.a, s.b)) + x * 0, X, a=XU + 1, b=XU * 2 + 2, af=(XU + 1).float(), bf=(XU * 2 + 2).float()); rcase('gcd_', lambda s, x: LB.gcd_f(s.af, s.bf) + x * 0, lambda s, x: f(s.a.clone().gcd_(s.b)) + x * 0, X, a=XU + 1, b=XU * 2 + 2, af=(XU + 1).float(), bf=(XU * 2 + 2).float())
    case('grid_sampler_2d', lambda s, x: torch.grid_sampler_2d(x, s.g, 0, 0, False), R(1, 2, 4, 4), g=U(1, 3, 3, 2) * 1.6 - 0.8)
    rcase('grid_sampler_3d', lambda s, x: LB.grid_sample_3d(x, s.g), lambda s, x: torch.grid_sampler_3d(x, s.g, 0, 0, False), R(1, 2, 3, 3, 3), g=U(1, 2, 2, 2, 3) * 1.6 - 0.8)
    case('group_norm', lambda s, x: torch.group_norm(x, 2, s.w, s.b), R(2, 4, 3), w=R(4), b=R(4))
    case('gru', lambda s, x: flat(*torch.gru(x, s.h, [s.wih, s.whh, s.bih, s.bhh], True, 1, 0.0, False, False, False)), R(5, 2, 4), h=R(1, 2, 3), wih=R(9, 4), whh=R(9, 3), bih=R(9), bhh=R(9))
    case('gru_cell', lambda s, x: torch.gru_cell(x, s.h, s.wih, s.whh, s.bih, s.bhh), R(2, 4), h=R(2, 3), wih=R(9, 4), whh=R(9, 3), bih=R(9), bhh=R(9))
    unary('hardshrink', lambda x: torch.hardshrink(x, 0.5)); case('hinge_embedding_loss', lambda s, x: torch.hinge_embedding_loss(x, s.t, 1.0, 1).reshape(1), X, t=torch.where(U(4, 8) > 0.5, 1.0, -1.0))
    rcase('histc', lambda s, x: LB.histc(x, 5, -2.0, 2.0), lambda s, x: torch.histc(x, 5, -2.0, 2.0), X)
    rcase('histogram', lambda s, x: LB.histc(x, 5, -2.0, 2.0), lambda s, x: torch.histogram(x, 5, range=(-2.0, 2.0)).hist, X)
    rcase('histogramdd', lambda s, x: LB.hist2d(x, 3, (-2.0, 2.0)), lambda s, x: torch.histogramdd(x, [3, 3], range=[-2.0, 2.0, -2.0, 2.0]).hist, R(16, 2))
    case('instance_norm', lambda s, x: torch.instance_norm(x, None, None, None, None, True, 0.1, 1e-5, False), R(2, 4, 8))
    case('kl_div', lambda s, x: torch.kl_div(x.log_softmax(1), s.t, 1).reshape(1), X, t=U(4, 8).softmax(1))
    case('kron', lambda s, x: torch.kron(x[:2, :2], s.b), X, b=R(2, 3))
    rcase('lcm', lambda s, x: s.af * s.bf / LB.gcd_f(s.af, s.bf) + x * 0, lambda s, x: f(torch.lcm(s.a, s.b)) + x * 0, X, a=XU + 1, b=XU % 3 + 1, af=(XU + 1).float(), bf=(XU % 3 + 1).float()); rcase('lcm_', lambda s, x: s.af * s.bf / LB.gcd_f(s.af, s.bf) + x * 0, lambda s, x: f(s.a.clone().lcm_(s.b)) + x * 0, X, a=XU + 1, b=XU % 3 + 1, af=(XU + 1).float(), bf=(XU % 3 + 1).float())
    rcase('logcumsumexp', lambda s, x: torch.log((torch.exp(x - x.amax(1, keepdim=True)) @ s.T)) + x.amax(1, keepdim=True), lambda s, x: torch.logcumsumexp(x, 1), X, T=torch.triu(torch.ones(8, 8)))
    case('lstm', lambda s, x: flat(*torch.lstm(x, [s.h, s.c], [s.wih, s.whh, s.bih, s.bhh], True, 1, 0.0, False, False, False)), R(5, 2, 4), h=R(1, 2, 3), c=R(1, 2, 3), wih=R(12, 4), whh=R(12, 3), bih=R(12), bhh=R(12))
    case('lstm_cell', lambda s, x: flat(*torch.lstm_cell(x, [s.h, s.c], s.wih, s.whh, s.bih, s.bhh)), R(2, 4), h=R(2, 3), c=R(2, 3), wih=R(12, 4), whh=R(12, 3), bih=R(12), bhh=R(12))
    case('margin_ranking_loss', lambda s, x: torch.margin_ranking_loss(x, s.y, s.t, 0.1, 1).reshape(1), X, y=Y, t=torch.where(U(4, 8) > 0.5, 1.0, -1.0))
    rcase('max_pool1d', lambda s, x: x.reshape(4, 4, 2).amax(-1), lambda s, x: torch.max_pool1d(x, 2), X); unary('max_pool3d', lambda x: torch.max_pool3d(x, 2), R(1, 2, 4, 4, 4))
    case('meshgrid', lambda s, x: flat(*torch.meshgrid(x[0, :3], s.b, indexing='ij')), X, b=R(4))
    case('native_batch_norm', lambda s, x: flat(*torch.native_batch_norm(x, s.w, s.b, s.rm, s.rv, False, 0.1, 1e-5)), R(2, 4, 8), w=R(4), b=R(4), rm=R(4), rv=U(4) + 0.5)
    unary('native_channel_shuffle', lambda x: torch.native_channel_shuffle(x, 2), R(1, 4, 3, 3))
    case('native_group_norm', lambda s, x: flat(*torch.native_group_norm(x, s.w, s.b, 2, 4, 3, 2, 1e-5)), R(2, 4, 3), w=R(4), b=R(4))
    case('native_layer_norm', lambda s, x: flat(*torch.native_layer_norm(x, [8], s.w, s.b, 1e-5)), X, w=R(8), b=R(8))
    rcase('native_norm', lambda s, x: (x * x).sum().sqrt().reshape(1), lambda s, x: torch.native_norm(x.to_sparse()).reshape(1), X); binary('pairwise_distance', torch.pairwise_distance); binary('nn.PairwiseDistance', lambda x, y: torch.nn.PairwiseDistance(p=1)(x, y))
    rcase('pdist', lambda s, x: LB.pdist(x), lambda s, x: torch.pdist(x), X)
    unary('pixel_unshuffle', lambda x: torch.pixel_unshuffle(x, 2), R(1, 1, 4, 4)); unary('nn.PixelShuffle', lambda x: torch.nn.PixelShuffle(2)(x), R(1, 4, 2, 2))
    case('poisson_nll_loss', lambda s, x: torch.poisson_nll_loss(x, s.t, True, False, 1e-8, 1).reshape(1), X, t=U(4, 8) * 3)
    case('prelu', lambda s, x: torch.prelu(x, s.w), X, w=torch.tensor([0.25]))
    unary('ravel', torch.ravel); inplace('relu_', lambda t: torch.relu_(t)); unary('renorm', lambda x: torch.renorm(x, 2, 0, 1.0))
    unary('repeat_interleave', lambda x: torch.repeat_interleave(x, 2, dim=1)); rcase('resize_as_', lambda s, x: x[:2], lambda s, x: x.clone().resize_as_(s.y), X, y=R(2, 8))
    case('rms_norm', lambda s, x: torch.rms_norm(x, [8], s.w, 1e-5), X, w=R(8))
    case('rnn_relu', lambda s, x: flat(*torch.rnn_relu(x, s.h, [s.wih, s.whh, s.bih, s.bhh], True, 1, 0.0, False, False, False)), R(5, 2, 4), h=R(1, 2, 3), wih=R(3, 4), whh=R(3, 3), bih=R(3), bhh=R(3))
    case('rnn_relu_cell', lambda s, x: torch.rnn_relu_cell(x, s.h, s.wih, s.whh, s.bih, s.bhh), R(2, 4), h=R(2, 3), wih=R(3, 4), whh=R(3, 3), bih=R(3), bhh=R(3))
    case('rnn_tanh', lambda s, x: flat(*torch.rnn_tanh(x, s.h, [s.wih, s.whh, s.bih, s.bhh], True, 1, 0.0, False, False, False)), R(5, 2, 4), h=R(1, 2, 3), wih=R(3, 4), whh=R(3, 3), bih=R(3), bhh=R(3))
    case('rnn_tanh_cell', lambda s, x: torch.rnn_tanh_cell(x, s.h, s.wih, s.whh, s.bih, s.bhh), R(2, 4), h=R(2, 3), wih=R(3, 4), whh=R(3, 3), bih=R(3), bhh=R(3))
    unary('roll', lambda x: torch.roll(x, (1, -2), (0, 1))); unary('rot90', lambda x: torch.rot90(x, 1, [0, 1]))
    rcase('rrelu', lambda s, x: torch.where(x >= 0, x, x * s.slope), seeded(lambda s, x: torch.rrelu(x, 0.1, 0.3, True)), X, slope=LB.rrelu_slopes(X, 0.1, 0.3)); rcase('rrelu_', lambda s, x: torch.where(x >= 0, x, x * s.slope), seeded(lambda s, x: torch.rrelu_(x.clone(), 0.1, 0.3, True)), X, slope=LB.rrelu_slopes(X, 0.1, 0.3))
    binary('rsub', lambda x, y: torch.rsub(x, y, alpha=0.5))
    rcase('searchsorted', lambda s, x: LB.searchsorted_f(s.b, x), lambda s, x: f(torch.searchsorted(s.b, x)), X, b=torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0]))
    unary('selu', torch.selu); inplace('selu_', lambda t: torch.selu_(t))
    case('tensordot', lambda s, x: torch.tensordot(x, s.y, dims=([1], [0])), X, y=R(8, 3))
    unary('threshold', lambda x: torch.threshold(x, 0.1, -1.0)); inplace('threshold_', lambda t: torch.threshold_(t, 0.1, -1.0))
    unary('trace', lambda x: torch.trace(x[:, :4]).reshape(1)); unary('tril', lambda x: torch.tril(x, -1)); unary('triu', lambda x: torch.triu(x, 1))
    case('tril_indices', lambda s, x: s.ti + x[0, 0] * 0, X, ti=torch.tril_indices(4, 4, -1).float()); case('triu_indices', lambda s, x: s.ti + x[0, 0] * 0, X, ti=torch.triu_indices(4, 4, 1).float())
    case('triplet_margin_loss', lambda s, x: torch.triplet_margin_loss(x, s.p, s.n, 1.0, 2.0, 1e-6, False, 1).reshape(1), X, p=Y, n=X2)
    unary('unflatten', lambda x: torch.unflatten(x, 1, (2, 4))); rcase('vander', lambda s, x: torch.stack([x[0, :4] ** 2, x[0, :4], torch.ones(4)], 1), lambda s, x: torch.vander(x[0, :4], N=3), X)
    unary('resolve_conj', torch.resolve_conj); unary('resolve_neg', torch.resolve_neg)
    # ================= BLAS and LAPACK =================
    case('addbmm', lambda s, x: torch.addbmm(x[:3, :3], s.a, s.b), X, a=R(2, 3, 4), b=R(2, 4, 3)); case('addmm', lambda s, x: torch.addmm(x[:3, :3], s.a, s.b), X, a=R(3, 4), b=R(4, 3))
    rcase('addmv', lambda s, x: x[0, :3] + s.a @ s.v, lambda s, x: torch.addmv(x[0, :3], s.a, s.v), X, a=R(3, 4), v=R(4)); rcase('addmv_', lambda s, x: x[0, :3] + s.a @ s.v, lambda s, x: x[0, :3].clone().addmv_(s.a, s.v), X, a=R(3, 4), v=R(4))
    case('addr', lambda s, x: torch.addr(x[:3, :4], s.a, s.b), X, a=R(3), b=R(4)); case('baddbmm', lambda s, x: torch.baddbmm(x[:2, :3].unsqueeze(0).expand(2, 2, 3), s.a, s.b), X, a=R(2, 2, 4), b=R(2, 4, 3))
    case('bmm', lambda s, x: torch.bmm(x.reshape(2, 2, 8), s.b), X, b=R(2, 8, 3)); case('chain_matmul', lambda s, x: torch.chain_matmul(x, s.a, s.b), X, a=R(8, 3), b=R(3, 2))
    spd = (lambda a: a @ a.t() + 4 * torch.eye(4))(R(4, 4)); L_ = torch.linalg.cholesky(spd)
    rcase('cholesky_inverse', lambda s, x: LB.inv_4x4(s.L @ s.L.t()) + x[:4, :4] * 0, lambda s, x: torch.cholesky_inverse(s.L) + x[:4, :4] * 0, X, L=L_)
    rcase('cholesky_solve', lambda s, x: LB.inv_4x4(s.L @ s.L.t()) @ x[:4, :4], lambda s, x: torch.cholesky_solve(x[:4, :4], s.L), X, L=L_)
    binary('dot', lambda x, y: torch.dot(x, y).reshape(1), R(8), R(8)); binary('vdot', lambda x, y: torch.vdot(x, y).reshape(1), R(8), R(8))
    case('ger', lambda s, x: torch.ger(x, s.v), R(4), v=R(3)); case('outer', lambda s, x: torch.outer(x, s.v), R(4), v=R(3)); binary('inner', torch.inner)
    rcase('inverse', lambda s, x: LB.inv_4x4(x), lambda s, x: torch.inverse(x), R(4, 4) + 3 * torch.eye(4)); rcase('linalg.inv', lambda s, x: LB.inv_4x4(x), lambda s, x: torch.linalg.inv(x), R(4, 4) + 3 * torch.eye(4))
    rcase('det', lambda s, x: LB.det_4x4(x).reshape(1), lambda s, x: torch.det(x).reshape(1), R(4, 4)); rcase('linalg.det', lambda s, x: LB.det_4x4(x).reshape(1), lambda s, x: torch.linalg.det(x).reshape(1), R(4, 4))
    rcase('logdet', lambda s, x: torch.log(LB.det_4x4(x)).reshape(1), lambda s, x: torch.logdet(x).reshape(1), spd)
    rcase('slogdet', lambda s, x: flat(torch.sign(LB.det_4x4(x)), torch.log(LB.det_4x4(x).abs())), lambda s, x: flat(*torch.slogdet(x)), R(4, 4))
    rcase('linalg.slogdet', lambda s, x: flat(torch.sign(LB.det_4x4(x)), torch.log(LB.det_4x4(x).abs())), lambda s, x: flat(*torch.linalg.slogdet(x)), R(4, 4))
    rcase('lu', lambda s, x: flat(*LB.lu_nopivot(x)), lambda s, x: flat(*LB.lu_unpacked_nopivot_ref(x)), spd)   # on an SPD matrix partial pivoting picks the diagonal: the pivots are the identity
    rcase('lu_solve', lambda s, x: LB.inv_4x4(s.A) @ x[:4, :4], lambda s, x: torch.lu_solve(x[:4, :4], *torch.linalg.lu_factor(s.A)), X, A=spd)
    rcase('linalg.lu_factor', lambda s, x: flat(*LB.lu_nopivot(x)), lambda s, x: flat(*LB.lu_unpacked_nopivot_ref(x)), spd)
    rcase('lu_unpack', lambda s, x: flat(*LB.lu_nopivot(x)), lambda s, x: flat(*[t for t in torch.lu_unpack(*torch.linalg.lu_factor(x))][1:]), spd)
    binary('matmul', torch.matmul, y=R(8, 3)); rcase('matrix_power', lambda s, x: x @ x @ x, lambda s, x: torch.matrix_power(x, 3), R(4, 4)); rcase('linalg.matrix_power', lambda s, x: LB.inv_4x4(x) @ LB.inv_4x4(x), lambda s, x: torch.linalg.matrix_power(x, -2), R(4, 4) + 3 * torch.eye(4))
    rcase('matrix_exp', lambda s, x: LB.matrix_exp_taylor(x), lambda s, x: torch.matrix_exp(x), R(4, 4) * 0.3); rcase('linalg.matrix_exp', lambda s, x: LB.matrix_exp_taylor(x), lambda s, x: torch.linalg.matrix_exp(x), R(4, 4) * 0.3)
    binary('mm', torch.mm, y=R(8, 3)); binary('mv', torch.mv, y=R(8))
    rcase('pinverse', lambda s, x: LB.pinv_tall(x), lambda s, x: torch.pinverse(x), R(6, 3)); rcase('linalg.pinv', lambda s, x: LB.pinv_tall(x), lambda s, x: torch.linalg.pinv(x), R(6, 3))
    rcase('svd', lambda s, x: LB.svd_vals_4x4(x), lambda s, x: torch.svd(x).S, spd); rcase('trapz', lambda s, x: torch.trapz(x, dx=0.5, dim=1), lambda s, x: torch.trapz(x, dx=0.5, dim=1), X)
    unary('trapezoid', lambda x: torch.trapezoid(x, dim=1)); rcase('cumulative_trapezoid', lambda s, x: (0.5 * (x[:, 1:] + x[:, :-1])) @ s.T, lambda s, x: torch.cumulative_trapezoid(x, dim=1), X, T=torch.triu(torch.ones(7, 7)))
    rcase('triangular_solve', lambda s, x: LB.inv_4x4(s.A) @ x[:4, :4], lambda s, x: torch.triangular_solve(x[:4, :4], s.A, upper=True).solution, X, A=torch.triu(R(4, 4)) + 3 * torch.eye(4))
    rcase('lobpcg', lambda s, x: LB.power_iter_top(x, 60), lambda s, x: torch.lobpcg(x, k=1, largest=True)[0], spd, _atol=1e-3)
    # ================= foreach (lists of tensors: [x, 2x, x^2] -> the results concatenated) =================
    for n_, fn_ in [(k, getattr(torch, '_foreach_' + k)) for k in ['abs', 'acos', 'asin', 'atan', 'ceil', 'cos', 'cosh', 'erf', 'erfc', 'exp', 'expm1', 'floor', 'log', 'log10', 'log1p', 'log2', 'neg', 'tan', 'sin', 'sinh', 'round', 'sqrt', 'lgamma', 'frac', 'reciprocal', 'sigmoid', 'trunc']]:
        dom = U(4, 8) * 0.8 + 0.1
        single = {'abs': torch.abs, 'acos': LB.acos, 'asin': LB.asin, 'atan': torch.atan, 'ceil': LB.ceil, 'cos': torch.cos, 'cosh': LB.cosh, 'erf': torch.erf, 'erfc': lambda t: 1 - torch.erf(t), 'exp': torch.exp, 'expm1': torch.expm1, 'floor': torch.floor, 'log': torch.log, 'log10': torch.log10, 'log1p': torch.log1p, 'log2': LB.log2, 'neg': torch.neg, 'tan': LB.tan, 'sin': torch.sin, 'sinh': LB.sinh, 'round': torch.round, 'sqrt': torch.sqrt, 'lgamma': LB.lgamma, 'frac': torch.frac, 'reciprocal': torch.reciprocal, 'sigmoid': torch.sigmoid, 'trunc': torch.trunc}[n_]
        rcase('_foreach_' + n_, (lambda g: lambda s, x: flat(*[g(t) for t in [x, x * 0.5, x * x]]))(single), (lambda fn_: lambda s, x: flat(*fn_([x, x * 0.5, x * x])))(fn_), dom)
        rcase('_foreach_' + n_ + '_', (lambda g: lambda s, x: flat(*[g(t) for t in [x, x * 0.5, x * x]]))(single), (lambda n_: lambda s, x: (lambda ts: (getattr(torch, '_foreach_' + n_ + '_')(ts), flat(*ts))[1])([x.clone(), x * 0.5, x * x]))(n_), dom)
    rcase('_foreach_zero_', lambda s, x: torch.zeros(64) + x.reshape(-1)[0], lambda s, x: (lambda ts: (torch._foreach_zero_(ts), flat(*ts) + x.reshape(-1)[0])[1])([x.clone(), x * 2]), X)
    if name == '--list': return sorted(C)
    if name not in C: raise SystemExit('unknown case ' + name)
    return C[name]()

if __name__ == '__main__':
    if sys.argv[1] == '--list': print('\n'.join(build('--list'))); sys.exit(0)
    name, mlir_out, bin_out = sys.argv[1:4]
    m, x = build(name); m = m.eval()
    with torch.no_grad(): y = m.reference(x) if hasattr(m, 'reference') else m(x)
    with torch.no_grad(): assert torch.allclose(m(x), y, atol=getattr(m, 'atol', 1e-4), rtol=1e-4), 'exported body != reference: %g' % (m(x) - y).abs().max()
    print('%s: in %s -> out %s' % (name, list(x.shape), list(y.shape)))
    mod = export_linalg(m, x)
    open(mlir_out, 'w').write(str(mod))
    xf = np.ascontiguousarray(x.numpy()).astype(np.float32).ravel(); yf = np.ascontiguousarray(y.numpy()).astype(np.float32).ravel()
    with open(bin_out, 'wb') as f_:
        f_.write(struct.pack('i', xf.size)); f_.write(xf.tobytes()); f_.write(struct.pack('i', yf.size)); f_.write(yf.tobytes())
