# generated by hwacha-cc from fusion_embedding.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vdivuw vv4, vv0, vs59
    vmulw vv5, vv4, vs58
    vaddw vv5, vv5, vv0
    vsll vv1, vv5, vs55
    vsrl vv1, vv1, vs55
    vsll vv2, vv4, vs55
    vsrl vv2, vv2, vs55
    vsll vv3, vv2, vs57
    vlxw vv4, vs61, vv3
    vsll vv3, vv1, vs57
    vlxw vv5, vs60, vv3
    vcmpfeq.s vp1, vv4, vv5
    vmul vv2, vv2, vs56
    vadd vv2, vv2, vv1
    vaddw vv4, vs0, vs0
    @vp1 vaddw vv4, vs0, vs54
    vsxb vv4, vs62, vv2
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vlxb vv2, vs62, vv0
    vcmpeq vp2, vv2, vs0
    vpop vp2, vp2, vp2, vp2, 0x55
    vaddw vv2, vs0, vs0
    @vp2 vfadd.s vv2, vv2, vs59
    vsll vv1, vv0, vs60
    vsxw vv2, vs61, vv1
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs62
    vsrl vv2, vv0, vs61
    vmul vv2, vv2, vs60
    vlw vv3, va0
    vsll vv1, vv1, vs59
    vaddw vv4, vv3, vs0
    vstop
    .globl net_kernel_2_wt_r0_b0
net_kernel_2_wt_r0_b0:
    vlxw vv3, vs3, vv2
    vlxw vv5, vs4, vv1
    vfmul.s vv5, vv3, vv5
    vfadd.s vv4, vv4, vv5
    vstop
    .globl net_kernel_2_wt_a0
net_kernel_2_wt_a0:
    vsw vv4, va0
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048559
	addi	a4, a4, 2039
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a3
	#NO_APP
	#APP
	vmcs vs61, a1
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	li	a1, 20
	#APP
	vmcs vs59, a1
	#NO_APP
	li	a2, -20
	#APP
	vmcs vs58, a2
	#NO_APP
	li	a2, 2
	#APP
	vmcs vs57, a2
	#NO_APP
	#APP
	vmcs vs56, a1
	#NO_APP
	li	a1, 32
	li	a2, 1
	#APP
	vmcs vs55, a1
	#NO_APP
	#APP
	vmcs vs54, a2
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a4, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi1)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi1)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi0)(a2)
	mv	a5, a0
	beqz	a6, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a5, a6
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a5
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048567
	addi	a3, a3, 1019
	srli	a3, a3, 1
	not	a3, a3
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	#APP
	vmcs vs61, a2
	#NO_APP
	li	a1, 2
	lui	a2, 260096
	#APP
	vmcs vs60, a1
	#NO_APP
	#APP
	vmcs vs59, a2
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi3:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a4, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi4:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi4)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi4)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi3)(a2)
	mv	a5, a0
	beqz	a6, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a5, a6
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a5
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi6:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi8:
	auipc	a4, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi7:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi8)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi7)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi7)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi6)(a2)
	mv	a5, a0
	beqz	a6, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a5, a6
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a5
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048552
	addi	a3, a3, -1031
	srli	a3, a3, 1
	li	a4, 31
	not	a3, a3
	li	a5, 5
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs62, a4
	#NO_APP
	#APP
	vmcs vs61, a5
	#NO_APP
	li	a3, 80
	li	a4, 2
	#APP
	vmcs vs60, a3
	#NO_APP
	#APP
	vmcs vs59, a4
	#NO_APP
	#APP
	vmcs vs58, a1
	#NO_APP
.Lpcrel_hi9:
	auipc	a3, %pcrel_hi(__constant_20x32xf32)
	li	a4, 7
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi9)
	#APP
	vmcs vs57, a4
	#NO_APP
	#APP
	vmcs vs56, a3
	#NO_APP
	li	a5, 1
	li	a4, 20
	#APP
	vmcs vs55, a5
	#NO_APP
	#APP
	vmcs vs54, a4
	#NO_APP
	beqz	a0, .LBB3_9
# %bb.1:                                # %stripmine.preheader
	li	a5, 0
.Lpcrel_hi10:
	auipc	a6, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi11:
	auipc	a7, %pcrel_hi(hwacha_vl_short)
.Lpcrel_hi12:
	auipc	t0, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi13:
	auipc	t1, %pcrel_hi(net_kernel_2_wt_r0_b0)
	addi	t0, t0, %pcrel_lo(.Lpcrel_hi12)
	addi	t1, t1, %pcrel_lo(.Lpcrel_hi13)
.LBB3_2:                                # %stripmine
                                        # =>This Loop Header: Depth=1
                                        #     Child Loop BB3_7 Depth 2
	ld	t3, %pcrel_lo(.Lpcrel_hi10)(a6)
	mv	t2, a0
	beqz	t3, .LBB3_4
# %bb.3:                                # %stripmine
                                        #   in Loop: Header=BB3_2 Depth=1
	mv	t2, t3
.LBB3_4:                                # %stripmine
                                        #   in Loop: Header=BB3_2 Depth=1
	mv	t4, a0
	bltu	a0, t2, .LBB3_6
# %bb.5:                                # %stripmine
                                        #   in Loop: Header=BB3_2 Depth=1
	mv	t4, t2
.LBB3_6:                                # %stripmine
                                        #   in Loop: Header=BB3_2 Depth=1
	li	t3, 0
	#APP
	vsetvl t2, t4
	#NO_APP
	ld	t5, %pcrel_lo(.Lpcrel_hi11)(a7)
	sltu	t4, t2, t4
	or	t4, t5, t4
	sd	t4, %pcrel_lo(.Lpcrel_hi11)(a7)
	#APP
	vmca va0, a2
	#NO_APP
	#APP
	vmcs vs63, a5
	#NO_APP
	#APP
	vf 0(t0)
	#NO_APP
	mv	t4, a1
	mv	t5, a3
.LBB3_7:                                # %ct_
                                        #   Parent Loop BB3_2 Depth=1
                                        # =>  This Inner Loop Header: Depth=2
	#APP
	vmcs vs2, t3
	#NO_APP
	#APP
	vmcs vs3, t4
	#NO_APP
	#APP
	vmcs vs4, t5
	#NO_APP
	#APP
	vf 0(t1)
	#NO_APP
	addi	t3, t3, 1
	addi	t5, t5, 128
	addi	t4, t4, 4
	bne	t3, a4, .LBB3_7
# %bb.8:                                # %ct_after
                                        #   in Loop: Header=BB3_2 Depth=1
.Lpcrel_hi14:
	auipc	t3, %pcrel_hi(net_kernel_2_wt_a0)
	sub	a0, a0, t2
	addi	t3, t3, %pcrel_lo(.Lpcrel_hi14)
	#APP
	vf 0(t3)
	#NO_APP
	slli	t3, t2, 2
	add	a5, a5, t2
	add	a2, a2, t3
	bnez	a0, .LBB3_2
.LBB3_9:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -80
	.cfi_def_cfa_offset 80
	sd	ra, 72(sp)                      # 8-byte Folded Spill
	sd	s0, 64(sp)                      # 8-byte Folded Spill
	sd	s1, 56(sp)                      # 8-byte Folded Spill
	sd	s2, 48(sp)                      # 8-byte Folded Spill
	sd	s3, 40(sp)                      # 8-byte Folded Spill
	sd	s4, 32(sp)                      # 8-byte Folded Spill
	sd	s5, 24(sp)                      # 8-byte Folded Spill
	sd	s6, 16(sp)                      # 8-byte Folded Spill
	sd	s7, 8(sp)                       # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	mv	s1, a0
	li	a0, 224
	call	malloc
	mv	s0, a0
.Lpcrel_hi15:
	auipc	s5, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi16:
	auipc	s6, %pcrel_hi(hwacha_grid_size)
	addi	a0, a0, 63
	li	s4, 160
	andi	s2, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s5)
	sd	s4, %pcrel_lo(.Lpcrel_hi16)(s6)
.Lpcrel_hi17:
	auipc	a2, %pcrel_hi(.L__constant_20xf32)
	addi	a2, a2, %pcrel_lo(.Lpcrel_hi17)
	li	a0, 160
	mv	a1, s1
	mv	a3, s2
	call	net_kernel_ct
	li	a0, 704
	call	malloc
	mv	s1, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s5)
	addi	a0, a0, 63
	andi	s3, a0, -64
	sd	s4, %pcrel_lo(.Lpcrel_hi16)(s6)
	li	a0, 160
	mv	a1, s2
	mv	a2, s3
	call	net_kernel_0_ct
	li	a0, 1088
	call	malloc
	mv	s2, a0
	li	s7, 256
	addi	a0, a0, 63
	andi	s4, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi16)(s6)
	li	a0, 256
	mv	a1, s4
	call	net_kernel_1_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi15)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi16)(s6)
	li	a0, 256
	mv	a1, s3
	mv	a2, s4
	call	net_kernel_2_ct
	mv	a0, s0
	call	free
	mv	a0, s1
	call	free
	mv	a0, s2
	ld	ra, 72(sp)                      # 8-byte Folded Reload
	ld	s0, 64(sp)                      # 8-byte Folded Reload
	ld	s1, 56(sp)                      # 8-byte Folded Reload
	ld	s2, 48(sp)                      # 8-byte Folded Reload
	ld	s3, 40(sp)                      # 8-byte Folded Reload
	ld	s4, 32(sp)                      # 8-byte Folded Reload
	ld	s5, 24(sp)                      # 8-byte Folded Reload
	ld	s6, 16(sp)                      # 8-byte Folded Reload
	ld	s7, 8(sp)                       # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	addi	sp, sp, 80
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end4:
	.size	net, .Lfunc_end4-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	__constant_20x32xf32,@object    # @__constant_20x32xf32
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
__constant_20x32xf32:
	.word	0x3f6aba07                      # float 0.916901051
	.word	0xbedb64ee                      # float -0.428504407
	.word	0xbfb9f4ff                      # float -1.45278919
	.word	0xbee64a64                      # float -0.449786305
	.word	0x3f823547                      # float 1.0172509
	.word	0x3d94c750                      # float 0.0726457834
	.word	0xbf9c252b                      # float -1.21988428
	.word	0xbe8787b2                      # float -0.264707148
	.word	0x3f370912                      # float 0.714982152
	.word	0x3e2254bc                      # float 0.158526361
	.word	0x3f8d2f94                      # float 1.10301447
	.word	0xbe5d3fca                      # float -0.216063648
	.word	0x3f58cefd                      # float 0.84690839
	.word	0xbfa01057                      # float -1.25049865
	.word	0xbf0da8fc                      # float -0.553359747
	.word	0xbfe4c831                      # float -1.78735936
	.word	0x3e8b0ab8                      # float 0.271566153
	.word	0xbf8de8d7                      # float -1.10866821
	.word	0xbf56c8c3                      # float -0.83900088
	.word	0x3e481ef6                      # float 0.195430607
	.word	0x3f019852                      # float 0.506230474
	.word	0xbfe831f6                      # float -1.81402469
	.word	0xbf95f727                      # float -1.17160499
	.word	0xbffd66d6                      # float -1.9797008
	.word	0x3ea2f366                      # float 0.318263233
	.word	0xbf0035fe                      # float -0.500823855
	.word	0x3f8c59c8                      # float 1.09648991
	.word	0x3ec9e651                      # float 0.3943353
	.word	0xbfa51645                      # float -1.28974211
	.word	0x3edcf084                      # float 0.431522489
	.word	0xbfc1ca0a                      # float -1.51397824
	.word	0xbf64b674                      # float -0.893409014
	.word	0x3f92e829                      # float 1.14770997
	.word	0x3e06a634                      # float 0.13149339
	.word	0xbf4994d2                      # float -0.787427067
	.word	0x3fb706dc                      # float 1.42989683
	.word	0xbf8fc2f1                      # float -1.12313664
	.word	0x3fa963df                      # float 1.32336032
	.word	0x3fd11b43                      # float 1.63364446
	.word	0x3ebae048                      # float 0.36499238
	.word	0xbfa3052b                      # float -1.27359521
	.word	0xbcb679be                      # float -0.0222748481
	.word	0x3d9e9c2f                      # float 0.077446334
	.word	0x3f4257b4                      # float 0.759150743
	.word	0xbcf8ce34                      # float -0.0303717628
	.word	0xc007b78f                      # float -2.12057853
	.word	0x3fb824ff                      # float 1.43862903
	.word	0xbe29c24d                      # float -0.165780261
	.word	0x3e8c630e                      # float 0.274193227
	.word	0x3f8aaa56                      # float 1.08332324
	.word	0x3fc9ddb4                      # float 1.57707834
	.word	0x3e8bdc09                      # float 0.27316311
	.word	0xbf8d5052                      # float -1.10401368
	.word	0xbccbfe84                      # float -0.0249016359
	.word	0x3f241fa3                      # float 0.641107738
	.word	0x3f04c1dd                      # float 0.518583119
	.word	0xbe8064d1                      # float -0.250769168
	.word	0xbf3646f4                      # float -0.712020159
	.word	0xbebaca5d                      # float -0.364825159
	.word	0xbfafcb54                      # float -1.37339258
	.word	0x3f150529                      # float 0.582109988
	.word	0x3e8355f4                      # float 0.256515145
	.word	0x3fb71427                      # float 1.4303025
	.word	0x4004dd1d                      # float 2.07599568
	.word	0x3efebad7                      # float 0.497519225
	.word	0xbfac2b1d                      # float -1.34506571
	.word	0x3f29dd8f                      # float 0.663536965
	.word	0xc0028c10                      # float -2.03979874
	.word	0x3f9ed5dc                      # float 1.24090147
	.word	0x3ffc70c0                      # float 1.97219086
	.word	0x3fc6537a                      # float 1.5494225
	.word	0xbf6d6b89                      # float -0.927422106
	.word	0xbfa1ae1c                      # float -1.2631259
	.word	0x3e59bd9e                      # float 0.212637395
	.word	0xbf5982e2                      # float -0.849653363
	.word	0x3e939987                      # float 0.288280696
	.word	0xbe6a4b07                      # float -0.228801832
	.word	0x3f1eabca                      # float 0.619808793
	.word	0xbf2e2649                      # float -0.680271685
	.word	0x3fefb40d                      # float 1.87268221
	.word	0xbcfb889a                      # float -0.0307047851
	.word	0x3df88018                      # float 0.121338069
	.word	0x3fb72e2b                      # float 1.43109643
	.word	0xbe902e16                      # float -0.281601608
	.word	0x3ec4ea18                      # float 0.384598494
	.word	0xbe921527                      # float -0.28531763
	.word	0xbf3923ac                      # float -0.72320056
	.word	0xbfcb117e                      # float -1.58647132
	.word	0xbf82614e                      # float -1.0185945
	.word	0xc0016331                      # float -2.02167916
	.word	0x3f0bc5c9                      # float 0.545986712
	.word	0x3eae855e                      # float 0.340861261
	.word	0x3ea85f43                      # float 0.328851789
	.word	0x3fa199ce                      # float 1.26250625
	.word	0x3ffa3cbb                      # float 1.95497835
	.word	0x3f9ea4c9                      # float 1.23940384
	.word	0xbeda09f8                      # float -0.425857306
	.word	0x3f4d8c2e                      # float 0.802920222
	.word	0xbdf7c1c4                      # float -0.120975047
	.word	0x3ea8e5f5                      # float 0.329879433
	.word	0x3f6c833f                      # float 0.923877656
	.word	0x3e67600a                      # float 0.225952297
	.word	0x3f55d811                      # float 0.835328161
	.word	0xbede5324                      # float -0.434228063
	.word	0xbcac6430                      # float -0.0210438669
	.word	0xbef16241                      # float -0.471452743
	.word	0x3f312d92                      # float 0.692101598
	.word	0xbeb230d0                      # float -0.34802866
	.word	0x3ffa2cc1                      # float 1.95449078
	.word	0xbf4ed5cd                      # float -0.807949841
	.word	0xbf82c176                      # float -1.02152896
	.word	0x3e82fc87                      # float 0.255832881
	.word	0xbf0db319                      # float -0.553514063
	.word	0x3ebc4e67                      # float 0.367785662
	.word	0x3edadaa9                      # float 0.427449495
	.word	0x3f4682da                      # float 0.775434136
	.word	0xbf369cba                      # float -0.713328958
	.word	0x3e80db32                      # float 0.251672328
	.word	0xbfa93e61                      # float -1.32221615
	.word	0x3f1b95b8                      # float 0.607753276
	.word	0xbf8b7018                      # float -1.08935833
	.word	0xbe8c2749                      # float -0.273737222
	.word	0x4000e46e                      # float 2.01394224
	.word	0x3f7ae8b1                      # float 0.980113089
	.word	0x3f9ffa1a                      # float 1.24981999
	.word	0x3f6e3e8e                      # float 0.930642008
	.word	0x3e4f7ef7                      # float 0.20263277
	.word	0xbdfc37db                      # float -0.123153411
	.word	0x3ff60d3d                      # float 1.922279
	.word	0x3fd19ecd                      # float 1.63765872
	.word	0x3fa8d517                      # float 1.31900299
	.word	0xbfb97089                      # float -1.4487468
	.word	0xbe2693da                      # float -0.162673384
	.word	0xbf00d0c5                      # float -0.50318557
	.word	0x3ec53da0                      # float 0.385235786
	.word	0x3e6cf4e5                      # float 0.231402948
	.word	0xbfa7a1a8                      # float -1.30962086
	.word	0xbe7dbda4                      # float -0.247793734
	.word	0xbebb3d38                      # float -0.365701437
	.word	0x3f0f1c65                      # float 0.559027016
	.word	0x3d25b6ab                      # float 0.0404574089
	.word	0xbf6402c7                      # float -0.890667378
	.word	0xbf9d05ec                      # float -1.22674322
	.word	0x3eb39cff                      # float 0.35080716
	.word	0xbf51f03d                      # float -0.820071995
	.word	0x3fa8f932                      # float 1.32010484
	.word	0x3e097e4b                      # float 0.134270832
	.word	0x3f96cda6                      # float 1.17815089
	.word	0xbf9016ad                      # float -1.12569201
	.word	0x3f84c19a                      # float 1.03715825
	.word	0x3fd05994                      # float 1.62773371
	.word	0x3ec1e27e                      # float 0.378681123
	.word	0xbf0270fc                      # float -0.509536505
	.word	0x3f7fd674                      # float 0.999366044
	.word	0x3eb37a1c                      # float 0.350540996
	.word	0xbd4d3aaa                      # float -0.0501047745
	.word	0x3f9de57f                      # float 1.23356616
	.word	0x3f02f4dc                      # float 0.511548758
	.word	0x3fa40897                      # float 1.28151214
	.word	0x3f6c1746                      # float 0.922230124
	.word	0xbf09e4bd                      # float -0.538646519
	.word	0xbe877e77                      # float -0.264636725
	.word	0x3fc6b7fd                      # float 1.55248988
	.word	0x3f3ab015                      # float 0.729249298
	.word	0x3f87f7bb                      # float 1.06224763
	.word	0x3d6ad3df                      # float 0.0573309623
	.word	0x3fc96e12                      # float 1.57367158
	.word	0x3f7d57e3                      # float 0.989622294
	.word	0xbe790cff                      # float -0.243213639
	.word	0x3ca8a67c                      # float 0.0205871984
	.word	0xbf2ea136                      # float -0.682147384
	.word	0xbe41ae8a                      # float -0.189142376
	.word	0xbfc3fd2e                      # float -1.53116393
	.word	0x3ea1459d                      # float 0.314984232
	.word	0x3ed7448a                      # float 0.420444787
	.word	0xbf7f7780                      # float -0.997917175
	.word	0x3f4a7e7a                      # float 0.790992379
	.word	0x3f91adf0                      # float 1.13812065
	.word	0xbf325a94                      # float -0.696694613
	.word	0xbda7908e                      # float -0.0818186849
	.word	0xbffe251a                      # float -1.98550725
	.word	0x3e894bea                      # float 0.268157303
	.word	0x3f178ece                      # float 0.592022777
	.word	0xbf2be1f1                      # float -0.671416342
	.word	0x3fe09973                      # float 1.7546829
	.word	0x3efc04e7                      # float 0.492224902
	.word	0x401a8ba7                      # float 2.4147737
	.word	0xbe695306                      # float -0.227855772
	.word	0xbe1f11f2                      # float -0.155341893
	.word	0x3e89690b                      # float 0.268379539
	.word	0xbec1af67                      # float -0.378291339
	.word	0x3fdf3c17                      # float 1.7440213
	.word	0xbeceefac                      # float -0.404172301
	.word	0x4015816a                      # float 2.33602381
	.word	0x3f749a23                      # float 0.955476939
	.word	0x3f164fae                      # float 0.587153316
	.word	0xbf74dcf5                      # float -0.956496536
	.word	0xbe85b993                      # float -0.261181444
	.word	0xbe45cc18                      # float -0.193161368
	.word	0x3f517837                      # float 0.818240582
	.word	0x3f410da3                      # float 0.754114329
	.word	0xbdc21f91                      # float -0.0947867706
	.word	0x3efd1977                      # float 0.494334906
	.word	0xbf6b6194                      # float -0.919457674
	.word	0xbf4aff1d                      # float -0.792955219
	.word	0x3f1d08fc                      # float 0.613418341
	.word	0xbf6ca7a5                      # float -0.924433052
	.word	0xbf3bea30                      # float -0.734042168
	.word	0x3f3ba82c                      # float 0.733034849
	.word	0x3ec681d0                      # float 0.387709141
	.word	0xbf2932ac                      # float -0.660929441
	.word	0x3e7062f7                      # float 0.234752521
	.word	0xbf0743d2                      # float -0.528378606
	.word	0xbf5a41bd                      # float -0.852565586
	.word	0x3e6dd935                      # float 0.232273892
	.word	0xbf0b6e5b                      # float -0.544652641
	.word	0xbe16217c                      # float -0.146612108
	.word	0x3eb37d20                      # float 0.350564003
	.word	0xbee2076b                      # float -0.441462845
	.word	0xbf039375                      # float -0.513968766
	.word	0xbda99c71                      # float -0.0828179195
	.word	0x3e22fc3e                      # float 0.159165353
	.word	0xbf4550e1                      # float -0.770765364
	.word	0x3f41d819                      # float 0.757203638
	.word	0xbf96d3ab                      # float -1.17833459
	.word	0xbe2d7433                      # float -0.169388577
	.word	0xbeac9fcd                      # float -0.337156683
	.word	0xbf832d96                      # float -1.02482867
	.word	0xbbf64f8b                      # float -0.00751680648
	.word	0xbf3788dc                      # float -0.716932058
	.word	0x3f576d66                      # float 0.841513037
	.word	0x3f14a7c5                      # float 0.58068496
	.word	0xbfd9f94c                      # float -1.70292044
	.word	0xbed603e7                      # float -0.417998523
	.word	0xbebd98b0                      # float -0.370305538
	.word	0x3f80e3d9                      # float 1.00695336
	.word	0x3f7637c9                      # float 0.961788713
	.word	0xbf994272                      # float -1.19734025
	.word	0x400df170                      # float 2.21786118
	.word	0xbf8ee210                      # float -1.11627388
	.word	0x3f58d6f5                      # float 0.847029983
	.word	0xbeb6456d                      # float -0.355998427
	.word	0x3f702107                      # float 0.938003957
	.word	0x3ef2f2b4                      # float 0.474507928
	.word	0xbf993f60                      # float -1.19724655
	.word	0x3f3a0f71                      # float 0.726798117
	.word	0xbfd87811                      # float -1.69116414
	.word	0x3e9a07f1                      # float 0.300841838
	.word	0xbe88a519                      # float -0.266884595
	.word	0xbef70e06                      # float -0.482528865
	.word	0xbfd7261a                      # float -1.68085027
	.word	0xc002cdc0                      # float -2.04380798
	.word	0x3e950a4a                      # float 0.291094124
	.word	0xbe8ca94d                      # float -0.274729162
	.word	0x3ecf6872                      # float 0.405093729
	.word	0x3f02e14e                      # float 0.511250377
	.word	0xc0085204                      # float -2.13000584
	.word	0xbef7d8c2                      # float -0.484075606
	.word	0xbfcc007c                      # float -1.59376478
	.word	0x3f60b111                      # float 0.877701818
	.word	0xbe5e55eb                      # float -0.217124626
	.word	0x3dbb8e9b                      # float 0.091580592
	.word	0x3f4acce0                      # float 0.792188644
	.word	0x3ea8c055                      # float 0.329592377
	.word	0x3ffa656c                      # float 1.95622015
	.word	0x3fcd22fc                      # float 1.60263014
	.word	0xbdf1047f                      # float -0.117684357
	.word	0x3ec9a263                      # float 0.393817037
	.word	0x3f8fb5a1                      # float 1.12273037
	.word	0x3f7e0c68                      # float 0.992376804
	.word	0xbf8def3c                      # float -1.10886335
	.word	0xbfb15ea9                      # float -1.3857013
	.word	0xbf12e3fd                      # float -0.573791325
	.word	0x402e19a3                      # float 2.72031474
	.word	0x4017ba23                      # float 2.37073588
	.word	0x3f46807b                      # float 0.775397956
	.word	0x3dead933                      # float 0.114672087
	.word	0xbec2e2e8                      # float -0.380637407
	.word	0x3fc5d264                      # float 1.54548311
	.word	0xbf6e5ea9                      # float -0.931131899
	.word	0xbf368ac0                      # float -0.713054656
	.word	0x3f99c150                      # float 1.20121193
	.word	0xbf84d06e                      # float -1.03761077
	.word	0xbfcb8db5                      # float -1.59026206
	.word	0x3f90626c                      # float 1.1280036
	.word	0x3ed13e09                      # float 0.408676416
	.word	0x3f602b4b                      # float 0.875660598
	.word	0x402088af                      # float 2.5083425
	.word	0x3e822aac                      # float 0.254231811
	.word	0x3f343c8a                      # float 0.704048753
	.word	0x3f0c86c6                      # float 0.548931479
	.word	0xbf9204d3                      # float -1.14077222
	.word	0x3f4f2332                      # float 0.809130787
	.word	0x3f9b15b0                      # float 1.21159935
	.word	0x3ebc0875                      # float 0.367252022
	.word	0xbf053868                      # float -0.520391941
	.word	0x3f3e1926                      # float 0.742571235
	.word	0x3f3dc5da                      # float 0.741300225
	.word	0xbece7bef                      # float -0.403289288
	.word	0xbeacd808                      # float -0.337585688
	.word	0x3f390f62                      # float 0.722890973
	.word	0x3fd7773a                      # float 1.68332601
	.word	0x3e6bdc5d                      # float 0.230332807
	.word	0x3f9f5bb2                      # float 1.24498582
	.word	0xbede6518                      # float -0.434365034
	.word	0xbf6d635b                      # float -0.927297294
	.word	0x3ed46d07                      # float 0.414894313
	.word	0x3ffa08b9                      # float 1.95339119
	.word	0xbfa652fa                      # float -1.29940724
	.word	0x3ee8402a                      # float 0.453614533
	.word	0xbd4f2bd9                      # float -0.0505789258
	.word	0xbe97f231                      # float -0.296769649
	.word	0x3f481e4f                      # float 0.781712472
	.word	0x3f9bf50f                      # float 1.21841609
	.word	0xbe3c6a4e                      # float -0.18399927
	.word	0x3f988a87                      # float 1.19172752
	.word	0xbf49bf2e                      # float -0.78807342
	.word	0xbda3cbcf                      # float -0.0799785777
	.word	0xbebdd63d                      # float -0.370775133
	.word	0xbfaec07f                      # float -1.36524951
	.word	0xbdf73967                      # float -0.120714955
	.word	0x3fa21d71                      # float 1.26652348
	.word	0xbef58377                      # float -0.479518622
	.word	0x3fbaf93c                      # float 1.46073103
	.word	0xbf87fff2                      # float -1.06249833
	.word	0x3f26e4dc                      # float 0.651929617
	.word	0xbfe69a86                      # float -1.80159068
	.word	0x3e09aaf7                      # float 0.134441242
	.word	0x3f28002a                      # float 0.656252503
	.word	0x3fc085c4                      # float 1.5040822
	.word	0x3ddd8d02                      # float 0.108179107
	.word	0x3e27acc4                      # float 0.163744986
	.word	0x3f83f244                      # float 1.03083086
	.word	0x3f3c09c4                      # float 0.734524012
	.word	0x3fa060b5                      # float 1.25295126
	.word	0x3f6bea5c                      # float 0.92154479
	.word	0x3f3b8f46                      # float 0.732654929
	.word	0xbd8f7548                      # float -0.070047915
	.word	0xbea4e245                      # float -0.3220388
	.word	0xbf172ed2                      # float -0.590558171
	.word	0xbee8474d                      # float -0.453668982
	.word	0xbfc0a4fd                      # float -1.50503504
	.word	0x3e828378                      # float 0.254909277
	.word	0xbf1ed09f                      # float -0.620370805
	.word	0x3e5863be                      # float 0.211317986
	.word	0x3e35f931                      # float 0.177708402
	.word	0xbeeb1c6a                      # float -0.459201157
	.word	0x3f24ffbf                      # float 0.644527375
	.word	0x3ee0a87f                      # float 0.438785523
	.word	0xbf287f83                      # float -0.658195674
	.word	0x3ec3642f                      # float 0.381623715
	.word	0x3f3b09a6                      # float 0.730615973
	.word	0xbf56f76b                      # float -0.839712798
	.word	0x3f95464c                      # float 1.16620779
	.word	0x3e3d4b90                      # float 0.184858561
	.word	0x3effad12                      # float 0.499367297
	.word	0x3d8b30d6                      # float 0.0679642409
	.word	0x3bc948bb                      # float 0.00614270335
	.word	0xbe31e84c                      # float -0.173737705
	.word	0xbeb0cef0                      # float -0.345328808
	.word	0x3f9d7c1c                      # float 1.23035002
	.word	0xbf7d9ced                      # float -0.990675747
	.word	0xbf3022a6                      # float -0.688028693
	.word	0xbec3d460                      # float -0.382479668
	.word	0xbed74235                      # float -0.420426995
	.word	0x3fe83e8a                      # float 1.81440854
	.word	0xbec68c5f                      # float -0.387789696
	.word	0x3f2931d4                      # float 0.660916567
	.word	0x3e11f369                      # float 0.142530099
	.word	0xbf08a5fa                      # float -0.533782601
	.word	0x3f47aa1e                      # float 0.779939532
	.word	0x3f187bc8                      # float 0.595638751
	.word	0x3e465ae2                      # float 0.193706065
	.word	0x3fae3e16                      # float 1.36126971
	.word	0xc0216298                      # float -2.52164268
	.word	0x3ee1172d                      # float 0.439629942
	.word	0xbf09a90e                      # float -0.53773582
	.word	0x3f9e0196                      # float 1.2344234
	.word	0xbe9cfb61                      # float -0.306605369
	.word	0x3f841b17                      # float 1.03207672
	.word	0xbf6cc600                      # float -0.92489624
	.word	0xbea10839                      # float -0.314515859
	.word	0xbfbaf4df                      # float -1.46059787
	.word	0x3ec26af2                      # float 0.379722178
	.word	0xbf9894aa                      # float -1.19203687
	.word	0x3dcddf15                      # float 0.100523151
	.word	0xbf85f46c                      # float -1.04652166
	.word	0xbeb67b37                      # float -0.356408805
	.word	0xc014f6a4                      # float -2.32755375
	.word	0xbf074e9c                      # float -0.528543234
	.word	0xbeea525b                      # float -0.457659572
	.word	0x3f010bcd                      # float 0.504086316
	.word	0x3e921505                      # float 0.285316616
	.word	0x3fadccfd                      # float 1.35781825
	.word	0xbdb50c49                      # float -0.0884023383
	.word	0x3fa1a7a5                      # float 1.26292861
	.word	0xbf554cb5                      # float -0.833201706
	.word	0xbf936a93                      # float -1.15168989
	.word	0x3f987643                      # float 1.19110906
	.word	0xc00d8390                      # float -2.21115494
	.word	0x3ee3658d                      # float 0.444134146
	.word	0x3fc8b1c7                      # float 1.56792533
	.word	0xbf50381f                      # float -0.813356339
	.word	0xbf1a2a21                      # float -0.602205336
	.word	0xbf95740a                      # float -1.16760373
	.word	0xbeabed34                      # float -0.335794091
	.word	0x3f1b323c                      # float 0.606235266
	.word	0xbf51951a                      # float -0.818681359
	.word	0x3e8777a3                      # float 0.264584631
	.word	0x3e3f7eaf                      # float 0.187006697
	.word	0xbeb2a3b6                      # float -0.348905265
	.word	0x3fa89d2f                      # float 1.31729686
	.word	0x3f0281ac                      # float 0.509791136
	.word	0xbe4b0d51                      # float -0.198292986
	.word	0xbd57fb40                      # float -0.052729845
	.word	0x3f2e615f                      # float 0.681173264
	.word	0xbee16d8d                      # float -0.440288931
	.word	0x3f1849c1                      # float 0.594875395
	.word	0xbf43d6f0                      # float -0.764998435
	.word	0xbfa09dfe                      # float -1.25482154
	.word	0xbe359589                      # float -0.177328244
	.word	0x3f650011                      # float 0.894532263
	.word	0x3eaa704e                      # float 0.332888067
	.word	0x3fa46b35                      # float 1.2845217
	.word	0xbe0c5226                      # float -0.137032121
	.word	0x3f2f1232                      # float 0.683871388
	.word	0x3e78d844                      # float 0.243012488
	.word	0x3fd76507                      # float 1.68277061
	.word	0xbf7284cc                      # float -0.947338819
	.word	0x3e5532f7                      # float 0.208202228
	.word	0xbf421be9                      # float -0.758238375
	.word	0xbd667980                      # float -0.0562682152
	.word	0x3f9a184f                      # float 1.20386684
	.word	0x3fc72a1d                      # float 1.5559727
	.word	0xbfb7bfdb                      # float -1.43554246
	.word	0xbfd83001                      # float -1.68896496
	.word	0x3fa3597b                      # float 1.27616823
	.word	0xbf747a4b                      # float -0.954991042
	.word	0x3fc8fee5                      # float 1.57027876
	.word	0xbfdbcec6                      # float -1.71724772
	.word	0xc0056b75                      # float -2.08468366
	.word	0xbfba0316                      # float -1.45321918
	.word	0x3fa6ef35                      # float 1.30417502
	.word	0xbf6be2bb                      # float -0.921428382
	.word	0x3e9e8c29                      # float 0.309663087
	.word	0xbf63657d                      # float -0.888267338
	.word	0xbf09e966                      # float -0.538717628
	.word	0xbe19d494                      # float -0.150224984
	.word	0xbd0b99f4                      # float -0.034082368
	.word	0xbf3f7462                      # float -0.747869611
	.word	0x3e3d389c                      # float 0.18478626
	.word	0xbfc9d68f                      # float -1.57686031
	.word	0x3eb5d5e4                      # float 0.355147481
	.word	0xbf9e4be3                      # float -1.23669088
	.word	0x3f85f55b                      # float 1.04655015
	.word	0xbe339c9a                      # float -0.175402075
	.word	0x3f29f8a4                      # float 0.663950205
	.word	0xbfa80ad8                      # float -1.31283092
	.word	0xbf5fb510                      # float -0.873856544
	.word	0xbcb77fc0                      # float -0.0223997831
	.word	0x3e61bc69                      # float 0.22044529
	.word	0x400d5092                      # float 2.20804262
	.word	0x3f39e317                      # float 0.726121366
	.word	0xb9fb6cf4                      # float -4.79556271E-4
	.word	0x3db13e76                      # float 0.086544916
	.word	0xbf99e578                      # float -1.20231533
	.word	0x3fb611a8                      # float 1.42241383
	.word	0xbff4148b                      # float -1.90687692
	.word	0x3e7ba5bb                      # float 0.245749399
	.word	0x3e9eeec3                      # float 0.310415357
	.word	0xbfcc00e4                      # float -1.59377718
	.word	0xbf9aeeac                      # float -1.21040869
	.word	0xbf52169d                      # float -0.820657551
	.word	0xbf57058a                      # float -0.839928269
	.word	0x3e51287a                      # float 0.204255968
	.word	0xbecb7718                      # float -0.397392988
	.word	0x3faf86d8                      # float 1.3713026
	.word	0xbee8da79                      # float -0.454791814
	.word	0xbf672388                      # float -0.902885913
	.word	0xbf88dc6d                      # float -1.06922686
	.word	0x3f12b055                      # float 0.573003113
	.word	0xbe008419                      # float -0.125503913
	.word	0xbfb24922                      # float -1.39285684
	.word	0xbf5f18c3                      # float -0.871471583
	.word	0xbe9a2f47                      # float -0.301141948
	.word	0xbfd022a3                      # float -1.62605703
	.word	0x3e195be1                      # float 0.149764553
	.word	0x3f0c912e                      # float 0.549090266
	.word	0x3eeb77f5                      # float 0.459899575
	.word	0x3dee028f                      # float 0.116215818
	.word	0x3f050842                      # float 0.519657254
	.word	0xbe4c6cac                      # float -0.1996333
	.word	0xbf375083                      # float -0.716072261
	.word	0x3f906149                      # float 1.12796891
	.word	0xbf3b68c1                      # float -0.732067167
	.word	0xbef29098                      # float -0.473759413
	.word	0x3f6f6132                      # float 0.935076832
	.word	0x3f8e5d0b                      # float 1.11221445
	.word	0x3ee09266                      # float 0.438616931
	.word	0xbf62f9ed                      # float -0.886626064
	.word	0x3f9559c7                      # float 1.16680229
	.word	0xbe019dcb                      # float -0.126578495
	.word	0x3f1d8e91                      # float 0.61545664
	.word	0xbeab2aff                      # float -0.334312409
	.word	0x3f611536                      # float 0.879229903
	.word	0xbdc62a01                      # float -0.0967598035
	.word	0xbd0a8fa7                      # float -0.0338284038
	.word	0x3f3d1e98                      # float 0.738748073
	.word	0xbf409fba                      # float -0.752437234
	.word	0xbdbdc068                      # float -0.092652142
	.word	0xbf29a07e                      # float -0.662605166
	.word	0x3dd9aec5                      # float 0.106290378
	.word	0x3f410ec2                      # float 0.754131436
	.word	0x3d1067be                      # float 0.0352551863
	.word	0xbf53ee32                      # float -0.827853322
	.word	0xbfdfe159                      # float -1.74906456
	.word	0xbf4e853a                      # float -0.806720376
	.word	0x3f4783c0                      # float 0.779354095
	.word	0xbd946d5f                      # float -0.0724742338
	.word	0x3f63fe04                      # float 0.890594721
	.word	0x3ee07a80                      # float 0.438434601
	.word	0xbf4cf3cf                      # float -0.800595223
	.word	0xbfa08880                      # float -1.25416565
	.word	0xc00d5a4c                      # float -2.20863628
	.word	0xbf58fc6c                      # float -0.847601652
	.word	0x3eae4376                      # float 0.340358436
	.word	0x3fa198df                      # float 1.26247776
	.word	0x3fca8662                      # float 1.58222604
	.word	0x3fb49f17                      # float 1.41110504
	.word	0xbede2e0a                      # float -0.433945
	.word	0x3fc1fb48                      # float 1.515481
	.word	0x3f59186b                      # float 0.848028838
	.word	0x3ff8024e                      # float 1.93757033
	.word	0x3f365604                      # float 0.712249994
	.word	0x40176aff                      # float 2.36590552
	.word	0xbe55696c                      # float -0.208409965
	.word	0xbf99a44f                      # float -1.2003268
	.word	0x3fda281b                      # float 1.70434892
	.word	0xbd668bf7                      # float -0.0562858246
	.word	0x3f120a60                      # float 0.57047081
	.word	0x3ea65c7b                      # float 0.32492432
	.word	0x3fb3b621                      # float 1.40399563
	.word	0x3ed0c338                      # float 0.407739401
	.word	0x3ffe2343                      # float 1.9854511
	.word	0x3f3178b9                      # float 0.693248331
	.word	0xbf9e4346                      # float -1.23642802
	.word	0x3f4246d2                      # float 0.758893132
	.word	0xbf761efd                      # float -0.961410343
	.word	0xbe8e2663                      # float -0.277636617
	.word	0xbf068804                      # float -0.525512934
	.word	0x3f00ce46                      # float 0.503147483
	.word	0xbdd01f28                      # float -0.101621926
	.word	0xbd0916b9                      # float -0.0334689356
	.word	0xbf852e13                      # float -1.04046857
	.word	0x3f08b3b5                      # float 0.533992112
	.word	0xbf6038e7                      # float -0.87586826
	.word	0x3f18104c                      # float 0.593998671
	.word	0xbe5cec9e                      # float -0.215746373
	.word	0x3fff3192                      # float 1.99370027
	.word	0x3f40f440                      # float 0.753726959
	.word	0x3f3b3f42                      # float 0.731433988
	.word	0x3f8dc634                      # float 1.10761118
	.word	0xbea60b2a                      # float -0.324303925
	.word	0x40277179                      # float 2.61630082
	.word	0x3eb92fa9                      # float 0.361691743
	.word	0xbdf2028d                      # float -0.118168928
	.word	0xbf7e80c0                      # float -0.994152069
	.word	0x3f5cb689                      # float 0.862160265
	.word	0xbc910686                      # float -0.0177033059
	.word	0x3f3635a6                      # float 0.71175611
	.word	0xbf92b34d                      # float -1.14609683
	.word	0x3c70ea8d                      # float 0.0147043588
	.word	0xbfca7cd1                      # float -1.58193409
	.word	0x4002408b                      # float 2.03518939
	.word	0xbe6eea26                      # float -0.23331508
	.word	0xbf333f4c                      # float -0.700184584
	.word	0x4029a28d                      # float 2.65054631
	.word	0xbef480b0                      # float -0.477544308
	.word	0xbdd115ee                      # float -0.102092609
	.word	0x3fc237ac                      # float 1.51732397
	.word	0xbf6a789a                      # float -0.915902733
	.word	0xbf136370                      # float -0.575736046
	.word	0xbf9419c8                      # float -1.15703678
	.word	0x3fc8eda8                      # float 1.56975269
	.word	0xbff5c8de                      # float -1.92019248
	.word	0x3e21dacf                      # float 0.158061251
	.word	0x3f865c04                      # float 1.04968309
	.word	0xbf898554                      # float -1.07438135
	.word	0xbfe5853f                      # float -1.79312885
	.word	0x3da20f1a                      # float 0.0791303664
	.word	0x3ef07d39                      # float 0.469705373
	.word	0x3fb867bf                      # float 1.44066608
	.word	0x3cc51964                      # float 0.0240599588
	.word	0xbd437401                      # float -0.0477180518
	.word	0x3f61191f                      # float 0.879289567
	.word	0x3fad718c                      # float 1.35502768
	.word	0x3f499a92                      # float 0.787514805
	.word	0xbfa325cd                      # float -1.27459109
	.word	0x3f104edd                      # float 0.563703358
	.word	0x3f88bd33                      # float 1.0682739
	.word	0x3ee94435                      # float 0.455598503
	.word	0xbf958868                      # float -1.16822529
	.word	0xbfb21089                      # float -1.39112961
	.word	0xbdf02267                      # float -0.117253117
	.word	0xbf392bdd                      # float -0.72332555
	.word	0x3d3672d7                      # float 0.0445431136
	.word	0x3f67e49e                      # float 0.905832171
	.word	0xbfa9cf96                      # float -1.32664752
	.word	0xbe836225                      # float -0.256608158
	.word	0x3e5d7023                      # float 0.21624808
	.word	0xc01e16e5                      # float -2.47014737
	.word	0xbf8cdda3                      # float -1.10051382
	.word	0xbf6addf4                      # float -0.917449236
	.word	0xbf2b2180                      # float -0.668479919
	.word	0x3f8ed9fc                      # float 1.11602736
	.word	0xbfc6c20e                      # float -1.55279708
	.word	0xbc0d0199                      # float -0.00860633794
	.word	0x3e8312cb                      # float 0.256002754
	.word	0x4002ae25                      # float 2.04187894
	.word	0xbf351aa2                      # float -0.707437634
	.word	0x3e57ec27                      # float 0.210861787
	.word	0x3c7e3bf2                      # float 0.0155172218
	.word	0x3ed7f70d                      # float 0.421806723
	.word	0xbf90b479                      # float -1.13050759
	.word	0xbeef044d                      # float -0.466829687
	.word	0xbe965c29                      # float -0.293671876
	.word	0xbe9ddcc5                      # float -0.308324963
	.word	0x3fb81e97                      # float 1.43843353
	.word	0x3fd4ac2c                      # float 1.66150427
	.word	0xbc54db79                      # float -0.0129917795
	.word	0x3efb2fa2                      # float 0.490597785
	.word	0xbf7d694c                      # float -0.989887952
	.word	0x3f4a5ee8                      # float 0.790510654
	.word	0x3f52ac9a                      # float 0.82294619
	.word	0x3da11592                      # float 0.0786544234
	.word	0xbfbfcbce                      # float -1.49840713
	.word	0xbeff45d0                      # float -0.498579502
	.word	0xbf3ce130                      # float -0.737811089
	.word	0xbfe626c4                      # float -1.79805803
	.word	0xbdc4748f                      # float -0.0959254428
	.size	__constant_20x32xf32, 2560

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.bss
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.type	.L__constant_20xf32,@object     # @__constant_20xf32
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
.L__constant_20xf32:
	.word	0x00000000                      # float 0
	.word	0x3f800000                      # float 1
	.word	0x40000000                      # float 2
	.word	0x40400000                      # float 3
	.word	0x40800000                      # float 4
	.word	0x40a00000                      # float 5
	.word	0x40c00000                      # float 6
	.word	0x40e00000                      # float 7
	.word	0x41000000                      # float 8
	.word	0x41100000                      # float 9
	.word	0x41200000                      # float 10
	.word	0x41300000                      # float 11
	.word	0x41400000                      # float 12
	.word	0x41500000                      # float 13
	.word	0x41600000                      # float 14
	.word	0x41700000                      # float 15
	.word	0x41800000                      # float 16
	.word	0x41880000                      # float 17
	.word	0x41900000                      # float 18
	.word	0x41980000                      # float 19
	.size	.L__constant_20xf32, 80

	.section	".note.GNU-stack","",@progbits
