# generated by hwacha-cc from _foreach_asin.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    vlw vv0, va0
    vfmul.s vv1, vv0, vs63
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    vlw vv0, va0
    vfmul.s vv1, vv0, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    vlw vv0, va0
    vfsub.s vv1, vs63, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    vlw vv0, va0
    vcmpfle.s vp1, vs63, vv0
    @vp1 vaddw vv1, vv0, vs0
    @!vp1 vaddw vv1, vs63, vs0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    vlw vv0, va0
    vfsqrt.s vv1, vv0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_4_wt
net_kernel_4_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfdiv.s vv1, vv0, vv1
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_5_wt
net_kernel_5_wt:
    vpset vp0
    vlw vv0, va0
    vcmpflt.s vp1, vv0, vs0
    @vp1 vfsgnjn.s vv1, vv0, vv0
    @!vp1 vaddw vv1, vv0, vs0
    vcmpflt.s vp2, vs63, vv1
    @vp2 vfdiv.s vv0, vs63, vv1
    @!vp2 vaddw vv0, vv1, vs0
    vcmpflt.s vp3, vs62, vv0
    vfadd.s vv1, vv0, vs63
    vfadd.s vv2, vv0, vs61
    @vp3 vfdiv.s vv3, vv2, vv1
    @!vp3 vaddw vv3, vv0, vs0
    vfmul.s vv0, vv3, vv3
    vfmul.s vv1, vv0, vs60
    vfadd.s vv1, vv1, vs59
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs58
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs57
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs56
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs55
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs54
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs53
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs63
    vfmul.s vv3, vv3, vv1
    @vp3 vfadd.s vv0, vv3, vs52
    @!vp3 vaddw vv0, vv3, vs0
    @vp2 vfsub.s vv1, vs51, vv0
    @!vp2 vaddw vv1, vv0, vs0
    @vp1 vfsgnjn.s vv0, vv1, vv1
    @!vp1 vaddw vv0, vv1, vs0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_6_wt
net_kernel_6_wt:
    vpset vp0
    vlw vv0, va0
    vfmul.s vv1, vv0, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_7_wt
net_kernel_7_wt:
    vpset vp0
    vlw vv0, va0
    vfsub.s vv1, vs63, vv0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_8_wt
net_kernel_8_wt:
    vpset vp0
    vlw vv0, va0
    vcmpfle.s vp1, vs63, vv0
    @vp1 vaddw vv1, vv0, vs0
    @!vp1 vaddw vv1, vs63, vs0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_9_wt
net_kernel_9_wt:
    vpset vp0
    vlw vv0, va0
    vfsqrt.s vv1, vv0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_10_wt
net_kernel_10_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfdiv.s vv1, vv0, vv1
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_11_wt
net_kernel_11_wt:
    vpset vp0
    vlw vv0, va0
    vcmpflt.s vp1, vv0, vs0
    @vp1 vfsgnjn.s vv1, vv0, vv0
    @!vp1 vaddw vv1, vv0, vs0
    vcmpflt.s vp2, vs63, vv1
    @vp2 vfdiv.s vv0, vs63, vv1
    @!vp2 vaddw vv0, vv1, vs0
    vcmpflt.s vp3, vs62, vv0
    vfadd.s vv1, vv0, vs63
    vfadd.s vv2, vv0, vs61
    @vp3 vfdiv.s vv3, vv2, vv1
    @!vp3 vaddw vv3, vv0, vs0
    vfmul.s vv0, vv3, vv3
    vfmul.s vv1, vv0, vs60
    vfadd.s vv1, vv1, vs59
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs58
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs57
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs56
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs55
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs54
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs53
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs63
    vfmul.s vv3, vv3, vv1
    @vp3 vfadd.s vv0, vv3, vs52
    @!vp3 vaddw vv0, vv3, vs0
    @vp2 vfsub.s vv1, vs51, vv0
    @!vp2 vaddw vv1, vv0, vs0
    @vp1 vfsgnjn.s vv0, vv1, vv1
    @!vp1 vaddw vv0, vv1, vs0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_12_wt
net_kernel_12_wt:
    vpset vp0
    vlw vv0, va0
    vfmul.s vv1, vv0, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_13_wt
net_kernel_13_wt:
    vpset vp0
    vlw vv0, va0
    vfsub.s vv1, vs63, vv0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_14_wt
net_kernel_14_wt:
    vpset vp0
    vlw vv0, va0
    vcmpfle.s vp1, vs63, vv0
    @vp1 vaddw vv1, vv0, vs0
    @!vp1 vaddw vv1, vs63, vs0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_15_wt
net_kernel_15_wt:
    vpset vp0
    vlw vv0, va0
    vfsqrt.s vv1, vv0
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_16_wt
net_kernel_16_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfdiv.s vv1, vv0, vv1
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_17_wt
net_kernel_17_wt:
    vpset vp0
    vlw vv0, va0
    vcmpflt.s vp1, vv0, vs0
    @vp1 vfsgnjn.s vv1, vv0, vv0
    @!vp1 vaddw vv1, vv0, vs0
    vcmpflt.s vp2, vs63, vv1
    @vp2 vfdiv.s vv0, vs63, vv1
    @!vp2 vaddw vv0, vv1, vs0
    vcmpflt.s vp3, vs62, vv0
    vfadd.s vv1, vv0, vs63
    vfadd.s vv2, vv0, vs61
    @vp3 vfdiv.s vv3, vv2, vv1
    @!vp3 vaddw vv3, vv0, vs0
    vfmul.s vv0, vv3, vv3
    vfmul.s vv1, vv0, vs60
    vfadd.s vv1, vv1, vs59
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs58
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs57
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs56
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs55
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs54
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs53
    vfmul.s vv1, vv1, vv0
    vfadd.s vv1, vv1, vs63
    vfmul.s vv3, vv3, vv1
    @vp3 vfadd.s vv0, vv3, vs52
    @!vp3 vaddw vv0, vv3, vs0
    @vp2 vfsub.s vv1, vs51, vv0
    @!vp2 vaddw vv1, vv0, vs0
    @vp1 vfsgnjn.s vv0, vv1, vv1
    @!vp1 vaddw vv0, vv1, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_18_wt
net_kernel_18_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_19_wt
net_kernel_19_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_20_wt
net_kernel_20_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	lui	a4, 258048
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a5, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi1)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi1)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi0)(a3)
	mv	a6, a0
	beqz	a7, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a7
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a6
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi3:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a5, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi4:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi4)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi4)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi3)(a3)
	mv	a6, a0
	beqz	a7, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a7
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a7, a6
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	lui	a4, 260096
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi6:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi8:
	auipc	a5, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi7:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi8)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi7)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi7)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi6)(a3)
	mv	a6, a0
	beqz	a7, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a7
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a7, a6
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 33
	lui	a3, 55844
	slli	a2, a2, 10
	addi	a3, a3, 608
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi9:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi11:
	auipc	a4, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi10:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi11)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi10)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi10)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi9)(a2)
	mv	a5, a0
	beqz	a6, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a5, a6
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a5
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi12:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi14:
	auipc	a4, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi13:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi14)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi13)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi13)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi12)(a2)
	mv	a5, a0
	beqz	a6, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a5, a6
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a5
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_4_ct                 # -- Begin function net_kernel_4_ct
	.p2align	2
	.type	net_kernel_4_ct,@function
net_kernel_4_ct:                        # @net_kernel_4_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB5_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi15:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi17:
	auipc	a5, %pcrel_hi(net_kernel_4_wt)
.Lpcrel_hi16:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi17)
	j	.LBB5_3
.LBB5_2:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi16)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi16)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB5_7
.LBB5_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi15)(a3)
	mv	a6, a0
	beqz	a7, .LBB5_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a6, a7
.LBB5_5:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB5_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a6
	j	.LBB5_2
.LBB5_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end5:
	.size	net_kernel_4_ct, .Lfunc_end5-net_kernel_4_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_5_ct                 # -- Begin function net_kernel_5_ct
	.p2align	2
	.type	net_kernel_5_ct,@function
net_kernel_5_ct:                        # @net_kernel_5_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 52
	addi	a3, a3, 33
	lui	a4, 260096
	slli	a3, a3, 11
	lui	a5, 257345
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	addi	a3, a5, 973
	#APP
	vmcs vs62, a3
	#NO_APP
	li	a3, 383
	slli	a3, a3, 23
	lui	a4, 190
	#APP
	vmcs vs61, a3
	#NO_APP
	addi	a3, a4, -1911
	lui	a5, 251663
	slli	a3, a3, 12
	addi	a5, a5, 241
	addi	a3, a3, -1911
	#APP
	vmcs vs60, a5
	#NO_APP
	#APP
	vmcs vs59, a3
	#NO_APP
	lui	a3, 252377
	lui	a5, 194281
	addi	a3, a3, -1575
	addi	a5, a5, -1117
	#APP
	vmcs vs58, a3
	#NO_APP
	slli	a5, a5, 2
	#APP
	vmcs vs57, a5
	#NO_APP
	lui	a3, 253497
	addi	a3, a3, -455
	addi	a4, a4, 293
	#APP
	vmcs vs56, a3
	#NO_APP
	slli	a4, a4, 12
	addi	a3, a4, -1755
	lui	a4, 191
	#APP
	vmcs vs55, a3
	#NO_APP
	addi	a3, a4, -1365
	lui	a4, 255181
	slli	a3, a3, 12
	addi	a4, a4, -819
	addi	a3, a3, -1365
	#APP
	vmcs vs54, a4
	#NO_APP
	#APP
	vmcs vs53, a3
	#NO_APP
	lui	a3, 259217
	lui	a4, 261265
	addi	a3, a3, -37
	addi	a4, a4, -37
	#APP
	vmcs vs52, a3
	#NO_APP
	#APP
	vmcs vs51, a4
	#NO_APP
	beqz	a0, .LBB6_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi18:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi20:
	auipc	a5, %pcrel_hi(net_kernel_5_wt)
.Lpcrel_hi19:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi20)
	j	.LBB6_3
.LBB6_2:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi19)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi19)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB6_7
.LBB6_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi18)(a3)
	mv	a6, a0
	beqz	a7, .LBB6_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a7
.LBB6_5:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB6_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a7, a6
	j	.LBB6_2
.LBB6_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end6:
	.size	net_kernel_5_ct, .Lfunc_end6-net_kernel_5_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_6_ct                 # -- Begin function net_kernel_6_ct
	.p2align	2
	.type	net_kernel_6_ct,@function
net_kernel_6_ct:                        # @net_kernel_6_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB7_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi21:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi23:
	auipc	a5, %pcrel_hi(net_kernel_6_wt)
.Lpcrel_hi22:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi23)
	j	.LBB7_3
.LBB7_2:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi22)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi22)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB7_7
.LBB7_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi21)(a3)
	mv	a6, a0
	beqz	a7, .LBB7_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a7
.LBB7_5:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB7_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a7, a6
	j	.LBB7_2
.LBB7_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end7:
	.size	net_kernel_6_ct, .Lfunc_end7-net_kernel_6_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_7_ct                 # -- Begin function net_kernel_7_ct
	.p2align	2
	.type	net_kernel_7_ct,@function
net_kernel_7_ct:                        # @net_kernel_7_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	lui	a3, 260096
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB8_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi24:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi26:
	auipc	a4, %pcrel_hi(net_kernel_7_wt)
.Lpcrel_hi25:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi26)
	j	.LBB8_3
.LBB8_2:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi25)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi25)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB8_7
.LBB8_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi24)(a2)
	mv	a5, a0
	beqz	a6, .LBB8_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a5, a6
.LBB8_5:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB8_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	a6, a5
	j	.LBB8_2
.LBB8_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end8:
	.size	net_kernel_7_ct, .Lfunc_end8-net_kernel_7_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_8_ct                 # -- Begin function net_kernel_8_ct
	.p2align	2
	.type	net_kernel_8_ct,@function
net_kernel_8_ct:                        # @net_kernel_8_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 33
	lui	a3, 55844
	slli	a2, a2, 10
	addi	a3, a3, 608
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB9_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi27:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi29:
	auipc	a4, %pcrel_hi(net_kernel_8_wt)
.Lpcrel_hi28:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi29)
	j	.LBB9_3
.LBB9_2:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi28)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi28)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB9_7
.LBB9_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi27)(a2)
	mv	a5, a0
	beqz	a6, .LBB9_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a5, a6
.LBB9_5:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB9_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a6, a5
	j	.LBB9_2
.LBB9_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end9:
	.size	net_kernel_8_ct, .Lfunc_end9-net_kernel_8_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_9_ct                 # -- Begin function net_kernel_9_ct
	.p2align	2
	.type	net_kernel_9_ct,@function
net_kernel_9_ct:                        # @net_kernel_9_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB10_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi30:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi32:
	auipc	a4, %pcrel_hi(net_kernel_9_wt)
.Lpcrel_hi31:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi32)
	j	.LBB10_3
.LBB10_2:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi31)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi31)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB10_7
.LBB10_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi30)(a2)
	mv	a5, a0
	beqz	a6, .LBB10_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a5, a6
.LBB10_5:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB10_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a6, a5
	j	.LBB10_2
.LBB10_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end10:
	.size	net_kernel_9_ct, .Lfunc_end10-net_kernel_9_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_10_ct                # -- Begin function net_kernel_10_ct
	.p2align	2
	.type	net_kernel_10_ct,@function
net_kernel_10_ct:                       # @net_kernel_10_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB11_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi33:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi35:
	auipc	a5, %pcrel_hi(net_kernel_10_wt)
.Lpcrel_hi34:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi35)
	j	.LBB11_3
.LBB11_2:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi34)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi34)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB11_7
.LBB11_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi33)(a3)
	mv	a6, a0
	beqz	a7, .LBB11_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a6, a7
.LBB11_5:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB11_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a7, a6
	j	.LBB11_2
.LBB11_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end11:
	.size	net_kernel_10_ct, .Lfunc_end11-net_kernel_10_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_11_ct                # -- Begin function net_kernel_11_ct
	.p2align	2
	.type	net_kernel_11_ct,@function
net_kernel_11_ct:                       # @net_kernel_11_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 52
	addi	a3, a3, 33
	lui	a4, 260096
	slli	a3, a3, 11
	lui	a5, 257345
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	addi	a3, a5, 973
	#APP
	vmcs vs62, a3
	#NO_APP
	li	a3, 383
	slli	a3, a3, 23
	lui	a4, 190
	#APP
	vmcs vs61, a3
	#NO_APP
	addi	a3, a4, -1911
	lui	a5, 251663
	slli	a3, a3, 12
	addi	a5, a5, 241
	addi	a3, a3, -1911
	#APP
	vmcs vs60, a5
	#NO_APP
	#APP
	vmcs vs59, a3
	#NO_APP
	lui	a3, 252377
	lui	a5, 194281
	addi	a3, a3, -1575
	addi	a5, a5, -1117
	#APP
	vmcs vs58, a3
	#NO_APP
	slli	a5, a5, 2
	#APP
	vmcs vs57, a5
	#NO_APP
	lui	a3, 253497
	addi	a3, a3, -455
	addi	a4, a4, 293
	#APP
	vmcs vs56, a3
	#NO_APP
	slli	a4, a4, 12
	addi	a3, a4, -1755
	lui	a4, 191
	#APP
	vmcs vs55, a3
	#NO_APP
	addi	a3, a4, -1365
	lui	a4, 255181
	slli	a3, a3, 12
	addi	a4, a4, -819
	addi	a3, a3, -1365
	#APP
	vmcs vs54, a4
	#NO_APP
	#APP
	vmcs vs53, a3
	#NO_APP
	lui	a3, 259217
	lui	a4, 261265
	addi	a3, a3, -37
	addi	a4, a4, -37
	#APP
	vmcs vs52, a3
	#NO_APP
	#APP
	vmcs vs51, a4
	#NO_APP
	beqz	a0, .LBB12_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi36:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi38:
	auipc	a5, %pcrel_hi(net_kernel_11_wt)
.Lpcrel_hi37:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi38)
	j	.LBB12_3
.LBB12_2:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi37)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi37)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB12_7
.LBB12_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi36)(a3)
	mv	a6, a0
	beqz	a7, .LBB12_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a6, a7
.LBB12_5:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB12_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a7, a6
	j	.LBB12_2
.LBB12_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end12:
	.size	net_kernel_11_ct, .Lfunc_end12-net_kernel_11_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_12_ct                # -- Begin function net_kernel_12_ct
	.p2align	2
	.type	net_kernel_12_ct,@function
net_kernel_12_ct:                       # @net_kernel_12_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB13_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi39:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi41:
	auipc	a5, %pcrel_hi(net_kernel_12_wt)
.Lpcrel_hi40:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi41)
	j	.LBB13_3
.LBB13_2:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi40)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi40)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB13_7
.LBB13_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi39)(a3)
	mv	a6, a0
	beqz	a7, .LBB13_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a6, a7
.LBB13_5:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB13_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a7, a6
	j	.LBB13_2
.LBB13_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end13:
	.size	net_kernel_12_ct, .Lfunc_end13-net_kernel_12_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_13_ct                # -- Begin function net_kernel_13_ct
	.p2align	2
	.type	net_kernel_13_ct,@function
net_kernel_13_ct:                       # @net_kernel_13_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	lui	a3, 260096
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB14_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi42:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi44:
	auipc	a4, %pcrel_hi(net_kernel_13_wt)
.Lpcrel_hi43:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi44)
	j	.LBB14_3
.LBB14_2:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi43)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi43)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB14_7
.LBB14_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi42)(a2)
	mv	a5, a0
	beqz	a6, .LBB14_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a5, a6
.LBB14_5:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB14_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	a6, a5
	j	.LBB14_2
.LBB14_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end14:
	.size	net_kernel_13_ct, .Lfunc_end14-net_kernel_13_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_14_ct                # -- Begin function net_kernel_14_ct
	.p2align	2
	.type	net_kernel_14_ct,@function
net_kernel_14_ct:                       # @net_kernel_14_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 53
	addi	a2, a2, 33
	lui	a3, 55844
	slli	a2, a2, 10
	addi	a3, a3, 608
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB15_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi45:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi47:
	auipc	a4, %pcrel_hi(net_kernel_14_wt)
.Lpcrel_hi46:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi47)
	j	.LBB15_3
.LBB15_2:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi46)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi46)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB15_7
.LBB15_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi45)(a2)
	mv	a5, a0
	beqz	a6, .LBB15_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a5, a6
.LBB15_5:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB15_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a6, a5
	j	.LBB15_2
.LBB15_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end15:
	.size	net_kernel_14_ct, .Lfunc_end15-net_kernel_14_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_15_ct                # -- Begin function net_kernel_15_ct
	.p2align	2
	.type	net_kernel_15_ct,@function
net_kernel_15_ct:                       # @net_kernel_15_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB16_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi48:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi50:
	auipc	a4, %pcrel_hi(net_kernel_15_wt)
.Lpcrel_hi49:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi50)
	j	.LBB16_3
.LBB16_2:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi49)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi49)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB16_7
.LBB16_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi48)(a2)
	mv	a5, a0
	beqz	a6, .LBB16_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a5, a6
.LBB16_5:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB16_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a6, a5
	j	.LBB16_2
.LBB16_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end16:
	.size	net_kernel_15_ct, .Lfunc_end16-net_kernel_15_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_16_ct                # -- Begin function net_kernel_16_ct
	.p2align	2
	.type	net_kernel_16_ct,@function
net_kernel_16_ct:                       # @net_kernel_16_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB17_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi51:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi53:
	auipc	a5, %pcrel_hi(net_kernel_16_wt)
.Lpcrel_hi52:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi53)
	j	.LBB17_3
.LBB17_2:                               # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi52)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi52)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB17_7
.LBB17_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi51)(a3)
	mv	a6, a0
	beqz	a7, .LBB17_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a6, a7
.LBB17_5:                               # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB17_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a7, a6
	j	.LBB17_2
.LBB17_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end17:
	.size	net_kernel_16_ct, .Lfunc_end17-net_kernel_16_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_17_ct                # -- Begin function net_kernel_17_ct
	.p2align	2
	.type	net_kernel_17_ct,@function
net_kernel_17_ct:                       # @net_kernel_17_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 52
	addi	a2, a2, 33
	lui	a3, 260096
	slli	a2, a2, 11
	lui	a4, 257345
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	addi	a2, a4, 973
	#APP
	vmcs vs62, a2
	#NO_APP
	li	a2, 383
	slli	a2, a2, 23
	lui	a3, 190
	#APP
	vmcs vs61, a2
	#NO_APP
	addi	a2, a3, -1911
	lui	a4, 251663
	slli	a2, a2, 12
	addi	a4, a4, 241
	addi	a2, a2, -1911
	#APP
	vmcs vs60, a4
	#NO_APP
	#APP
	vmcs vs59, a2
	#NO_APP
	lui	a2, 252377
	lui	a4, 194281
	addi	a2, a2, -1575
	addi	a4, a4, -1117
	#APP
	vmcs vs58, a2
	#NO_APP
	slli	a4, a4, 2
	#APP
	vmcs vs57, a4
	#NO_APP
	lui	a2, 253497
	addi	a2, a2, -455
	addi	a3, a3, 293
	#APP
	vmcs vs56, a2
	#NO_APP
	slli	a3, a3, 12
	addi	a2, a3, -1755
	lui	a3, 191
	#APP
	vmcs vs55, a2
	#NO_APP
	addi	a2, a3, -1365
	lui	a3, 255181
	slli	a2, a2, 12
	addi	a3, a3, -819
	addi	a2, a2, -1365
	#APP
	vmcs vs54, a3
	#NO_APP
	#APP
	vmcs vs53, a2
	#NO_APP
	lui	a2, 259217
	lui	a3, 261265
	addi	a2, a2, -37
	addi	a3, a3, -37
	#APP
	vmcs vs52, a2
	#NO_APP
	#APP
	vmcs vs51, a3
	#NO_APP
	beqz	a0, .LBB18_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi54:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi56:
	auipc	a4, %pcrel_hi(net_kernel_17_wt)
.Lpcrel_hi55:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi56)
	j	.LBB18_3
.LBB18_2:                               # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi55)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi55)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB18_7
.LBB18_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi54)(a2)
	mv	a5, a0
	beqz	a6, .LBB18_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	a5, a6
.LBB18_5:                               # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB18_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	a6, a5
	j	.LBB18_2
.LBB18_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end18:
	.size	net_kernel_17_ct, .Lfunc_end18-net_kernel_17_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_18_ct                # -- Begin function net_kernel_18_ct
	.p2align	2
	.type	net_kernel_18_ct,@function
net_kernel_18_ct:                       # @net_kernel_18_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB19_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi57:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi59:
	auipc	a5, %pcrel_hi(net_kernel_18_wt)
.Lpcrel_hi58:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi59)
	j	.LBB19_3
.LBB19_2:                               # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi58)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi58)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB19_7
.LBB19_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi57)(a3)
	mv	a6, a0
	beqz	a7, .LBB19_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a6, a7
.LBB19_5:                               # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB19_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a7, a6
	j	.LBB19_2
.LBB19_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end19:
	.size	net_kernel_18_ct, .Lfunc_end19-net_kernel_18_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_19_ct                # -- Begin function net_kernel_19_ct
	.p2align	2
	.type	net_kernel_19_ct,@function
net_kernel_19_ct:                       # @net_kernel_19_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB20_7
# %bb.1:                                # %stripmine.preheader
	addi	a2, a2, 128
.Lpcrel_hi60:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi62:
	auipc	a5, %pcrel_hi(net_kernel_19_wt)
.Lpcrel_hi61:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi62)
	j	.LBB20_3
.LBB20_2:                               # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi61)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi61)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB20_7
.LBB20_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi60)(a3)
	mv	a6, a0
	beqz	a7, .LBB20_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	a6, a7
.LBB20_5:                               # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB20_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	a7, a6
	j	.LBB20_2
.LBB20_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end20:
	.size	net_kernel_19_ct, .Lfunc_end20-net_kernel_19_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_20_ct                # -- Begin function net_kernel_20_ct
	.p2align	2
	.type	net_kernel_20_ct,@function
net_kernel_20_ct:                       # @net_kernel_20_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB21_7
# %bb.1:                                # %stripmine.preheader
	addi	a2, a2, 256
.Lpcrel_hi63:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi65:
	auipc	a5, %pcrel_hi(net_kernel_20_wt)
.Lpcrel_hi64:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi65)
	j	.LBB21_3
.LBB21_2:                               # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi64)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi64)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB21_7
.LBB21_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi63)(a3)
	mv	a6, a0
	beqz	a7, .LBB21_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a6, a7
.LBB21_5:                               # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB21_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a7, a6
	j	.LBB21_2
.LBB21_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end21:
	.size	net_kernel_20_ct, .Lfunc_end21-net_kernel_20_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -112
	.cfi_def_cfa_offset 112
	sd	ra, 104(sp)                     # 8-byte Folded Spill
	sd	s0, 96(sp)                      # 8-byte Folded Spill
	sd	s1, 88(sp)                      # 8-byte Folded Spill
	sd	s2, 80(sp)                      # 8-byte Folded Spill
	sd	s3, 72(sp)                      # 8-byte Folded Spill
	sd	s4, 64(sp)                      # 8-byte Folded Spill
	sd	s5, 56(sp)                      # 8-byte Folded Spill
	sd	s6, 48(sp)                      # 8-byte Folded Spill
	sd	s7, 40(sp)                      # 8-byte Folded Spill
	sd	s8, 32(sp)                      # 8-byte Folded Spill
	sd	s9, 24(sp)                      # 8-byte Folded Spill
	sd	s10, 16(sp)                     # 8-byte Folded Spill
	sd	s11, 8(sp)                      # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	.cfi_offset s8, -80
	.cfi_offset s9, -88
	.cfi_offset s10, -96
	.cfi_offset s11, -104
	mv	s4, a0
	li	a0, 192
	call	malloc
	sd	a0, 0(sp)                       # 8-byte Folded Spill
	addi	a1, a0, 63
	andi	s2, a1, -64
	li	a0, 192
	call	malloc
	mv	s1, a0
.Lpcrel_hi66:
	auipc	s10, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi67:
	auipc	s11, %pcrel_hi(hwacha_grid_size)
	addi	a0, a0, 63
	li	s0, 32
	andi	s7, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s4
	mv	a2, s7
	call	net_kernel_ct
	li	a0, 192
	call	malloc
	mv	s3, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	addi	a0, a0, 63
	andi	s5, a0, -64
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s4
	mv	a2, s5
	call	net_kernel_0_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s5
	mv	a2, s2
	call	net_kernel_1_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_2_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_3_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s4
	mv	a2, s2
	call	net_kernel_4_ct
	li	a0, 192
	call	malloc
	mv	s4, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	addi	a0, a0, 63
	andi	s6, a0, -64
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	mv	a2, s6
	call	net_kernel_5_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s7
	mv	a2, s2
	call	net_kernel_6_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_7_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_8_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_9_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s7
	mv	a2, s2
	call	net_kernel_10_ct
	li	a0, 192
	call	malloc
	mv	s7, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	addi	a0, a0, 63
	andi	s8, a0, -64
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	mv	a2, s8
	call	net_kernel_11_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s5
	mv	a2, s2
	call	net_kernel_12_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_13_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_14_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_15_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s5
	mv	a2, s2
	call	net_kernel_16_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	call	net_kernel_17_ct
	li	a0, 448
	call	malloc
	mv	s5, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	addi	a0, a0, 63
	andi	s9, a0, -64
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s6
	mv	a2, s9
	call	net_kernel_18_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s8
	mv	a2, s9
	call	net_kernel_19_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s10)
	sd	s0, %pcrel_lo(.Lpcrel_hi67)(s11)
	li	a0, 32
	mv	a1, s2
	mv	a2, s9
	call	net_kernel_20_ct
	ld	a0, 0(sp)                       # 8-byte Folded Reload
	call	free
	mv	a0, s1
	call	free
	mv	a0, s3
	call	free
	mv	a0, s4
	call	free
	mv	a0, s7
	call	free
	mv	a0, s5
	ld	ra, 104(sp)                     # 8-byte Folded Reload
	ld	s0, 96(sp)                      # 8-byte Folded Reload
	ld	s1, 88(sp)                      # 8-byte Folded Reload
	ld	s2, 80(sp)                      # 8-byte Folded Reload
	ld	s3, 72(sp)                      # 8-byte Folded Reload
	ld	s4, 64(sp)                      # 8-byte Folded Reload
	ld	s5, 56(sp)                      # 8-byte Folded Reload
	ld	s6, 48(sp)                      # 8-byte Folded Reload
	ld	s7, 40(sp)                      # 8-byte Folded Reload
	ld	s8, 32(sp)                      # 8-byte Folded Reload
	ld	s9, 24(sp)                      # 8-byte Folded Reload
	ld	s10, 16(sp)                     # 8-byte Folded Reload
	ld	s11, 8(sp)                      # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	.cfi_restore s8
	.cfi_restore s9
	.cfi_restore s10
	.cfi_restore s11
	addi	sp, sp, 112
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end22:
	.size	net, .Lfunc_end22-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.section	".note.GNU-stack","",@progbits
