# generated by hwacha-cc from nanquantile.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vsd vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs59
    vsrl vv2, vv0, vs58
    vand vv3, vv2, vs59
    vsrl vv2, vv0, vs57
    vsll vv2, vv2, vs56
    vsll vv4, vv1, vs55
    vadd vv2, vv2, vv4
    vlxw vv5, vs60, vv2
    vsrl vv2, vv0, vs57
    vsll vv2, vv2, vs56
    vsll vv4, vv3, vs55
    vadd vv2, vv2, vv4
    vlxw vv6, vs62, vv2
    vcmpflt.s vp1, vv5, vv6
    vand vv2, vv0, vs54
    vsll vv3, vv3, vs58
    vadd vv2, vv2, vv3
    vadd vv2, vv2, vv1
    vaddw vv5, vs0, vs0
    @vp1 vaddw vv5, vs0, vs53
    vsxb vv5, vs61, vv2
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs59
    vsrl vv2, vv0, vs58
    vand vv3, vv2, vs59
    vsrl vv2, vv0, vs57
    vsll vv2, vv2, vs56
    vsll vv4, vv1, vs55
    vadd vv2, vv2, vv4
    vlxw vv5, vs62, vv2
    vsrl vv2, vv0, vs57
    vsll vv2, vv2, vs56
    vsll vv4, vv3, vs55
    vadd vv2, vv2, vv4
    vlxw vv6, vs60, vv2
    vcmpfeq.s vp1, vv5, vv6
    vand vv2, vv0, vs54
    vsll vv3, vv3, vs58
    vadd vv2, vv2, vv3
    vadd vv2, vv2, vv1
    vaddw vv5, vs0, vs0
    @vp1 vaddw vv5, vs0, vs53
    vsxb vv5, vs61, vv2
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vand vv1, vv0, vs60
    vsrl vv2, vv0, vs59
    vsll vv1, vv1, vs59
    vlxd vv3, vs61, vv1
    vsll vv2, vv2, vs59
    vlxd vv1, vs62, vv2
    vcmplt vp1, vv3, vv1
    vaddw vv4, vs0, vs0
    @vp1 vaddw vv4, vs0, vs58
    vsb vv4, va0
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    veidx vv0
    vadd vv0, vv0, vs63
    vlb vv2, va0
    vcmpeq vp2, vv2, vs0
    vpop vp2, vp2, vp2, vp2, 0x55
    vand vv1, vv0, vs61
    vlxb vv2, vs62, vv1
    vcmpeq vp4, vv2, vs0
    vpop vp4, vp4, vp4, vp4, 0x55
    vpop vp2, vp2, vp4, vp2, 136
    vaddw vv2, vs0, vs0
    @vp2 vaddw vv2, vs0, vs60
    vsb vv2, va0
    vstop

    .text
    .align 3
    .globl net_kernel_4_wt
net_kernel_4_wt:
    vpset vp0
    vlb vv0, va0
    vcmpeq vp2, vv0, vs0
    vpop vp2, vp2, vp2, vp2, 0x55
    vlb vv0, va1
    vcmpeq vp4, vv0, vs0
    vpop vp4, vp4, vp4, vp4, 0x55
    vpop vp2, vp2, vp4, vp2, 238
    vaddw vv0, vs0, vs0
    @vp2 vaddw vv0, vs0, vs63
    vsb vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_5_wt
net_kernel_5_wt:
    vpset vp0
    vlb vv0, va0
    vcmpeq vp2, vv0, vs0
    vpop vp2, vp2, vp2, vp2, 0x55
    vaddw vv0, vs0, vs0
    @vp2 vfadd.s vv0, vv0, vs63
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_6_wt
net_kernel_6_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_7_wt
net_kernel_7_wt:
    vpset vp0
    vlstw vv0, va0, va9
    vlw vv1, va1
    vfadd.s vv1, vv0, vv1
    vlstw vv0, va2, va10
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va3, va11
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va4, va12
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va5, va13
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va6, va14
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va7, va15
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va8, va16
    vfadd.s vv1, vv1, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_8_wt
net_kernel_8_wt:
    vpset vp0
    vlw vv0, va0
    vcmpfeq.s vp1, vv0, vs63
    vaddw vv0, vs0, vs0
    @vp1 vaddw vv0, vs0, vs62
    vsb vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_9_wt
net_kernel_9_wt:
    vpset vp0
    vlb vv0, va0
    vcmpeq vp2, vv0, vs0
    vpop vp2, vp2, vp2, vp2, 0x55
    vaddw vv0, vs0, vs0
    @vp2 vfadd.s vv0, vv0, vs63
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_10_wt
net_kernel_10_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfmul.s vv1, vv0, vv1
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_11_wt
net_kernel_11_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_12_wt
net_kernel_12_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_13_wt
net_kernel_13_wt:
    vpset vp0
    vlstw vv0, va0, va9
    vlw vv1, va1
    vfadd.s vv1, vv0, vv1
    vlstw vv0, va2, va10
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va3, va11
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va4, va12
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va5, va13
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va6, va14
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va7, va15
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va8, va16
    vfadd.s vv1, vv1, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_14_wt
net_kernel_14_wt:
    vpset vp0
    vlw vv0, va0
    vcmpfeq.s vp1, vv0, vs63
    vaddw vv0, vs0, vs0
    @vp1 vaddw vv0, vs0, vs62
    vsb vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_15_wt
net_kernel_15_wt:
    vpset vp0
    vlb vv0, va0
    vcmpeq vp2, vv0, vs0
    vpop vp2, vp2, vp2, vp2, 0x55
    vaddw vv0, vs0, vs0
    @vp2 vfadd.s vv0, vv0, vs63
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_16_wt
net_kernel_16_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfmul.s vv1, vv0, vv1
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_17_wt
net_kernel_17_wt:
    vpset vp0
    vlstw vv0, va0, va9
    vlw vv1, va1
    vfadd.s vv1, vv0, vv1
    vlstw vv0, va2, va10
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va3, va11
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va4, va12
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va5, va13
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va6, va14
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va7, va15
    vfadd.s vv1, vv1, vv0
    vlstw vv0, va8, va16
    vfadd.s vv1, vv1, vv0
    vsw vv1, va1
    vstop

    .text
    .align 3
    .globl net_kernel_18_wt
net_kernel_18_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfsub.s vv1, vv0, vv1
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_19_wt
net_kernel_19_wt:
    vpset vp0
    vlw vv0, va0
    vfmul.s vv1, vv0, vs63
    vsw vv1, va0
    vstop

    .text
    .align 3
    .globl net_kernel_20_wt
net_kernel_20_wt:
    vpset vp0
    vlw vv0, va0
    vlw vv1, va1
    vfadd.s vv1, vv0, vv1
    vsw vv1, va1
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 63
	addi	a2, a2, 513
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi0:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a5, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi1)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 3
	sd	a7, %pcrel_lo(.Lpcrel_hi1)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, t0
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi0)(a3)
	mv	a6, a0
	beqz	a7, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a7
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a7, a6
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048559
	addi	a4, a4, 2037
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	#APP
	vmcs vs61, a3
	#NO_APP
	#APP
	vmcs vs60, a1
	#NO_APP
	li	a1, 7
	#APP
	vmcs vs59, a1
	#NO_APP
	li	a1, 3
	#APP
	vmcs vs58, a1
	#NO_APP
	li	a1, 6
	#APP
	vmcs vs57, a1
	#NO_APP
	li	a1, 5
	#APP
	vmcs vs56, a1
	#NO_APP
	li	a1, 2
	#APP
	vmcs vs55, a1
	#NO_APP
	lui	a1, 262144
	addi	a1, a1, -64
	li	a2, 1
	#APP
	vmcs vs54, a1
	#NO_APP
	#APP
	vmcs vs53, a2
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi3:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi5:
	auipc	a4, %pcrel_hi(net_kernel_0_wt)
.Lpcrel_hi4:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi5)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi4)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi4)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi3)(a2)
	mv	a5, a0
	beqz	a6, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a5, a6
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a5
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048559
	addi	a4, a4, 2037
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a1
	#NO_APP
	#APP
	vmcs vs61, a3
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	li	a1, 7
	#APP
	vmcs vs59, a1
	#NO_APP
	li	a1, 3
	#APP
	vmcs vs58, a1
	#NO_APP
	li	a1, 6
	#APP
	vmcs vs57, a1
	#NO_APP
	li	a1, 5
	#APP
	vmcs vs56, a1
	#NO_APP
	li	a1, 2
	#APP
	vmcs vs55, a1
	#NO_APP
	lui	a1, 262144
	addi	a1, a1, -64
	li	a2, 1
	#APP
	vmcs vs54, a1
	#NO_APP
	#APP
	vmcs vs53, a2
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi6:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi8:
	auipc	a4, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi7:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi8)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi7)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi7)(a3)
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi6)(a2)
	mv	a5, a0
	beqz	a6, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a5, a6
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a5
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a4, 1048567
	addi	a4, a4, 2039
	srli	a4, a4, 1
	not	a4, a4
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs62, a2
	#NO_APP
	li	a2, 7
	#APP
	vmcs vs61, a1
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	li	a1, 3
	li	a2, 1
	#APP
	vmcs vs59, a1
	#NO_APP
	#APP
	vmcs vs58, a2
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
	li	a1, 0
.Lpcrel_hi9:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi11:
	auipc	a5, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi10:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi11)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi10)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi10)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmcs vs63, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a3, a3, a6
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi9)(a2)
	mv	a6, a0
	beqz	a7, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a7
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a6
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	lui	a3, 1048567
	addi	a3, a3, -1029
	srli	a3, a3, 1
	not	a3, a3
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 63
	#APP
	vmcs vs62, a2
	#NO_APP
	li	a2, 1
	#APP
	vmcs vs61, a3
	#NO_APP
	#APP
	vmcs vs60, a2
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
	li	a2, 0
.Lpcrel_hi12:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi14:
	auipc	a5, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi13:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi14)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi13)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi13)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a2, a2, a6
	add	a1, a1, a6
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi12)(a3)
	mv	a6, a0
	beqz	a7, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a7
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a7, a6
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_4_ct                 # -- Begin function net_kernel_4_ct
	.p2align	2
	.type	net_kernel_4_ct,@function
net_kernel_4_ct:                        # @net_kernel_4_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 37
	slli	a3, a3, 9
	li	a4, 1
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB5_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi15:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi17:
	auipc	a5, %pcrel_hi(net_kernel_4_wt)
.Lpcrel_hi16:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi17)
	j	.LBB5_3
.LBB5_2:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi16)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi16)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB5_7
.LBB5_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi15)(a3)
	mv	a6, a0
	beqz	a7, .LBB5_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a6, a7
.LBB5_5:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB5_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB5_3 Depth=1
	mv	a7, a6
	j	.LBB5_2
.LBB5_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end5:
	.size	net_kernel_4_ct, .Lfunc_end5-net_kernel_4_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_5_ct                 # -- Begin function net_kernel_5_ct
	.p2align	2
	.type	net_kernel_5_ct,@function
net_kernel_5_ct:                        # @net_kernel_5_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 35
	slli	a3, a3, 9
	lui	a4, 260096
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB6_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi18:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi20:
	auipc	a5, %pcrel_hi(net_kernel_5_wt)
.Lpcrel_hi19:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi20)
	j	.LBB6_3
.LBB6_2:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi19)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi19)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, t0
	beqz	a0, .LBB6_7
.LBB6_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi18)(a3)
	mv	a6, a0
	beqz	a7, .LBB6_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a6, a7
.LBB6_5:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB6_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB6_3 Depth=1
	mv	a7, a6
	j	.LBB6_2
.LBB6_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end6:
	.size	net_kernel_5_ct, .Lfunc_end6-net_kernel_5_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_6_ct                 # -- Begin function net_kernel_6_ct
	.p2align	2
	.type	net_kernel_6_ct,@function
net_kernel_6_ct:                        # @net_kernel_6_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB7_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi21:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi23:
	auipc	a4, %pcrel_hi(net_kernel_6_wt)
.Lpcrel_hi22:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi23)
	j	.LBB7_3
.LBB7_2:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi22)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi22)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB7_7
.LBB7_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi21)(a2)
	mv	a5, a0
	beqz	a6, .LBB7_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a5, a6
.LBB7_5:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB7_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB7_3 Depth=1
	mv	a6, a5
	j	.LBB7_2
.LBB7_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end7:
	.size	net_kernel_6_ct, .Lfunc_end7-net_kernel_6_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_7_ct                 # -- Begin function net_kernel_7_ct
	.p2align	2
	.type	net_kernel_7_ct,@function
net_kernel_7_ct:                        # @net_kernel_7_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 32
	#APP
	vmca va9, a3
	#NO_APP
	#APP
	vmca va10, a3
	#NO_APP
	#APP
	vmca va11, a3
	#NO_APP
	#APP
	vmca va12, a3
	#NO_APP
	#APP
	vmca va13, a3
	#NO_APP
	#APP
	vmca va14, a3
	#NO_APP
	#APP
	vmca va15, a3
	#NO_APP
	#APP
	vmca va16, a3
	#NO_APP
	beqz	a0, .LBB8_7
# %bb.1:                                # %stripmine.preheader
	addi	a3, a1, 4
	addi	a4, a1, 8
	addi	a5, a1, 12
	addi	a6, a1, 16
	addi	a7, a1, 20
	addi	t0, a1, 24
	addi	t1, a1, 28
.Lpcrel_hi24:
	auipc	t2, %pcrel_hi(hwacha_group_size)
	j	.LBB8_3
.LBB8_2:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
.Lpcrel_hi25:
	auipc	t4, %pcrel_hi(hwacha_vl_short)
	#APP
	vsetvl t5, t3
	#NO_APP
	ld	t6, %pcrel_lo(.Lpcrel_hi25)(t4)
	sltu	t3, t5, t3
	or	t3, t6, t3
.Lpcrel_hi26:
	auipc	t6, %pcrel_hi(net_kernel_7_wt)
	sd	t3, %pcrel_lo(.Lpcrel_hi25)(t4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vmca va4, a5
	#NO_APP
	#APP
	vmca va5, a6
	#NO_APP
	#APP
	vmca va6, a7
	#NO_APP
	#APP
	vmca va7, t0
	#NO_APP
	addi	t3, t6, %pcrel_lo(.Lpcrel_hi26)
	#APP
	vmca va8, t1
	#NO_APP
	#APP
	vf 0(t3)
	#NO_APP
	sub	a0, a0, t5
	slli	t3, t5, 5
	add	a1, a1, t3
	slli	t5, t5, 2
	add	a2, a2, t5
	add	a3, a3, t3
	add	a4, a4, t3
	add	a5, a5, t3
	add	a6, a6, t3
	add	a7, a7, t3
	add	t0, t0, t3
	add	t1, t1, t3
	beqz	a0, .LBB8_7
.LBB8_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t3, %pcrel_lo(.Lpcrel_hi24)(t2)
	mv	t4, a0
	beqz	t3, .LBB8_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	t4, t3
.LBB8_5:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	t3, a0
	bltu	a0, t4, .LBB8_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB8_3 Depth=1
	mv	t3, t4
	j	.LBB8_2
.LBB8_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end8:
	.size	net_kernel_7_ct, .Lfunc_end8-net_kernel_7_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_8_ct                 # -- Begin function net_kernel_8_ct
	.p2align	2
	.type	net_kernel_8_ct,@function
net_kernel_8_ct:                        # @net_kernel_8_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 53
	addi	a3, a3, 17
	lui	a4, 262144
	slli	a3, a3, 10
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 1
	#APP
	vmcs vs63, a4
	#NO_APP
	#APP
	vmcs vs62, a3
	#NO_APP
	beqz	a0, .LBB9_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi27:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi29:
	auipc	a5, %pcrel_hi(net_kernel_8_wt)
.Lpcrel_hi28:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi29)
	j	.LBB9_3
.LBB9_2:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi28)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi28)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, t0
	add	a2, a2, a6
	beqz	a0, .LBB9_7
.LBB9_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi27)(a3)
	mv	a6, a0
	beqz	a7, .LBB9_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a6, a7
.LBB9_5:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB9_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB9_3 Depth=1
	mv	a7, a6
	j	.LBB9_2
.LBB9_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end9:
	.size	net_kernel_8_ct, .Lfunc_end9-net_kernel_8_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_9_ct                 # -- Begin function net_kernel_9_ct
	.p2align	2
	.type	net_kernel_9_ct,@function
net_kernel_9_ct:                        # @net_kernel_9_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 35
	slli	a3, a3, 9
	lui	a4, 260096
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB10_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi30:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi32:
	auipc	a5, %pcrel_hi(net_kernel_9_wt)
.Lpcrel_hi31:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi32)
	j	.LBB10_3
.LBB10_2:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi31)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi31)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, t0
	beqz	a0, .LBB10_7
.LBB10_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi30)(a3)
	mv	a6, a0
	beqz	a7, .LBB10_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a6, a7
.LBB10_5:                               # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB10_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB10_3 Depth=1
	mv	a7, a6
	j	.LBB10_2
.LBB10_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end10:
	.size	net_kernel_9_ct, .Lfunc_end10-net_kernel_9_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_10_ct                # -- Begin function net_kernel_10_ct
	.p2align	2
	.type	net_kernel_10_ct,@function
net_kernel_10_ct:                       # @net_kernel_10_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB11_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi33:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi35:
	auipc	a5, %pcrel_hi(net_kernel_10_wt)
.Lpcrel_hi34:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi35)
	j	.LBB11_3
.LBB11_2:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi34)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi34)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB11_7
.LBB11_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi33)(a3)
	mv	a6, a0
	beqz	a7, .LBB11_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a6, a7
.LBB11_5:                               # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB11_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB11_3 Depth=1
	mv	a7, a6
	j	.LBB11_2
.LBB11_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end11:
	.size	net_kernel_10_ct, .Lfunc_end11-net_kernel_10_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_11_ct                # -- Begin function net_kernel_11_ct
	.p2align	2
	.type	net_kernel_11_ct,@function
net_kernel_11_ct:                       # @net_kernel_11_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB12_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi36:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi38:
	auipc	a4, %pcrel_hi(net_kernel_11_wt)
.Lpcrel_hi37:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi38)
	j	.LBB12_3
.LBB12_2:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi37)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi37)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB12_7
.LBB12_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi36)(a2)
	mv	a5, a0
	beqz	a6, .LBB12_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a5, a6
.LBB12_5:                               # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB12_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB12_3 Depth=1
	mv	a6, a5
	j	.LBB12_2
.LBB12_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end12:
	.size	net_kernel_11_ct, .Lfunc_end12-net_kernel_11_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_12_ct                # -- Begin function net_kernel_12_ct
	.p2align	2
	.type	net_kernel_12_ct,@function
net_kernel_12_ct:                       # @net_kernel_12_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB13_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi39:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi41:
	auipc	a5, %pcrel_hi(net_kernel_12_wt)
.Lpcrel_hi40:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi41)
	j	.LBB13_3
.LBB13_2:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi40)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi40)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB13_7
.LBB13_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi39)(a3)
	mv	a6, a0
	beqz	a7, .LBB13_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a6, a7
.LBB13_5:                               # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB13_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB13_3 Depth=1
	mv	a7, a6
	j	.LBB13_2
.LBB13_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end13:
	.size	net_kernel_12_ct, .Lfunc_end13-net_kernel_12_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_13_ct                # -- Begin function net_kernel_13_ct
	.p2align	2
	.type	net_kernel_13_ct,@function
net_kernel_13_ct:                       # @net_kernel_13_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 32
	#APP
	vmca va9, a3
	#NO_APP
	#APP
	vmca va10, a3
	#NO_APP
	#APP
	vmca va11, a3
	#NO_APP
	#APP
	vmca va12, a3
	#NO_APP
	#APP
	vmca va13, a3
	#NO_APP
	#APP
	vmca va14, a3
	#NO_APP
	#APP
	vmca va15, a3
	#NO_APP
	#APP
	vmca va16, a3
	#NO_APP
	beqz	a0, .LBB14_7
# %bb.1:                                # %stripmine.preheader
	addi	a3, a1, 4
	addi	a4, a1, 8
	addi	a5, a1, 12
	addi	a6, a1, 16
	addi	a7, a1, 20
	addi	t0, a1, 24
	addi	t1, a1, 28
.Lpcrel_hi42:
	auipc	t2, %pcrel_hi(hwacha_group_size)
	j	.LBB14_3
.LBB14_2:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
.Lpcrel_hi43:
	auipc	t4, %pcrel_hi(hwacha_vl_short)
	#APP
	vsetvl t5, t3
	#NO_APP
	ld	t6, %pcrel_lo(.Lpcrel_hi43)(t4)
	sltu	t3, t5, t3
	or	t3, t6, t3
.Lpcrel_hi44:
	auipc	t6, %pcrel_hi(net_kernel_13_wt)
	sd	t3, %pcrel_lo(.Lpcrel_hi43)(t4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vmca va4, a5
	#NO_APP
	#APP
	vmca va5, a6
	#NO_APP
	#APP
	vmca va6, a7
	#NO_APP
	#APP
	vmca va7, t0
	#NO_APP
	addi	t3, t6, %pcrel_lo(.Lpcrel_hi44)
	#APP
	vmca va8, t1
	#NO_APP
	#APP
	vf 0(t3)
	#NO_APP
	sub	a0, a0, t5
	slli	t3, t5, 5
	add	a1, a1, t3
	slli	t5, t5, 2
	add	a2, a2, t5
	add	a3, a3, t3
	add	a4, a4, t3
	add	a5, a5, t3
	add	a6, a6, t3
	add	a7, a7, t3
	add	t0, t0, t3
	add	t1, t1, t3
	beqz	a0, .LBB14_7
.LBB14_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t3, %pcrel_lo(.Lpcrel_hi42)(t2)
	mv	t4, a0
	beqz	t3, .LBB14_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	t4, t3
.LBB14_5:                               # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	t3, a0
	bltu	a0, t4, .LBB14_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB14_3 Depth=1
	mv	t3, t4
	j	.LBB14_2
.LBB14_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end14:
	.size	net_kernel_13_ct, .Lfunc_end14-net_kernel_13_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_14_ct                # -- Begin function net_kernel_14_ct
	.p2align	2
	.type	net_kernel_14_ct,@function
net_kernel_14_ct:                       # @net_kernel_14_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 53
	addi	a3, a3, 17
	lui	a4, 263168
	slli	a3, a3, 10
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 1
	#APP
	vmcs vs63, a4
	#NO_APP
	#APP
	vmcs vs62, a3
	#NO_APP
	beqz	a0, .LBB15_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi45:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi47:
	auipc	a5, %pcrel_hi(net_kernel_14_wt)
.Lpcrel_hi46:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi47)
	j	.LBB15_3
.LBB15_2:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi46)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi46)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, t0
	add	a2, a2, a6
	beqz	a0, .LBB15_7
.LBB15_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi45)(a3)
	mv	a6, a0
	beqz	a7, .LBB15_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a6, a7
.LBB15_5:                               # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB15_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB15_3 Depth=1
	mv	a7, a6
	j	.LBB15_2
.LBB15_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end15:
	.size	net_kernel_14_ct, .Lfunc_end15-net_kernel_14_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_15_ct                # -- Begin function net_kernel_15_ct
	.p2align	2
	.type	net_kernel_15_ct,@function
net_kernel_15_ct:                       # @net_kernel_15_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 35
	slli	a3, a3, 9
	lui	a4, 260096
	#APP
	vsetcfg a3
	#NO_APP
	#APP
	vmcs vs63, a4
	#NO_APP
	beqz	a0, .LBB16_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi48:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi50:
	auipc	a5, %pcrel_hi(net_kernel_15_wt)
.Lpcrel_hi49:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi50)
	j	.LBB16_3
.LBB16_2:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi49)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	or	a7, t0, a7
	slli	t0, a6, 2
	sd	a7, %pcrel_lo(.Lpcrel_hi49)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, t0
	beqz	a0, .LBB16_7
.LBB16_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi48)(a3)
	mv	a6, a0
	beqz	a7, .LBB16_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a6, a7
.LBB16_5:                               # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB16_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB16_3 Depth=1
	mv	a7, a6
	j	.LBB16_2
.LBB16_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end16:
	.size	net_kernel_15_ct, .Lfunc_end16-net_kernel_15_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_16_ct                # -- Begin function net_kernel_16_ct
	.p2align	2
	.type	net_kernel_16_ct,@function
net_kernel_16_ct:                       # @net_kernel_16_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB17_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi51:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi53:
	auipc	a5, %pcrel_hi(net_kernel_16_wt)
.Lpcrel_hi52:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi53)
	j	.LBB17_3
.LBB17_2:                               # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi52)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi52)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB17_7
.LBB17_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi51)(a3)
	mv	a6, a0
	beqz	a7, .LBB17_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a6, a7
.LBB17_5:                               # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB17_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB17_3 Depth=1
	mv	a7, a6
	j	.LBB17_2
.LBB17_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end17:
	.size	net_kernel_16_ct, .Lfunc_end17-net_kernel_16_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_17_ct                # -- Begin function net_kernel_17_ct
	.p2align	2
	.type	net_kernel_17_ct,@function
net_kernel_17_ct:                       # @net_kernel_17_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	li	a3, 32
	#APP
	vmca va9, a3
	#NO_APP
	#APP
	vmca va10, a3
	#NO_APP
	#APP
	vmca va11, a3
	#NO_APP
	#APP
	vmca va12, a3
	#NO_APP
	#APP
	vmca va13, a3
	#NO_APP
	#APP
	vmca va14, a3
	#NO_APP
	#APP
	vmca va15, a3
	#NO_APP
	#APP
	vmca va16, a3
	#NO_APP
	beqz	a0, .LBB18_7
# %bb.1:                                # %stripmine.preheader
	addi	a3, a1, 4
	addi	a4, a1, 8
	addi	a5, a1, 12
	addi	a6, a1, 16
	addi	a7, a1, 20
	addi	t0, a1, 24
	addi	t1, a1, 28
.Lpcrel_hi54:
	auipc	t2, %pcrel_hi(hwacha_group_size)
	j	.LBB18_3
.LBB18_2:                               # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
.Lpcrel_hi55:
	auipc	t4, %pcrel_hi(hwacha_vl_short)
	#APP
	vsetvl t5, t3
	#NO_APP
	ld	t6, %pcrel_lo(.Lpcrel_hi55)(t4)
	sltu	t3, t5, t3
	or	t3, t6, t3
.Lpcrel_hi56:
	auipc	t6, %pcrel_hi(net_kernel_17_wt)
	sd	t3, %pcrel_lo(.Lpcrel_hi55)(t4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	#APP
	vmca va3, a4
	#NO_APP
	#APP
	vmca va4, a5
	#NO_APP
	#APP
	vmca va5, a6
	#NO_APP
	#APP
	vmca va6, a7
	#NO_APP
	#APP
	vmca va7, t0
	#NO_APP
	addi	t3, t6, %pcrel_lo(.Lpcrel_hi56)
	#APP
	vmca va8, t1
	#NO_APP
	#APP
	vf 0(t3)
	#NO_APP
	sub	a0, a0, t5
	slli	t3, t5, 5
	add	a1, a1, t3
	slli	t5, t5, 2
	add	a2, a2, t5
	add	a3, a3, t3
	add	a4, a4, t3
	add	a5, a5, t3
	add	a6, a6, t3
	add	a7, a7, t3
	add	t0, t0, t3
	add	t1, t1, t3
	beqz	a0, .LBB18_7
.LBB18_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	t3, %pcrel_lo(.Lpcrel_hi54)(t2)
	mv	t4, a0
	beqz	t3, .LBB18_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	t4, t3
.LBB18_5:                               # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	t3, a0
	bltu	a0, t4, .LBB18_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB18_3 Depth=1
	mv	t3, t4
	j	.LBB18_2
.LBB18_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end18:
	.size	net_kernel_17_ct, .Lfunc_end18-net_kernel_17_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_18_ct                # -- Begin function net_kernel_18_ct
	.p2align	2
	.type	net_kernel_18_ct,@function
net_kernel_18_ct:                       # @net_kernel_18_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB19_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi57:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi59:
	auipc	a5, %pcrel_hi(net_kernel_18_wt)
.Lpcrel_hi58:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi59)
	j	.LBB19_3
.LBB19_2:                               # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi58)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi58)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB19_7
.LBB19_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi57)(a3)
	mv	a6, a0
	beqz	a7, .LBB19_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a6, a7
.LBB19_5:                               # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB19_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB19_3 Depth=1
	mv	a7, a6
	j	.LBB19_2
.LBB19_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end19:
	.size	net_kernel_18_ct, .Lfunc_end19-net_kernel_18_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_19_ct                # -- Begin function net_kernel_19_ct
	.p2align	2
	.type	net_kernel_19_ct,@function
net_kernel_19_ct:                       # @net_kernel_19_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 65
	lui	a3, 253133
	slli	a2, a2, 9
	addi	a3, a3, -819
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmcs vs63, a3
	#NO_APP
	beqz	a0, .LBB20_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi60:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi62:
	auipc	a4, %pcrel_hi(net_kernel_19_wt)
.Lpcrel_hi61:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi62)
	j	.LBB20_3
.LBB20_2:                               # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi61)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi61)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB20_7
.LBB20_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi60)(a2)
	mv	a5, a0
	beqz	a6, .LBB20_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	a5, a6
.LBB20_5:                               # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB20_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB20_3 Depth=1
	mv	a6, a5
	j	.LBB20_2
.LBB20_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end20:
	.size	net_kernel_19_ct, .Lfunc_end20-net_kernel_19_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_20_ct                # -- Begin function net_kernel_20_ct
	.p2align	2
	.type	net_kernel_20_ct,@function
net_kernel_20_ct:                       # @net_kernel_20_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 65
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB21_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi63:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi65:
	auipc	a5, %pcrel_hi(net_kernel_20_wt)
.Lpcrel_hi64:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi65)
	j	.LBB21_3
.LBB21_2:                               # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi64)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi64)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB21_7
.LBB21_3:                               # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi63)(a3)
	mv	a6, a0
	beqz	a7, .LBB21_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a6, a7
.LBB21_5:                               # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB21_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB21_3 Depth=1
	mv	a7, a6
	j	.LBB21_2
.LBB21_7:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end21:
	.size	net_kernel_20_ct, .Lfunc_end21-net_kernel_20_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -176
	.cfi_def_cfa_offset 176
	sd	ra, 168(sp)                     # 8-byte Folded Spill
	sd	s0, 160(sp)                     # 8-byte Folded Spill
	sd	s1, 152(sp)                     # 8-byte Folded Spill
	sd	s2, 144(sp)                     # 8-byte Folded Spill
	sd	s3, 136(sp)                     # 8-byte Folded Spill
	sd	s4, 128(sp)                     # 8-byte Folded Spill
	sd	s5, 120(sp)                     # 8-byte Folded Spill
	sd	s6, 112(sp)                     # 8-byte Folded Spill
	sd	s7, 104(sp)                     # 8-byte Folded Spill
	sd	s8, 96(sp)                      # 8-byte Folded Spill
	sd	s9, 88(sp)                      # 8-byte Folded Spill
	sd	s10, 80(sp)                     # 8-byte Folded Spill
	sd	s11, 72(sp)                     # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	.cfi_offset s8, -80
	.cfi_offset s9, -88
	.cfi_offset s10, -96
	.cfi_offset s11, -104
	mv	s3, a0
	li	a0, 128
	call	malloc
	sd	a0, 64(sp)                      # 8-byte Folded Spill
.Lpcrel_hi66:
	auipc	s5, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi67:
	auipc	s6, %pcrel_hi(hwacha_grid_size)
	addi	a2, a0, 63
	li	a1, 8
	andi	s1, a2, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	a1, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 8
	mv	a1, s1
	call	net_kernel_ct
	li	a0, 320
	call	malloc
	sd	a0, 56(sp)                      # 8-byte Folded Spill
	addi	a1, a0, 63
	andi	s0, a1, -64
	li	a0, 320
	call	malloc
	sd	a0, 48(sp)                      # 8-byte Folded Spill
	li	s7, 256
	addi	a1, a0, 63
	andi	s2, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 256
	mv	a1, s3
	mv	a2, s3
	mv	a3, s2
	call	net_kernel_0_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 256
	mv	a1, s3
	mv	a2, s3
	mv	a3, s0
	call	net_kernel_1_ct
	li	a0, 128
	call	malloc
	sd	a0, 40(sp)                      # 8-byte Folded Spill
	li	a2, 64
	addi	a1, a0, 63
	andi	s4, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	a2, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 64
	mv	a1, s1
	mv	a2, s1
	mv	a3, s4
	call	net_kernel_2_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 256
	mv	a1, s0
	mv	a2, s4
	call	net_kernel_3_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 256
	mv	a1, s2
	mv	a2, s0
	call	net_kernel_4_ct
	li	a0, 1088
	call	malloc
	sd	a0, 32(sp)                      # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	addi	a1, a0, 63
	andi	s1, a1, -64
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 256
	mv	a1, s0
	mv	a2, s1
	call	net_kernel_5_ct
	li	a0, 192
	call	malloc
	sd	a0, 24(sp)                      # 8-byte Folded Spill
	addi	a1, a0, 63
	andi	s10, a1, -64
	li	a0, 192
	call	malloc
	sd	a0, 16(sp)                      # 8-byte Folded Spill
	li	s7, 32
	addi	a1, a0, 63
	andi	s0, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s0
	call	net_kernel_6_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s1
	mv	a2, s0
	call	net_kernel_7_ct
	li	a0, 96
	call	malloc
	sd	a0, 8(sp)                       # 8-byte Folded Spill
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	addi	a1, a0, 63
	andi	s2, a1, -64
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s0
	mv	a2, s2
	call	net_kernel_8_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s2
	mv	a2, s10
	call	net_kernel_9_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s10
	mv	a2, s3
	call	net_kernel_10_ct
	li	a0, 80
	call	malloc
	mv	s9, a0
	li	s8, 4
	addi	a0, a0, 63
	andi	s1, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s1
	call	net_kernel_11_ct
	li	a0, 80
	call	malloc
	mv	s11, a0
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	addi	a0, a0, 63
	andi	s4, a0, -64
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s1
	mv	a2, s4
	call	net_kernel_12_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s10
	mv	a2, s4
	call	net_kernel_13_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s0
	mv	a2, s2
	call	net_kernel_14_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s2
	mv	a2, s10
	call	net_kernel_15_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s7, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 32
	mv	a1, s10
	mv	a2, s3
	call	net_kernel_16_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s10
	mv	a2, s1
	call	net_kernel_17_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s1
	mv	a2, s4
	call	net_kernel_18_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s1
	call	net_kernel_19_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi66)(s5)
	sd	s8, %pcrel_lo(.Lpcrel_hi67)(s6)
	li	a0, 4
	mv	a1, s4
	mv	a2, s1
	call	net_kernel_20_ct
	ld	a0, 64(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 56(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 48(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 40(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 32(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 24(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 16(sp)                      # 8-byte Folded Reload
	call	free
	ld	a0, 8(sp)                       # 8-byte Folded Reload
	call	free
	mv	a0, s11
	call	free
	mv	a0, s9
	ld	ra, 168(sp)                     # 8-byte Folded Reload
	ld	s0, 160(sp)                     # 8-byte Folded Reload
	ld	s1, 152(sp)                     # 8-byte Folded Reload
	ld	s2, 144(sp)                     # 8-byte Folded Reload
	ld	s3, 136(sp)                     # 8-byte Folded Reload
	ld	s4, 128(sp)                     # 8-byte Folded Reload
	ld	s5, 120(sp)                     # 8-byte Folded Reload
	ld	s6, 112(sp)                     # 8-byte Folded Reload
	ld	s7, 104(sp)                     # 8-byte Folded Reload
	ld	s8, 96(sp)                      # 8-byte Folded Reload
	ld	s9, 88(sp)                      # 8-byte Folded Reload
	ld	s10, 80(sp)                     # 8-byte Folded Reload
	ld	s11, 72(sp)                     # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	.cfi_restore s8
	.cfi_restore s9
	.cfi_restore s10
	.cfi_restore s11
	addi	sp, sp, 176
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end22:
	.size	net, .Lfunc_end22-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.section	".note.GNU-stack","",@progbits
