void gr_base(float * P, float * T, float * Y, float * C, float TCONV, float PCONV);
void ratt_kernel(float * T, float * RF, float TCONV);
void rdsmh_kernel(float * T, float * EG, float TCONV);
void ratt2_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt3_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt4_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt5_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt6_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt7_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt8_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt9_kernel(float * T, float * RF, float * RB, float * EG, float TCONV);
void ratt10_kernel(float * T, float * RKLOW, float TCONV);
void ratx_kernel(float * T, float * C, float * RF, float * RB, float * RKLOW, float TCONV);
void ratxb_kernel(float * T, float * C, float * RF, float * RB, float * RKLOW, float TCONV);
void ratx2_kernel(float * C, float * RF);
void ratx4_kernel(float * C, float * RB);
void qssa_kernel(float * RF, float * RB, float * A);
void qssab_kernel(float * RF, float * RB, float * A);
void qssa2_kernel(float * RF, float * RB, float * A);
void rdwdot_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot2_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot3_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot6_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot7_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot8_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot9_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
void rdwdot10_kernel(float * RKF, float * RKR, float * WDOT, float rateconv, float * molwt);
