# generated by hwacha-cc from convolve.ll
# ---- worker threads (vector-fetch blocks) ----

    .text
    .align 3
    .globl net_kernel_wt
net_kernel_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_0_wt
net_kernel_0_wt:
    vpset vp0
    vlstw vv0, va0, va2
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_1_wt
net_kernel_1_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_2_wt
net_kernel_2_wt:
    vpset vp0
    vlw vv0, va0
    vsw vv0, va1
    vstop

    .text
    .align 3
    .globl net_kernel_3_wt
net_kernel_3_wt:
    vpset vp0
    vaddw vv0, vs0, vs0
    vsw vv0, va0
    vstop

    .text
    .align 3
    .globl net_kernel_4_wt
net_kernel_4_wt:
    vpset vp0
    vlw vv0, va0
    vaddw vv1, vv0, vs0
    vstop
    .globl net_kernel_4_wt_r0_b0
net_kernel_4_wt_r0_b0:
    vlw vv0, va1
    vfmul.s vv2, vv0, vs3
    vfadd.s vv1, vv1, vv2
    vstop
    .globl net_kernel_4_wt_a0
net_kernel_4_wt_a0:
    vsw vv1, va0
    vstop

# ---- control threads (from llc) ----
	.file	"hwacha-ct"
	.text
	.globl	net_kernel_ct                   # -- Begin function net_kernel_ct
	.p2align	2
	.type	net_kernel_ct,@function
net_kernel_ct:                          # @net_kernel_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB0_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi0:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi2:
	auipc	a4, %pcrel_hi(net_kernel_wt)
.Lpcrel_hi1:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi2)
	j	.LBB0_3
.LBB0_2:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi1)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi1)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB0_7
.LBB0_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi0)(a2)
	mv	a5, a0
	beqz	a6, .LBB0_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a5, a6
.LBB0_5:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB0_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB0_3 Depth=1
	mv	a6, a5
	j	.LBB0_2
.LBB0_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end0:
	.size	net_kernel_ct, .Lfunc_end0-net_kernel_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_0_ct                 # -- Begin function net_kernel_0_ct
	.p2align	2
	.type	net_kernel_0_ct,@function
net_kernel_0_ct:                        # @net_kernel_0_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	li	a3, -4
	#APP
	vsetcfg a2
	#NO_APP
	#APP
	vmca va2, a3
	#NO_APP
	beqz	a0, .LBB1_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi3:
	auipc	a3, %pcrel_hi(__constant_1x9xf32+32)
.Lpcrel_hi4:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi6:
	auipc	a5, %pcrel_hi(net_kernel_0_wt)
	addi	a3, a3, %pcrel_lo(.Lpcrel_hi3)
.Lpcrel_hi5:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi6)
	j	.LBB1_3
.LBB1_2:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi5)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi5)(a4)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vmca va1, a1
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	sub	a3, a3, a6
	add	a1, a1, a6
	beqz	a0, .LBB1_7
.LBB1_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi4)(a2)
	mv	a6, a0
	beqz	a7, .LBB1_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a6, a7
.LBB1_5:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB1_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB1_3 Depth=1
	mv	a7, a6
	j	.LBB1_2
.LBB1_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end1:
	.size	net_kernel_0_ct, .Lfunc_end1-net_kernel_0_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_1_ct                 # -- Begin function net_kernel_1_ct
	.p2align	2
	.type	net_kernel_1_ct,@function
net_kernel_1_ct:                        # @net_kernel_1_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB2_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi7:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi9:
	auipc	a4, %pcrel_hi(net_kernel_1_wt)
.Lpcrel_hi8:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi9)
	j	.LBB2_3
.LBB2_2:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi8)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi8)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB2_7
.LBB2_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi7)(a2)
	mv	a5, a0
	beqz	a6, .LBB2_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a5, a6
.LBB2_5:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB2_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB2_3 Depth=1
	mv	a6, a5
	j	.LBB2_2
.LBB2_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end2:
	.size	net_kernel_1_ct, .Lfunc_end2-net_kernel_1_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_2_ct                 # -- Begin function net_kernel_2_ct
	.p2align	2
	.type	net_kernel_2_ct,@function
net_kernel_2_ct:                        # @net_kernel_2_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a3, -1
	slli	a3, a3, 54
	addi	a3, a3, 33
	slli	a3, a3, 9
	#APP
	vsetcfg a3
	#NO_APP
	beqz	a0, .LBB3_7
# %bb.1:                                # %stripmine.preheader
	addi	a2, a2, 32
.Lpcrel_hi10:
	auipc	a3, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi12:
	auipc	a5, %pcrel_hi(net_kernel_2_wt)
.Lpcrel_hi11:
	auipc	a4, %pcrel_hi(hwacha_vl_short)
	addi	a5, a5, %pcrel_lo(.Lpcrel_hi12)
	j	.LBB3_3
.LBB3_2:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	#APP
	vsetvl a6, a7
	#NO_APP
	ld	t0, %pcrel_lo(.Lpcrel_hi11)(a4)
	sltu	a7, a6, a7
	sub	a0, a0, a6
	slli	a6, a6, 2
	or	a7, t0, a7
	sd	a7, %pcrel_lo(.Lpcrel_hi11)(a4)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vmca va1, a2
	#NO_APP
	#APP
	vf 0(a5)
	#NO_APP
	add	a1, a1, a6
	add	a2, a2, a6
	beqz	a0, .LBB3_7
.LBB3_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a7, %pcrel_lo(.Lpcrel_hi10)(a3)
	mv	a6, a0
	beqz	a7, .LBB3_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a6, a7
.LBB3_5:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a0
	bltu	a0, a6, .LBB3_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB3_3 Depth=1
	mv	a7, a6
	j	.LBB3_2
.LBB3_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end3:
	.size	net_kernel_2_ct, .Lfunc_end3-net_kernel_2_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_3_ct                 # -- Begin function net_kernel_3_ct
	.p2align	2
	.type	net_kernel_3_ct,@function
net_kernel_3_ct:                        # @net_kernel_3_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a2, -1
	slli	a2, a2, 54
	addi	a2, a2, 33
	slli	a2, a2, 9
	#APP
	vsetcfg a2
	#NO_APP
	beqz	a0, .LBB4_7
# %bb.1:                                # %stripmine.preheader
.Lpcrel_hi13:
	auipc	a2, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi15:
	auipc	a4, %pcrel_hi(net_kernel_3_wt)
.Lpcrel_hi14:
	auipc	a3, %pcrel_hi(hwacha_vl_short)
	addi	a4, a4, %pcrel_lo(.Lpcrel_hi15)
	j	.LBB4_3
.LBB4_2:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	#APP
	vsetvl a5, a6
	#NO_APP
	ld	a7, %pcrel_lo(.Lpcrel_hi14)(a3)
	sltu	a6, a5, a6
	sub	a0, a0, a5
	slli	a5, a5, 2
	or	a6, a7, a6
	sd	a6, %pcrel_lo(.Lpcrel_hi14)(a3)
	#APP
	vmca va0, a1
	#NO_APP
	#APP
	vf 0(a4)
	#NO_APP
	add	a1, a1, a5
	beqz	a0, .LBB4_7
.LBB4_3:                                # %stripmine
                                        # =>This Inner Loop Header: Depth=1
	ld	a6, %pcrel_lo(.Lpcrel_hi13)(a2)
	mv	a5, a0
	beqz	a6, .LBB4_5
# %bb.4:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a5, a6
.LBB4_5:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a0
	bltu	a0, a5, .LBB4_2
# %bb.6:                                # %stripmine
                                        #   in Loop: Header=BB4_3 Depth=1
	mv	a6, a5
	j	.LBB4_2
.LBB4_7:                                # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end4:
	.size	net_kernel_3_ct, .Lfunc_end4-net_kernel_3_ct
	.cfi_endproc
                                        # -- End function
	.globl	net_kernel_4_ct                 # -- Begin function net_kernel_4_ct
	.p2align	2
	.type	net_kernel_4_ct,@function
net_kernel_4_ct:                        # @net_kernel_4_ct
	.cfi_startproc
# %bb.0:                                # %entry
	li	a4, -1
	slli	a4, a4, 54
	addi	a4, a4, 97
	slli	a4, a4, 9
	#APP
	vsetcfg a4
	#NO_APP
	#APP
	vmcs vs63, a2
	#NO_APP
	li	a5, 1
	li	a4, 9
	#APP
	vmcs vs62, a5
	#NO_APP
	#APP
	vmcs vs61, a4
	#NO_APP
	beqz	a0, .LBB5_10
# %bb.1:                                # %stripmine.preheader
	addi	sp, sp, -16
	.cfi_def_cfa_offset 16
	sd	s0, 8(sp)                       # 8-byte Folded Spill
	.cfi_offset s0, -8
	li	a5, 0
.Lpcrel_hi16:
	auipc	a6, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi18:
	auipc	t0, %pcrel_hi(net_kernel_4_wt)
.Lpcrel_hi17:
	auipc	a7, %pcrel_hi(hwacha_vl_short)
	addi	t0, t0, %pcrel_lo(.Lpcrel_hi18)
.Lpcrel_hi19:
	auipc	t1, %pcrel_hi(net_kernel_4_wt_r0_b0)
.Lpcrel_hi20:
	auipc	t2, %pcrel_hi(net_kernel_4_wt_a0)
	addi	t1, t1, %pcrel_lo(.Lpcrel_hi19)
	addi	t2, t2, %pcrel_lo(.Lpcrel_hi20)
.LBB5_2:                                # %stripmine
                                        # =>This Loop Header: Depth=1
                                        #     Child Loop BB5_7 Depth 2
	ld	t4, %pcrel_lo(.Lpcrel_hi16)(a6)
	mv	t3, a0
	beqz	t4, .LBB5_4
# %bb.3:                                # %stripmine
                                        #   in Loop: Header=BB5_2 Depth=1
	mv	t3, t4
.LBB5_4:                                # %stripmine
                                        #   in Loop: Header=BB5_2 Depth=1
	mv	t5, a0
	bltu	a0, t3, .LBB5_6
# %bb.5:                                # %stripmine
                                        #   in Loop: Header=BB5_2 Depth=1
	mv	t5, t3
.LBB5_6:                                # %stripmine
                                        #   in Loop: Header=BB5_2 Depth=1
	li	t4, 0
	#APP
	vsetvl t3, t5
	#NO_APP
	ld	t6, %pcrel_lo(.Lpcrel_hi17)(a7)
	sltu	t5, t3, t5
	or	t5, t6, t5
	slli	t6, a5, 2
	sd	t5, %pcrel_lo(.Lpcrel_hi17)(a7)
	#APP
	vmca va0, a3
	#NO_APP
	#APP
	vf 0(t0)
	#NO_APP
	add	t5, a1, t6
	mv	t6, a2
.LBB5_7:                                # %ct_
                                        #   Parent Loop BB5_2 Depth=1
                                        # =>  This Inner Loop Header: Depth=2
	#APP
	vmcs vs2, t4
	#NO_APP
	lwu	s0, 0(t6)
	addi	t4, t4, 1
	#APP
	vmcs vs3, s0
	#NO_APP
	#APP
	vmca va1, t5
	#NO_APP
	#APP
	vf 0(t1)
	#NO_APP
	addi	t5, t5, 4
	addi	t6, t6, 4
	bne	t4, a4, .LBB5_7
# %bb.8:                                # %ct_after
                                        #   in Loop: Header=BB5_2 Depth=1
	sub	a0, a0, t3
	add	a5, a5, t3
	slli	t3, t3, 2
	#APP
	vf 0(t2)
	#NO_APP
	add	a3, a3, t3
	bnez	a0, .LBB5_2
# %bb.9:
	ld	s0, 8(sp)                       # 8-byte Folded Reload
	.cfi_restore s0
	addi	sp, sp, 16
	.cfi_def_cfa_offset 0
.LBB5_10:                               # %done
	#APP
	fence
	#NO_APP
	ret
.Lfunc_end5:
	.size	net_kernel_4_ct, .Lfunc_end5-net_kernel_4_ct
	.cfi_endproc
                                        # -- End function
	.globl	net                             # -- Begin function net
	.p2align	2
	.type	net,@function
net:                                    # @net
	.cfi_startproc
# %bb.0:
	addi	sp, sp, -80
	.cfi_def_cfa_offset 80
	sd	ra, 72(sp)                      # 8-byte Folded Spill
	sd	s0, 64(sp)                      # 8-byte Folded Spill
	sd	s1, 56(sp)                      # 8-byte Folded Spill
	sd	s2, 48(sp)                      # 8-byte Folded Spill
	sd	s3, 40(sp)                      # 8-byte Folded Spill
	sd	s4, 32(sp)                      # 8-byte Folded Spill
	sd	s5, 24(sp)                      # 8-byte Folded Spill
	sd	s6, 16(sp)                      # 8-byte Folded Spill
	sd	s7, 8(sp)                       # 8-byte Folded Spill
	sd	s8, 0(sp)                       # 8-byte Folded Spill
	.cfi_offset ra, -8
	.cfi_offset s0, -16
	.cfi_offset s1, -24
	.cfi_offset s2, -32
	.cfi_offset s3, -40
	.cfi_offset s4, -48
	.cfi_offset s5, -56
	.cfi_offset s6, -64
	.cfi_offset s7, -72
	.cfi_offset s8, -80
	mv	s2, a0
	li	a0, 100
	call	malloc
	mv	s0, a0
.Lpcrel_hi21:
	auipc	s6, %pcrel_hi(hwacha_group_size)
.Lpcrel_hi22:
	auipc	s7, %pcrel_hi(hwacha_grid_size)
	addi	a0, a0, 63
	li	s3, 9
	andi	s1, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi21)(s6)
	sd	s3, %pcrel_lo(.Lpcrel_hi22)(s7)
	li	a0, 9
	mv	a1, s1
	call	net_kernel_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi21)(s6)
	sd	s3, %pcrel_lo(.Lpcrel_hi22)(s7)
	li	a0, 9
	mv	a1, s1
	call	net_kernel_0_ct
	li	a0, 640
	call	malloc
	mv	s3, a0
	li	a0, 144
	addi	a1, s3, 63
	andi	s4, a1, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi21)(s6)
	sd	a0, %pcrel_lo(.Lpcrel_hi22)(s7)
	li	a0, 144
	mv	a1, s4
	call	net_kernel_1_ct
	li	a0, 128
	sd	zero, %pcrel_lo(.Lpcrel_hi21)(s6)
	sd	a0, %pcrel_lo(.Lpcrel_hi22)(s7)
	li	a0, 128
	mv	a1, s2
	mv	a2, s4
	call	net_kernel_2_ct
	li	a0, 608
	call	malloc
	mv	s2, a0
	li	s8, 136
	addi	a0, a0, 63
	andi	s5, a0, -64
	sd	zero, %pcrel_lo(.Lpcrel_hi21)(s6)
	sd	s8, %pcrel_lo(.Lpcrel_hi22)(s7)
	li	a0, 136
	mv	a1, s5
	call	net_kernel_3_ct
	sd	zero, %pcrel_lo(.Lpcrel_hi21)(s6)
	sd	s8, %pcrel_lo(.Lpcrel_hi22)(s7)
	li	a0, 136
	mv	a1, s4
	mv	a2, s1
	mv	a3, s5
	call	net_kernel_4_ct
	mv	a0, s0
	call	free
	mv	a0, s3
	call	free
	mv	a0, s2
	ld	ra, 72(sp)                      # 8-byte Folded Reload
	ld	s0, 64(sp)                      # 8-byte Folded Reload
	ld	s1, 56(sp)                      # 8-byte Folded Reload
	ld	s2, 48(sp)                      # 8-byte Folded Reload
	ld	s3, 40(sp)                      # 8-byte Folded Reload
	ld	s4, 32(sp)                      # 8-byte Folded Reload
	ld	s5, 24(sp)                      # 8-byte Folded Reload
	ld	s6, 16(sp)                      # 8-byte Folded Reload
	ld	s7, 8(sp)                       # 8-byte Folded Reload
	ld	s8, 0(sp)                       # 8-byte Folded Reload
	.cfi_restore ra
	.cfi_restore s0
	.cfi_restore s1
	.cfi_restore s2
	.cfi_restore s3
	.cfi_restore s4
	.cfi_restore s5
	.cfi_restore s6
	.cfi_restore s7
	.cfi_restore s8
	addi	sp, sp, 80
	.cfi_def_cfa_offset 0
	ret
.Lfunc_end6:
	.size	net, .Lfunc_end6-net
	.cfi_endproc
                                        # -- End function
	.type	hwacha_vl_short,@object         # @hwacha_vl_short
	.bss
	.weak	hwacha_vl_short
	.p2align	3, 0x0
hwacha_vl_short:
	.quad	0                               # 0x0
	.size	hwacha_vl_short, 8

	.type	__constant_1x9xf32,@object      # @__constant_1x9xf32
	.section	.rodata,"a",@progbits
	.p2align	6, 0x0
__constant_1x9xf32:
	.word	0x3df307b8                      # float 0.118667066
	.word	0x3cdbe794                      # float 0.0268438235
	.word	0xbd4eb297                      # float -0.0504632853
	.word	0xbe113b44                      # float -0.141827643
	.word	0xbf17571c                      # float -0.591172934
	.word	0x3e40f28b                      # float 0.188425228
	.word	0xbd0b0a7a                      # float -0.0339455381
	.word	0x3e0e4492                      # float 0.13893345
	.word	0x3dcd16e7                      # float 0.100141339
	.size	__constant_1x9xf32, 36

	.type	hwacha_grid_size,@object        # @hwacha_grid_size
	.bss
	.weak	hwacha_grid_size
	.p2align	3, 0x0
hwacha_grid_size:
	.quad	0                               # 0x0
	.size	hwacha_grid_size, 8

	.type	hwacha_group_size,@object       # @hwacha_group_size
	.weak	hwacha_group_size
	.p2align	3, 0x0
hwacha_group_size:
	.quad	0                               # 0x0
	.size	hwacha_group_size, 8

	.section	".note.GNU-stack","",@progbits
